### ISSUE TITLE
README needs updating

### ISSUE THREAD

**Issue by RJacksonm1** [RJacksonm1/node-dota2#102]
For missing methods and events I have at least added stubs with f70cfa19425ee8947b0234a6fd6212724ab8d2a7, but it is pretty sucky regardless.  Need to go through it and re-document every method and event in a consistent format; linking to protos where appropriate.

**Comment by jimmydorry** [comment]
Major readme update. Should cover all of the large changes.

https://github.com/RJacksonm1/node-dota2/pull/132

**Comment by jimmydorry** [comment]
Still needs to cover outdated regions, i believe.

https://github.com/RJacksonm1/node-dota2/issues/113

**Comment by howardchung** [comment]
Think the README is in a decent state thanks to @Crazy-Duck.

We can patch it later with more details (no functionality change)
