### ISSUE TITLE
GC not ready code duplication

### ISSUE THREAD

**Issue by paralin** [RJacksonm1/node-dota2#107]
It's really messy to write "gc not ready" literally everywhere in the codebase. Would be better to clean this up with a helper function.

**Comment by jimmydorry** [comment]
Signal whether https://github.com/RJacksonm1/node-dota2/pull/109 addresses it.

**Comment by jimmydorry** [comment]
Still heaps of not readys on a quick browse.

**Comment by howardchung** [comment]
Enhancement, doesn't change functionality.  I'm fine with deferring this to a later refactor+version bump.

**Comment by jimmydorry** [comment]
This is the last legacy issue remaining.

If no one wants to sponsor it, I'm happy to have it closed.

Someone that cares about coding standards and improving readability is more than welcome to make a helper function.

**Comment by Crazy-Duck** [comment]
I'll have a look at it, can't promise anything for 2.0.0 though

**Comment by Crazy-Duck** [comment]
I've started the refactoring on my dev branch, I'll try and do the entire thing during this week

**Comment by jimmydorry** [comment]
No rush really. I just wanted to close the remaining tickets so we have a clean slate.

A helper function would make the code a bit more readable, but isn't particularly high priority.

**Comment by jimmydorry** [comment]
@paralin You should take a quick squiz at the nice changes @Crazy-Duck made. Particularly around the way the callback works when GC isn't ready and how all of the payload constructors were adjusted to match. The callback arguments are apparently `-1, null` now.

**Comment by jimmydorry** [comment]
Forgot to link to the PR https://github.com/RJacksonm1/node-dota2/pull/177

**Comment by Crazy-Duck** [comment]
The arguments are purely indicative, I just used the first thing that came to mind that didn't overlap with any existing eresults. Feel free to change :)
