### ISSUE TITLE
outdated ServerRegions

### ISSUE THREAD

**Issue by howardchung** [RJacksonm1/node-dota2#113]
The current ServerRegions shipping with node-dota2 is out of date.  I think Dotabuff maintains a current listing by automatically extracting the data from the client:

https://github.com/dotabuff/d2vpk/blob/master/json/dota_pak01/scripts/regions.json

We can either keep it manually updated or write a script to pull data from there (part of update script) or something.

EDIT: new one for reborn
https://github.com/dotabuff/d2vpkr/blob/master/dota/scripts/regions.json

**Comment by paralin** [comment]
A lot of this stuff comes from intercepting and interpreting packets in WireShark. I saw a lot of interesting data about the Datagram network before they rolled it out that way.

There's also a lot of data on the CDN about these things.

**Comment by jimmydorry** [comment]
There is no good solution (both automatic and robust) right now. The people most likely to be using that data will probably figure out how to update it manually or eventually look at updating their dependency (this library), when it gets out of date.

I'll tag this as an enhancement for now and leave it open for now. Someone may find a good way to keep it in sync later on, but I am not expecting anything to fix this in the short term.

**Comment by howardchung** [comment]
We could simply drop that data from node-dota2 and have the user maintain their own mappings.

**Comment by jimmydorry** [comment]
It's fine to have a set of defaults that are occasionally updated.

**Comment by Crazy-Duck** [comment]
It should be properly documented as such then I think with a notice in the ReadMe

**Comment by jimmydorry** [comment]
Readme to mention considerations.
