### ISSUE TITLE
commit which removed messages.js introduced link error

### ISSUE THREAD

**Issue by Crazy-Duck** [RJacksonm1/node-dota2#115]
Introduced in commit 955f2d866f4aa26b99d809e93c78f2729bdaa9f9 

There is still a reference to ./messages in index.js

**Comment by howardchung** [comment]
whoops.  I probably should have mentioned that I hadn't tested it fully.  Can you fix it?

**Comment by Crazy-Duck** [comment]
Busy doing the commit ;)

**Comment by Crazy-Duck** [comment]
Hmm, upon further testing, this is not the only issue it seems. Gonna have to refactor all handlers to replace mentions to the previously defined sub-schema's I think 
``` Javascript
Dota2.schema.EDOTAGCMsg.k_EMsgGCChatMessage
```
to 
``` Javascript
Dota2.schema.k_EMsgGCChatMessage
```

And I'm having trouble with this relative reference when including the library in another project
``` Javascript
var folder = fs.readdirSync('./proto');
```

**Comment by Crazy-Duck** [comment]
Handlers refactored, still the problem that fs.readdirSync searches relative to process.cwd() and **not** relative to the current script...

**Comment by howardchung** [comment]
I think we neeed to use __dirname:

https://nodejs.org/api/globals.html#globals_dirname

**Comment by Crazy-Duck** [comment]
Adding __dirname seems to work now, refactoring wasn't necessary after all, just needed to update the proto files. However my connection remains unreliable for now, still got to find out why..

**Comment by Crazy-Duck** [comment]
Alright, apparently I forgot to fix the client hello I messed up earlier. I added the require for the helper handler again, everything seems to work as it should now

**Comment by Crazy-Duck** [comment]
Closed after merge
