### ISSUE TITLE
Implement player profile card handling

### ISSUE THREAD

**Issue by paralin** [RJacksonm1/node-dota2#118]
cc @howardchung

I think the profile requests we're using are the Source 1 compat version. You can specify "engine" and the default is still Source1. Also, in Nethook the response I'm seeing for the profile is far more extensive than I'm seeing in node-dota2, and private profiles from Source 1 are still returning error 15 while they are always visible in Source 2.

**Comment by paralin** [comment]
They're almost the same response (a lot of the data is empty in Source 2) but Source 2 will never respond with error 15 (it's not possible to make a private profile in Source 2).

So this patch actually fixes a lot of problems with profile fetching.

**Comment by howardchung** [comment]
Wow, so you can actually get anyone's MMR now?

**Comment by paralin** [comment]
Yeah, seems so. Haven't tried without friend yet

**Comment by howardchung** [comment]
Will check later.  It would be nice to be able to avoid the friending step
but any display of MMR data still must be voluntary to avoid angry Valve.

**Comment by paralin** [comment]
@howardchung Confirming that friend status is not required for profile checks.

**Comment by howardchung** [comment]
Somebody should probably tell Valve that. . . I feel like this is a security issue

**Comment by paralin** [comment]
@howardchung Done :)

**Comment by howardchung** [comment]
Merged this change, @Crazy-Duck 's fix, and latest state of this branch into:
https://github.com/yasp-dota/node-dota2/tree/dev

Tested with player profiles and match details, both works.

Also confirmed that all players' MMR data is available.

**Comment by howardchung** [comment]
I feel that this is probably more likely a mistake rather than intended, so I'm not going to build any features with it.  Maybe if they don't do anything about it for a month...

**Comment by paralin** [comment]
See my email @howardchung

**Comment by jimmydorry** [comment]
Definitely doesn't sound like an intended feature.

**Comment by paralin** [comment]
Also see my email @jimmydorry

**Comment by howardchung** [comment]
I didn't get any email

**Comment by paralin** [comment]
Apparently my mails are filtered now

**Comment by jimmydorry** [comment]
Yea, it was shitlisted for me...

**Comment by paralin** [comment]
.. making a new email domain

**Comment by jimmydorry** [comment]
No need to do that, when this is a configuration issue.

https://support.google.com/mail/answer/81126

Set your SPF. A quick look at the mail header saw this:

Received-SPF: neutral (google.com: 209.85.160.175 is neither permitted nor denied by best guess record for domain of XXXX@XXXX.in) client-ip=209.85.160.175;

**Comment by paralin** [comment]
Thanks, fixed.

**Comment by howardchung** [comment]
Thanks for the update.  It would be nice to avoid the whole friending process.  It would save a lot of code if we just try to read a player's profile and display the data if available.

**Comment by Crazy-Duck** [comment]
The change might actually be intended, since it's now possible to advertise your MMR on your profile. I've played plenty of matches where I could see people's MMR on their profile page, without being friends.

**Comment by howardchung** [comment]
Yeah, but presumably you're not supposed to be able to see players' MMR if
they haven't put it on their profile.

**Comment by Crazy-Duck** [comment]
Hmm, mind that this would completely defeat the current system used by both dotabuff and yasp, where you have to friend a bot to track your MMR. Further more it would severely limit peoples options on their profile page. This would imply that if you want to have your MMR tracked, you'd be obligated to publish it on your profile and, seeing as there are but two slots, you won't be able to publish your commends, join date, ... anymore.

**Comment by howardchung** [comment]
I like it because the user doesn't have to do anything application specific in order to display their MMR.  Making people friend a bot is kind of hacky and the code behind it isn't that pretty either.

I feel that some people wouldn't be happy if we started publicly revealing their MMR without opting in, even if Valve is okay with it.  Limiting it to people who have set their profile to display it is a nice simple solution.

That said, it would be cool to have some complete data on MMR distribution.

**Comment by Crazy-Duck** [comment]
It might help to give you guys a more accurate representation of match skill level, draw stats on avg MMR in a game, variance, ...  you could actually analyse winrate based on MMR variance within a match. This opens a lot of possibilities

**Comment by paralin** [comment]
It opens a lot of possibilities but it's not the intended behavior by valve
and may be patched in the coming few days.

**Comment by paralin** [comment]
@howardchung @Crazy-Duck @jimmydorry As of the last patch, the profile request has been disabled for non-friends. The profile card request still works, though! So theoretically if they had MMR displayed on their profile you can get it without friend status.l

**Comment by howardchung** [comment]
node-dota2 doesn't have the profile card call implemented yet it looks like.  I suppose we can add it if we want to.  Valve will probably eventually disable the Source 1 profile fetching at some point (like how they removed the Source 1 combat log events recently).

**Comment by paralin** [comment]
It should be implemented for sure. It's fairly simple. 

According to them it won't be removed for a long while, if it will be at all. It's used in other places too.

**Comment by paralin** [comment]
Whoops, misclick.

Anyway, make sure engine: 1 is specified. That should help with the private profile errors.

**Comment by paralin** [comment]
If someone wants to implement the profile card handling it's probably a nice entry level contribution.

Reference C# code: https://github.com/sbx320/Dota2/commit/402e28dc78867b167349bacb9b0120a9af4b6722

**Comment by Crazy-Duck** [comment]
Should be easy enough, I'll look into it this week

**Comment by Crazy-Duck** [comment]
@paralin btw you sure profileRequests for non-friends are disabled? I just tried with a random ID I pulled of yasp and I still get MMR results...

**Comment by paralin** [comment]
If it isn't now it will be within a couple days

**Comment by Crazy-Duck** [comment]
basic support implemented in 695517c0bc3112af6042c8925826feecb3b86130 #123

**Comment by jimmydorry** [comment]
Merged

**Comment by jimmydorry** [comment]
Merged. Close this issue after testing it.

**Comment by jimmydorry** [comment]
No reports of errors.
