### ISSUE TITLE
I follow the installation guide but I receive "Object #<SteamClient> has no method 'logOn'"

### ISSUE THREAD

**Issue by mfandre** [RJacksonm1/node-dota2#122]
I'm trying to run the node-dota2 but after install (following the guide) I'm receiving the follow error: "Object #<SteamClient> has no method 'logOn'" on execute "node index.js" (inside test folder). 

Am I missing something?
Thx in Advance

**Comment by Crazy-Duck** [comment]
Which version are you running?

**Comment by jimmydorry** [comment]
Stale question, significant library improvements since.
