### ISSUE TITLE
Dota 2 update appears to have broken requestProfile

### ISSUE THREAD

**Issue by petridw** [RJacksonm1/node-dota2#124]
Since the Dota 2 client update earlier today I'm getting back an err 80 in the requestProfile callback which appears to indicate that the request is disabled according to the [eresult enum](https://github.com/SteamRE/SteamKit/blob/master/Resources/SteamLanguage/eresult.steamd#L86). I'm wondering if maybe they updated the protobuf message signatures for this request since a few of the patch notes indicate potential changes to the internal API (Fixed dashboard performance impact of the friends list, enabled team matchmaking).

Tried on a couple diff steam accounts so I don't think it's that I'm rate limited or anything, plus I don't think I'd get a response back anyway if I was. I'm running a version a few commits back in the 1.0.0 branch so in the meantime I'll try a more recent commit and see if that fixes anything.

**Comment by howardchung** [comment]
Looks like Valve is getting rid of the old player profiles and moving to profileCards?

@paralin might have a better idea of what's going on.

Sample response:
```
{"account_id":88367253,"background_def_index":0,"slots":[{"slot_id":0,"trophy":null,"stat":{"stat_id":5,"stat_score":2122},"item":null,"hero":null,"emoticon":null},{"slot_id":1,"trophy":null,"stat":{"stat_id":1,"stat_score":3911},"item":null,"hero":null,"emoticon":null},{"slot_id":2,"trophy":null,"stat":null,"item":null,"hero":{"hero_id":53,"hero_wins":156,"hero_losses":null},"emoticon":null},{"slot_id":3,"trophy":null,"stat":null,"item":null,"hero":{"hero_id":109,"hero_wins":129,"hero_losses":null},"emoticon":null},{"slot_id":4,"trophy":null,"stat":null,"item":null,"hero":{"hero_id":77,"hero_wins":91,"hero_losses":null},"emoticon":null}],"badge_points":4475,"event_points":null,"event_id":null}
```

**Comment by howardchung** [comment]
For reference, stat_ids:
https://github.com/SteamDatabase/GameTracking/blob/c6903e73783d4affafdd619610a8e13b4db282e7/Protobufs/dota/dota_gcmessages_common.proto#L1619

**Comment by paralin** [comment]
Changes I have heard of:

 - Profile requests only work when friends
 - You MUST specify engine:1 in the request. See the PR I submitted before.

Other than that it should work.

**Comment by howardchung** [comment]
Tried it with friend+engine, still was getting error: 80.

You could double-check

**Comment by petridw** [comment]
I'm trying with friends + engine as well, same thing.

**Comment by paralin** [comment]
Confirming error 80 now. The call has been disabled. Time to port to profile cards.

**Comment by petridw** [comment]
Ah cool, hadn't seen the discussion about profile cards until now. The implementation from @Crazy-Duck  is working well for me for the moment.

Does this mean we need to tell our friends to put their MMRs on their profile if we want to be able to track it now?

**Comment by paralin** [comment]
Yeah. You need to display it in the profile if you want to track it. Guessing @howardchung isn't getting much sleep right now.

**Comment by howardchung** [comment]
lol, actually I already implemented it a couple hours ago (it only took about 30 minutes):
https://github.com/yasp-dota/yasp/commit/f2b662bcb6e799ee023830a438601ab65a2e2cd3

However, I did it on development branch and may not deploy for a couple weeks.  MMR tracking is pretty low priority.

**Comment by jimmydorry** [comment]
I don't remember if this was fully actioned. Anyone remember?

**Comment by imayhaveborkedit** [comment]
I believe this was fixed with #138 ?

**Comment by norf33rus** [comment]
Response from profileRequest is error 80

**Comment by jimmydorry** [comment]
Error 80 is "disabled". Are you using a non-limited account? Try it manually. This may also mean something else.

**Comment by Crazy-Duck** [comment]
Isn't requestProfile discontinued by valve? It was replaced by the profileCard if I'm not mistaken.. 
On 25 Nov 2015 22:22, jimmydorry <notifications@github.com> wrote:Error 80 is "disabled". Are you using a non-limited account? Try it manually. This may also mean something else.

**Comment by norf33rus** [comment]
non-limited accout.. what does it mean? i'l just try fetch a mmr, from requestProfile. Now i can do it from profileCard if user select it

**Comment by jimmydorry** [comment]
Replaced by profileCard. No longer an issue.
