### ISSUE TITLE
Change callbacks to promises

### ISSUE THREAD

**Issue by Crazy-Duck** [RJacksonm1/node-dota2#126]
@macnibblet proposes to refactor the API to switch from callbacks to promises. I think this might simplify usage of the library (might significantly change certain calls though), I just don't know how this will interact with the underlying node-steam calls... Thoughts?

**Comment by macnibblet** [comment]
Well it will make the public api a lot cleaner, my main concern is that node-steam will still require callback style, and mixing the two styles of coding might not be the idea.

**Comment by macnibblet** [comment]
@noggan, follow dis!

**Comment by Crazy-Duck** [comment]
That's my main concern as well, mixing promises with callbacks usually leads to quite horrible looking code blocks.. I think it might be better to hold of on this until node-steam makes the switch. You might want to create a similar issue over there :)

**Comment by macnibblet** [comment]
Lol, well node-steam is not onboard. Hmm, well ill see if I might fork the thing.

**Comment by jimmydorry** [comment]
RIP

**Comment by Crazy-Duck** [comment]
Oh well, close it up I guess

**Comment by jimmydorry** [comment]
@macnibblet open this or another issue when you have something to work with or have some points of further discussion.

Good luck.
