### ISSUE TITLE
How does one leave a ongoing match as a spectator or after it has finished ? 

### ISSUE THREAD

**Issue by macnibblet** [RJacksonm1/node-dota2#127]
Title says pretty much everything, I can't find the correct command to leave with.

**Comment by Crazy-Duck** [comment]
Have you tried leavePracticeLobby() ?

**Comment by idreamshen** [comment]
maybe abandonGame()

**Comment by macnibblet** [comment]
A combination of both abandomGame and leavePractiseLobby kinda works, but leavePraticseLobby gives result 2, abanomGame has no result at all ?

**Comment by Crazy-Duck** [comment]
Hmm, might want to try to implement CMsgCancelWatchGame and give that one a go. Or, if you really want to be sure, just run nethook while you're spectating a game and the leave it. Normally you'll have a full trace of all messages exchanged with the GameCoordinator, this should point you in the right direction.

**Comment by macnibblet** [comment]
Gah, totally missed that one as well, gonna try that later today.

**Comment by jimmydorry** [comment]
Report back if you see potential feature engancements.

**Comment by macnibblet** [comment]
I have plenty in my fork of the project, but i'm currently still only working on a prototype. If it all works out as i hope ill do a huge pull request with cleanup and stuff for 1.0.0

**Comment by jimmydorry** [comment]
Great. Make a new issue or PR when you are ready. :)
