### ISSUE TITLE
Fail in protobuf compilation

### ISSUE THREAD

**Issue by Flumaster** [RJacksonm1/node-dota2#128]
Could you help me, guys? Or could you give compiled protobuf?

protobuf_for_node.target.mk:102: recipe for target 'Release/obj.target/protobuf_for_node/protobuf_for_node.o' failed
make: *** [Release/obj.target/protobuf_for_node/protobuf_for_node.o] Error 1
make: Leaving directory '*/node_modules/node-dota2/node_modules/protobuf/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.2.0-4-amd64
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd */node_modules/node-dota2/node_modules/protobuf
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! protobuf@0.11.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the protobuf@0.11.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the protobuf package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls protobuf
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by Crazy-Duck** [comment]
I urge you to checkout the 1.0.0-dev branch of the repository and to use that one in your project. We migrated away from compiled protos and are working with a full JS stack for the moment. Further-more, the 1.0.0-dev branch seems much more stable and maintained for the moment than the master branch, albeit somewhat lacking in up-to-date documentation and .

**Comment by Flumaster** [comment]
@Crazy-Duck , thanks bro.
