### ISSUE TITLE
After a few hours i get a disconnect error

### ISSUE THREAD

**Issue by macnibblet** [RJacksonm1/node-dota2#130]
I'm guessing i should handle the disconnect and reconnect, but just checking if someone has seen this before. 

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Disconnected
    at SteamClient._disconnected (/app/node_modules/steam/lib/steam_client.js:186:24)
    at emitOne (events.js:77:13)
    at Connection.emit (events.js:169:7)
    at TCP._onclose (net.js:469:12)
```

**Comment by howardchung** [comment]
Possibly related to https://github.com/RJacksonm1/node-dota2/issues/105

You probably just need to handle disconnections yourself.

**Comment by howardchung** [comment]
Although this seems to be failing at the node-steam level rather than the node-dota2 level, so you might be trying to do something while disconnected.

**Comment by jimmydorry** [comment]
Good memory. This looks exactly like #105 

Please comment on the original issue.
