### ISSUE TITLE
Getting TypeError on "createPracticeLobby"

### ISSUE THREAD

**Issue by alexdefine** [RJacksonm1/node-dota2#137]
I have completed all steps from "Setting up" section, after that uncommented lines of code to create lobby and after execution getting error:
TypeError: Cannot read property 'GameMode' of undefined.
Is there any way to fix it somehow? Tried on Windows 7 and Ubuntu.
Also, each time i use node test.js I have to reset Steam Guard, is it expected behavior?

**Comment by Crazy-Duck** [comment]
Hmm, I took a quick look at test.js and it seems it is no longer up to date, think we forgot to migrate it when doing the 1.0.0 update. Since 1.0.0 `createPracticeLobby` is defined as: 
```JavaScript
Dota2.Dota2Client.prototype.createPracticeLobby = function(password, options, callback) {...}
```
In other words, if you want to call it from the test.js file, your call should look somewhat like this:
```JavaScript
var options = {
    "game_name": "Name of your lobby",
    "server_region": 3,
    "game_mode": 2,
    "game_version": 1,
    "allow_cheats": false,
    "fill_with_bots": false,
    "allow_spectating": true,
    "pass_key": "yourPassword",
    "radiant_series_wins": 0,
    "dire_series_wins": 0,
    "allchat": true
}
Dota2.createPracticeLobby(options.pass_key, options, callback) {...}
```
You can find all function signatures in the handler folder in the project. Everything is split up by theme (lobbies, community, matches, ...).
As for the steam guard behaviour, I think this might indeed be intended behaviour by Steam (not something we can influence), I never tried it myself.

**Comment by howardchung** [comment]
Yeah, I think we forgot about test.js cause we never got around to implementing automated tests.  When/If @RJacksonm1 sets Travis up perhaps we can go through and clean up the tests.

**Comment by alexdefine** [comment]
@Crazy-Duck Thank you for your reponse! About steam guard, in previous version "test" folder contained index.js (now its test.js) and when I executed it I didn't have that problem, I mean I could just "node index.js" with the same steam guard code on and on. So I assume that it caused by changes in latest version.
@howardchung it would be great! :)

**Comment by howardchung** [comment]
I would advise disabling steam guard.  Steam guard logins are persisted through the "sentry" file I believe that saves a hash that can authenticate the user.  The code is one time use.

However this depends on the filesystem staying intact and does not work well with cloud hosting/automated testing.

**Comment by jimmydorry** [comment]
Did you make a blank sentry file? Did you clear the steam guard code from your config after successfully logging in for the first time?

When you have a working sentry, it will only change when you make account settings changes like password and email.

**Comment by alexdefine** [comment]
@jimmydorry
"Did you make a blank sentry file?"
Yes, I did everything exactly as written in "Setting up" section
"Did you clear the steam guard code from your config after successfully logging in for the first time?"
I couldn't log in for the first time. After first ran I got emailed with steam guard code. After that I was able to loggin successfuly. However eachtime I want to start a bot, I have to do like:
1) comment out steam guard line in config.js
2) run test.js
3) copy fresh steam guard code from email to config.js
4) run again

**Comment by jimmydorry** [comment]
The first cycle is working as intended, how ever, i believe you are meant to comment out the steam guard line after successfully logging in... before you login for the third time.

Previous node-steam versions (that are no longer compatible) probably ignored your steam guard line if you had a non empty sentry file.

Let me know if that works.

**Comment by alexdefine** [comment]
Hi, @jimmydorry. Sorry, for late response. Could you tell me what version if node-steam should I use?
Btw, I tried to do everything from the begining. So after first successfull log in with steam guard, I commented it in config.js and in logOn i passed only sentry data, account name and password and its not working :/ still have to pass fresh steam guard code for each log in.

**Comment by Crazy-Duck** [comment]
You should be using node-steam >=1.1.0 and node js >=4.0.0

**Comment by jimmydorry** [comment]
Severely out of date. Re-open if you are still having issues.
