### ISSUE TITLE
profileCardResponse handling issues

### ISSUE THREAD

**Issue by imayhaveborkedit** [RJacksonm1/node-dota2#138]
Since it seems that the profileCardResponse code was copy pasted from profileResponse, it technically handles it improperly.  It still works since it passes the result along with the `undefined` error value, but there is no result field, and the debug messages weren't even changed.   You can request any account_id up to 2<sup>32</sup>-1 but if it's not a valid profile the result will always be:
```JSON
{
  "account_id": (input),
  "background_def_index": null,
  "slots": [],
  "badge_points": null,
  "event_points": null,
  "event_id": null
}
```

**Comment by howardchung** [comment]
Can you submit a patch to fix?  Otherwise @Crazy-Duck might be able to, or I might take a look over the weekend

**Comment by imayhaveborkedit** [comment]
I can try but i'll have to figure out exactly how to determine what a "bad profile card response" is supposed to be first.

**Comment by howardchung** [comment]
Hmm, actually it's quite possible that this is the intended behavior.  We just decode the response with the appropriate protobuf definition.  I assume if the given account_id was invalid the protobuf will not crash, but the fields will not be populated with valid data.  The client application is probably supposed to detect and handle the error (ignoring the fields).

Are the debug messages you're referring to part of node-dota2?

**Comment by imayhaveborkedit** [comment]
Upon requesting a non-number account_id I was presented with this:
`Illegal value for Message.Field .CMsgClientToGCGetProfileCard.account_id: NaN (TypeError: Illegal value: NaN (not an integer))`

The debug messages are part of the onProfileCardResponse handlker in community.js

Unrelated, the tab spacing is inconsistent.  Are you using 2 or 4 spaces for tabs?

**Comment by howardchung** [comment]
I would just implement a NaN check at your application level rather than embed that into node-dota2.  I'm pretty sure that error is thrown at the protobufjs level and not at node-dota2, so I don't think it's very clean to implement error handling for that (to be consistent we would have to implement it for every single method that takes an id).

Yeah, looks like @Crazy-Duck didn't update the debug strings, but that's pretty easily fixed.

I have no idea about the spacing.  Probably different people are using different values and that's leading to inconsistency.

**Comment by imayhaveborkedit** [comment]
Here we go #139

**Comment by Crazy-Duck** [comment]
I pretty much wrote this method in 5 min just so we'd have a fix as soon as possible when Valve nuked the regular profileRequest. It doesn't surprise me I forgot something :)

**Comment by jimmydorry** [comment]
It is your code that was implemented as the fix, so If there are further issues feel free to re-open.
