### ISSUE TITLE
Dota/SourceTV is borked

### ISSUE THREAD

**Issue by imayhaveborkedit** [RJacksonm1/node-dota2#141]
`CMsgFindSourceTVGames` seems to be gone, and Valve changed the entire live games system.  The 'Featured' button under the Watch tab in dota is still disabled too, so Valve is likely to add something new or change it again entirely if someone on reddit complains the right way.  As it stands though the current system needs to be re-implemented.  `CMsgClientToGCFindTopSourceTVGames`, `CMsgGCToClientFindTopSourceTVGamesResponse`, and `CSourceTVGameSmall` seem to be the relevant protobuffs.

**Comment by imayhaveborkedit** [comment]
I am attempting to implement the new version of source tv games request but due to one or more of several reasons, possibly including my own incompetence and/or lack of experience with nodejs, I have run into an issue.  I got the request working, but the callback fails.  Rather, never happens because it's not passed to the handler for whatever reason.  I have no idea why this is happening since it's based on the old source tv game request functions that _did_ work.  

```javascript
Dota2.Dota2Client.prototype.newRequestSourceTVGames = function(filter_options, callback) {
    callback = callback || null;
    var _self = this;

    console.log(arguments);

    if (!this._gcReady) {
        if (this.debug) util.log("GC not ready, please listen for the 'ready' event.");
        return null;
    }

    if (this.debug) util.log("Sending new SourceTV games request");

    var payload = new Dota2.schema.CMsgClientToGCFindTopSourceTVGames(merge({
        "search_key": '',
        "league_id": 0,
        "hero_id": 0,
        "start_game": 0,
        "game_list_index": 0,
        "lobby_ids": 0,
    }, filter_options));

    this._protoBufHeader.msg = Dota2.schema.EDOTAGCMsg.k_EMsgClientToGCFindTopSourceTVGames;
    this._gc.send(this._protoBufHeader,
                  payload.toBuffer(),
                  function (header, body) {
                      onNewSourceTVGamesResponse.call(_self, body, callback);
                  }
    );
};

var onNewSourceTVGamesResponse = function onNewSourceTVGamesResponse(message, callback) {
    callback = callback || null;

    console.log(arguments);

    var sourceTVGamesResponse = Dota2.schema.CMsgGCToClientFindTopSourceTVGamesResponse.decode(message);

    if (typeof sourceTVGamesResponse.game_list !== "undefined" && sourceTVGamesResponse.game_list.length > 0) {
        if (this.debug) util.log("Received new SourceTV games data");
        this.emit("newSourceTVGamesData", sourceTVGamesResponse.num_games, sourceTVGamesResponse.game_list);
        if (callback) callback(null, sourceTVGamesResponse);
    }
    else {
        if (this.debug) util.log("Received a bad new SourceTV games response");
        if (callback) callback(sourceTVGamesResponse.result, sourceTVGamesResponse);
    }
};
handlers[Dota2.schema.EDOTAGCMsg.k_EMsgGCToClientFindTopSourceTVGamesResponse] = onNewSourceTVGamesResponse;
```
The callback for `onNewSourceTVGamesResponse` is never there.  It's not in the arguments list.  I assumed `onNewSourceTVGamesResponse.call(_self, body, callback);` would pass the callback, where it _does_ exist, but that function never seems to be called.  Maybe I just don't know what I'm doing but I'm still at a loss.

**Comment by Crazy-Duck** [comment]
Is it undefined? If so, not all functions work with callbacks if I recall correctly, so your implementation might be working as intended

**Comment by imayhaveborkedit** [comment]
Nope.  The only argument is `message`, as in `arguments = { '0': <buffer ...>}`.  If that's the case then this is another function that can't support callbacks, sadly.  This code was just me testing it anyways, I made no effort to make it "official" looking.  I guess if that's really the case I can replace the old sourcetv function with this one.  I just don't want to be the only one to try this and find out that it really does support callbacks.

Another thing.  The GC responds to this twice.  One reply with an empty `game_list` and `specific_games = true`, the second time with a populated list and `specific_games = false`.  I would imagine this has to do with the input arguments, but I haven't tested that yet.

**Comment by imayhaveborkedit** [comment]
Alright turns out `lobby_ids` isn't an int, and sending an int causes it to send a weird empty response before the real response.

**Comment by imayhaveborkedit** [comment]
I have continued testing things, and left some notes as comments.

```javascript
Dota2.Dota2Client.prototype.newRequestSourceTVGames = function(filter_options, callback) {
    callback = callback || null;
    filter_options = filter_options || null;
    var _self = this;

    if (!this._gcReady) {
        if (this.debug) util.log("GC not ready, please listen for the 'ready' event.");
        return null;
    }

    if (this.debug) util.log("Sending new SourceTV games request");

    var payload = new Dota2.schema.CMsgClientToGCFindTopSourceTVGames(merge({
        "search_key": '',     // I don't know what's supposed to go here, everything i've tried fails
        "league_id": 0,       // Presumably used for searching for live games in a tourney
        "hero_id": 0,         // Same as the old one, hero filter using id number
        "start_game": 0,      // THIS IS NOT THE GAME OFFSET, only values in [0, 10, 20, ... 90] are valid, and yield [1,2,3 ... 10] responses
        "game_list_index": 0, // I think this may be some sort of version number
        "lobby_ids": [],      // I'm not quite sure about this one either but it might have something to do with looking up live lobby games?
    }, filter_options));

    if (this.debug) util.log("Using data:\n", payload);

    this._protoBufHeader.msg = Dota2.schema.EDOTAGCMsg.k_EMsgClientToGCFindTopSourceTVGames;
    this._gc.send(this._protoBufHeader,
                  payload.toBuffer(),
                  function (header, body) {
                      // Callbacks may not work with this one :<
                      onNewSourceTVGamesResponse.call(_self, body, callback);
                  }
    );
};

var onNewSourceTVGamesResponse = function onNewSourceTVGamesResponse(message, callback) {
    callback = callback || null; // It won't work, will it :<

    var sourceTVGamesResponse = Dota2.schema.CMsgGCToClientFindTopSourceTVGamesResponse.decode(message);

    if (sourceTVGamesResponse.start_game !== null) {
        if (this.debug) util.log("Received new SourceTV games data");
        this.emit("newSourceTVGamesData", sourceTVGamesResponse);
        if (callback) callback(null, sourceTVGamesResponse);

    } else {
        /*

        A "bad" response will look like this.
        Any of these values should be ok to check for, except maybe game_list

        { search_key: null,
          league_id: null,
          hero_id: null,
          start_game: null,
          num_games: 0,
          game_list_index: null,
          game_list: [],
          specific_games: null }

        */

        if (this.debug) util.log("Received a bad new SourceTV games response");
        this.emit("newSourceTVGamesData", sourceTVGamesResponse);
        if (callback) callback(null, sourceTVGamesResponse); // There is no eresult, it's a response where everything is null/empty/0
    }
};
handlers[Dota2.schema.EDOTAGCMsg.k_EMsgGCToClientFindTopSourceTVGamesResponse] = onNewSourceTVGamesResponse;
```

When this code is all sorted out I plan to replace the old version with this one using the old names.  That might be a while though, for various reasons.  A few of the protobuff arguments are weird, and I don't actually know that much about node.js, so if someone who's more familiar could chime in, that would be nice.

**Comment by jimmydorry** [comment]
Good work figuring this out! 

Please make a PR into the dev branch when you are done.

Have you been using nethook? If not, using it may be useful in looking at what the steam client is doing, instead of relying on just the protobuf dumps.

**Comment by imayhaveborkedit** [comment]
I have not been using nethook.  I don't know that much about it, except maybe I have to compile it, which I should be able to do.  I think there was documentation on it in the steamre/nethook folder, so i'll look at that a bit.  There are also some other protobuff messages I wanted to implement to see what exactly they do.  In any case, it'll be kinda problematic if this new sourcetv function can't use callbacks, but if it just doesn't work there's nothing I can do about it.

**Comment by jimmydorry** [comment]
https://github.com/SteamRE/SteamKit/tree/master/Resources/NetHook2

There is a compiled one here, but it may be out of date. https://www.mediafire.com/folder/0bkbp0sb0d3lf/nethook2

If you can figure out how to compile, I would do that. It's pretty handy to see what is happening in the client, as well as what data is specifically getting sent and received.

**Comment by imayhaveborkedit** [comment]
After much effort and discovering that my the nethook I compiled doesn't work and the mediafire version does, I have collected some nethook dumps to look through.  I'll do some more experimenting but it looks like there are some `GCPlayerInfoRequest`s and `ClientPersonaState`s involved.  Another point of interest is that by default dota does a sourcetv games request with some lobby_ids.  I don't know where it gets those but i'm not really concerned about that at this point.

**Comment by jimmydorry** [comment]
`GCPlayerInfoRequest` is probably for the 3 profile slots on people you hover over.

`ClientPersonaState` is probably to show what match / custom game they are playing.

**Comment by imayhaveborkedit** [comment]
The three profile slots on hoverover popups is from the profile card.  `GCPlayerInfoRequest` returns a list of data like so:

```
account_id: numbers
name: "display name"
country_code: "" (cn for china, etc)
fantasy_role: 0
team_id: 0
team_name: ""
team_tag: "" (CDEC, DC, etc)
sponsor: ""
is_locked: False
```
The useful things being team data and display name.

As for `ClientPersonaState`, it looks more like something from the steam client and not dota.  There's a status flag int, along with a Friend struct, with steamid, persona state, ingame app number, server info, name, avatar hash, and facebook name/id.

**Comment by imayhaveborkedit** [comment]
On that topic `ClientRichPresenceInfo` is also still sent, but that might be a node-steam issue so i'll not pay much attention to that.

**Comment by imayhaveborkedit** [comment]
Alright i've implemented `GCPlayerInfoRequest` and, unfortunately, it seems this one doesn't support callbacks either.  I'm beginning to think this is a node-steam issue with new dota GC messages.

```javascript
Dota2.Dota2Client.prototype.requestPlayerInfo = function(account_ids, callback) {
    account_ids = account_ids || [0]; // If this is empty it seems nothing comes back, please advise
    callback = callback || null;

    var _self = this;

    if (!this._gcReady) {
        if (this.debug) util.log("GC not ready, please listen for the 'ready' event.");
        return null;
    }

    if (this.debug) util.log("Sending player info request.");

    var payload = new Dota2.schema.CMsgGCPlayerInfoRequest({
        account_ids: account_ids
    });

    this._protoBufHeader.msg = Dota2.schema.EDOTAGCMsg.k_EMsgGCPlayerInfoRequest;
    this._gc.send(
        this._protoBufHeader,
        payload.toBuffer(),
        function (header, body) {
            onPlayerInfoResponse.call(_self, body, callback);
        }
    );

};

var onPlayerInfoResponse = function onPlayerInfoResponse(message, callback) {
    callback = callback || null; // FUCK THIS ONE DOESNT WORK EITHER

    var playerInfoResponse = Dota2.schema.CMsgGCPlayerInfo.decode(message);

    // console.log(playerInfoResponse);
    // I'm not sure there's a bad response condition, so I don't know if we need a check

    if (this.debug) util.log("Received new player info data");
    this.emit("playerInfoData", playerInfoResponse);

    if (callback) callback(null, playerInfoResponse);

};
handlers[Dota2.schema.EDOTAGCMsg.k_EMsgGCPlayerInfo] = onPlayerInfoResponse;
```

If there's a better way to deal with something let me know as i'm not really a js programmer.

**Comment by imayhaveborkedit** [comment]
Moving on, `ClientRequestFriendData` returns X `ClientPersonaState` messages for every id requested.  I'm 99% sure this isn't a dota related message since it doesn't have a GCMessage section.  It's not that useful anyways, so I'll ignore it.

The callbacks not working for these is somewhat of an issue, particularly for `FindTopSourceTVGames` since it sends back multiple messages depending on `start_game`, which seems to work like so:
```
start_games: Can be 0, and any multiple of 10 up to 90.
start_games: 0 -> Results in receiving one message with the first set of games, as expected.
start_games: 10 -> Results in receiving two messages, as if it were page 1 and page 2.
start_games: 20...90 -> Same as before, every increment resulting in one more page being sent.
```

**Comment by Crazy-Duck** [comment]
I think you might be branching out into node-steam territory here. As far as i now personastate is something that is managed on steam level and not on game level. The SteamFriends object in node-steam has for example a function setPersonaState which should be called upon logon to set your status and another one to set your name. The same goes for the friend data. Dota itself does not contain a dota specific friend management, it reuses steam. The only thing that is managed on the side of dota are guilds and teams. I don't think its wise to start including stuff in node-dota which is already managed on the side of node-steam...
As for the handling of multiple messages, when we receive multiple messages from the GC, we'll receive multiple events from node-steam and up until now we've always handled these one by one. So when you send your request, you'll receive multiple events from node-dota because node-dota received multiple events from node-steam. I think this might be the reason why callbacks don't work in certain instances. In my experience all calls to the GC which might give rise to multiple response messages do not support callbacks

**Comment by imayhaveborkedit** [comment]
Yeah, I didn't notice those were steam related and not dota related until recently.  Those I intend to ignore.  The node-steam people can deal with it.  Callbacks are an issue though, but I don't know how do deal with them right now.  If they really can't be dealt with then I'm going to have a hard time using them.

**Comment by Crazy-Duck** [comment]
What issue are you exactly having which makes handling the events without callbacks impossible?

**Comment by imayhaveborkedit** [comment]
Its... uhhh... I'm talking to nodejs from python through zerorpc, and I have functions that I call in the nodejs file, get the data, reply with that.  I can do one non-callback event easy with a .once() listener, but for multiple i'm not sure.  I can probably figure out something but it won't be pretty, and what I currently have probably isn't pretty to begin with.  An example function:

``javascript
    getmatchdetails: function(matchid, reply) {
        reply = arguments[arguments.length - 1];
        matchid = typeof matchid !== 'function' ? matchid : undefined;

        if (matchid === undefined) {
            reply("No match id.");
        }

        if (!Dota2._gcReady) {
            reply("GC unready")
        }

        Dota2.requestMatchDetails(matchid, function(err, response){
            if (err){
                console.log(err);
                reply("You probably ran out of requests, see console.")
                return;
            }
            util.log("Got data for match " + matchid);
            reply(null, response);
        });
    }
````

**Comment by Crazy-Duck** [comment]
I'm not familiar with zerorpc, however, i guess you could always implement your own callback mechanism on top of node-dota. If you manage to find out how many events you need in return, you could listen until you've received them all and subsequently invoke your callback yourself..

**Comment by imayhaveborkedit** [comment]
Back on topic, I'm not sure if the following code is the best way to deal with this.  I'm not really sure about js conventions but I don't think this solution is quite correct.
```javascript
Dota2.Dota2Client.prototype.requestPlayerInfo = function(account_ids, callback) {
    // If this is empty it seems nothing comes back, please advise on how to handle that
    // and if asking for a list object argument is the correct call    
    account_ids = account_ids || [0]; 
```

**Comment by Crazy-Duck** [comment]
If a required argument is missing we usually just make a debug log and return null. It's what we do when we detect for example when the GC isn't ready when a function was invoked
```Javascript
  if (!this._gcReady) {
    if (this.debug) util.log("GC not ready, please listen for the 'ready' event.");
    return null;
  }
```

**Comment by jimmydorry** [comment]
DotA2 is weird though, from what I recall pre-reborn. There is crossover where personastate or richpresence or something is used for showing what DotA things your friends are doing... like what hero they are playing or custom game they are in. That part is managed from within DotA, even though it is a steam thing.

I could also imagine some usefulness of being able to at least figure out what your friends are doing within DotA, if you were matching some of the functionality that is available in the client.

I agree with @Crazy-Duck though, in that some parts of it might just not be possible or desirable to bring into the library.

**Comment by imayhaveborkedit** [comment]
I've decided the best course of action is to stick with the basic implementation for now and see if I can collect all the responses together on my end.  Once I have everything cleaned up and documented I'll make a PR.

Also, is this supposed to be a number of some sort in a format only valve would use? ` 'lobby_id': {'high': 5653128, 'low': -526368991, 'unsigned': True}`

**Comment by howardchung** [comment]
Its likely the high and low 32 bits of a 64 bit unsigned int.  If you want
the true number you'll have to compute it from that data.

**Comment by imayhaveborkedit** [comment]
I've sort of got it in python but I'm not sure how to do this in nodejs.  I know we can probably use bignumber for something but I'm not sure about the conversions.
```python
>>> ctypes.c_uint64((ctypes.c_int32(5653128).value << 32) | ctypes.c_uint32(-526368991).value).value
<<< 24280003648700193L
```

**Comment by Crazy-Duck** [comment]
No need to use complicated calculations actually. This is an object type wich can be stringified. So you can basically do `""+lobby_id` to get the value. If you go through the code you'll see we use this in several places to compare unsigned int's.

**Comment by imayhaveborkedit** [comment]
Well... then... :goberserk: 

So if I were to convert those to normal numbers using something like...
```javascript
for (var i = gamedata.game_list.length - 1; i >= 0; i--) {
    gamedata.game_list[i].lobby_id = ""+gamedata.game_list[i].lobby_id
    gamedata.game_list[i].server_steam_id = ""+gamedata.game_list[i].server_steam_id
};
```
That would probably go in my own code instead of `onSourceTVGamesResponse`, right?

**Comment by imayhaveborkedit** [comment]
I have successfully fixed my own code involving this but I have found another problem.  The new live games list includes special games for players and ticketed games.  Player specific games, in this case for Ar1se-^, ExplicitAF, and 1437, don't seem to show up as normal games.  According to my nethook dumps, the live games request includes some lobby ids, but I don't know where dota gets those from.

![example image](http://i.imgur.com/87YQJPO.png)

**Comment by Crazy-Duck** [comment]
Can you check which requests are sent before the client asks these games? These games are supposed to be pro-player games, so there might be a request sent first to determine which pro's are playing and the lobbies they're in

**Comment by imayhaveborkedit** [comment]
Not as far as I can tell.  Maybe someone else can find something I missed.

**Comment by imayhaveborkedit** [comment]
I have encountered yet another issue.  Turns out that `requestPlayerInfo` responses for private profiles have null fields for everything, including the name field.  Instead, Dota liberally uses `ClientRequestFriendData`/`ClientPersonaState` to get names (maybe more) for players.  Again, these aren't strictly Dota related, but now I don't know if there's a way to get names for players with private profiles using only dota/node-dota2 related messages.

**Comment by Crazy-Duck** [comment]
In that case it might be useful to include an extra return argument with a boolean indicating if the user's profile is private or not, again for better usability. As for the use of steam functions, there is nothing inherently wrong with that. There is nothing which prohibits you from using node-steam functions in combination with node-dota2 functions in your personal code. Look at node-dota2 as an expansion for node-steam, which offers an extra abstraction layer for GC communication pertaining specifically to Dota2. This does not invalidate any other functionality implemented by node-steam.

**Comment by imayhaveborkedit** [comment]
Playerinfo responses can have more than one user's info so unless you alter the data that's not really feasible.

**Comment by Crazy-Duck** [comment]
Ok, I hadn't looked that far into it. In that case users will have to detect it based on the null values I guess.

**Comment by jimmydorry** [comment]
Make a new issue for each individual topic please. The issue is no longer helpful, being left open.
