### ISSUE TITLE
How do you guys save the computer?

### ISSUE THREAD

**Issue by gerlaic** [RJacksonm1/node-dota2#155]
I'm having trouble in letting the program remember my computer... Every time I run the program, it throw error 65 and I have to delete the Auth Code and request it again :/ Anyways to save that? I know in browser it uses cookie to do so. How does node-dota2 do?

**Comment by RJacksonm1** [comment]
This is a [node-steam](https://github.com/seishun/node-steam) question more than a node-dota2 specific problem, but the quick answer is if you have Steam Guard enabled then you either have to provide an `auth_code` or a `sha_sentryfile` parameter when logging in.

The first time you logon via an auth code, Steam will throw you a `sentry` via node-steam's `updateMachineAuth` event.  You have to save this somewhere, and then when you later logon you provide this sentry through `sha_sentryfile`.

Here's a relevant code from the node-dota2 test script, though I'm not sure if this is functional and working with the current version of node-steam, so you might have to do a little more digging to get it working:

```javascript

// Save sentry file from Steam
steamUser.on('updateMachineAuth', function(sentry, callback) {
    fs.writeFileSync('sentry', sentry.bytes)
    util.log("sentryfile saved");
    callback({ sha_file: crypto.createHash('sha1').update(sentry.bytes).digest() });
});

// Construct logon details object, passing auth code if we have one set, or a sentry file if we have one on the filesystem.
var logOnDetails = {
    "account_name": global.config.steam_user,
    "password": global.config.steam_pass,
};
if (global.config.steam_guard_code) logOnDetails.auth_code = global.config.steam_guard_code;

try {
    var sentry = fs.readFileSync('sentry');
    if (sentry.length) logOnDetails.sha_sentryfile = sentry;
}
catch (beef){
    util.log("Cannae load the sentry. " + beef);
}

// Connect to Steam and logon
steamClient.connect();
steamClient.on('connected', function() {
  steamUser.logOn(logOnDetails);
});
```

**Comment by jimmydorry** [comment]
Did you save the computer @gerlaic ? If not, re-open or make a more specific question.

**Comment by gerlaic** [comment]
Well I was reading through all the issues and then I saw this. Actually @jimmydorry I didn't save it but basically I disabled the steam guard and I think this is the easiest way to solve the problem

**Comment by jimmydorry** [comment]
No way. I made something recently, and it worked fine even with SteamGuard enabled. You should try pulling the latest github version into where you have this library installed.
