### ISSUE TITLE
There is no series type enum

### ISSUE THREAD

**Issue by Crazy-Duck** [RJacksonm1/node-dota2#160]
The README states that to configure the series type when creating/modifying a lobby, you need to use the series type enum. There is no such enum neither in the project nor in the proto files. The current version of the protobufs just states that it's a 32 bit integer. Has anyone already nethooked the different  values for best-of-1/2/3/5 ?

**Comment by jimmydorry** [comment]
Nope. Let me know if you want the compiled nethook from a few months ago.
