### ISSUE TITLE
sendMessage denied?

### ISSUE THREAD

**Issue by andresrivero** [RJacksonm1/node-dota2#163]
Edit: see next post about this being an account level issue. Solved itself.

I used node-dota2 about 7 months ago successfully and had a fairly complex bot going on, took a break with the reborn upgrade and wanted to get back into it. My original code wouldn't work so I upgraded Node.js and installed the newest node-steam and node-dota2. I am able to log on, launch dota2, receive servers, get sentry/sha, get ready state. From there I am able to send most messages like joining chat channels and getting user profiles, tournaments, and so on. After joining a channel I can see the chat within that channel in the console, so I'm sure that part is working.

The problem I am having is after joining a chat channel, I am unable to send a message to the channel. I see in the node console:
Sending message to channelname
followed by:
UNHANDLED MESSAGE #7102

I see that the protobuf lists that as a gcpopup message. I'm totally stuck and hate to be that guy but I've exhausted almost every troubleshooting step I know.

I've reinstalled all versions of node.js and installed steam globally and locally, used the git version and the plain npm install version. Right now I'm on 4.2.2 with OSX and Windows. I tried different methods of installing node-steam but that didn't help much. I even made a VM of Windows to do a completely fresh install of node.js and still get the same error. 

I was thinking it might have to do with the account being muted or maybe banned somehow, but I made a new account, logged in and still the same error message.

Any ideas?

Edit: Sorry here is the js, which is the same one as test.js but pared down to just the joinchannel and sendmessage portion:

        var steam = require("steam"),
        util = require("util"),
        fs = require("fs"),
        crypto = require("crypto"),
        dota2 = require("../"),
        steamClient = new steam.SteamClient(),
        steamUser = new steam.SteamUser(steamClient),
        steamFriends = new steam.SteamFriends(steamClient),
        Dota2 = new dota2.Dota2Client(steamClient, true);
    
    global.config = require("./config");
    
    var onSteamLogOn = function onSteamLogOn(logonResp) {
        if (logonResp.eresult == steam.EResult.OK) {
            steamFriends.setPersonaState(steam.EPersonaState.Busy);
            steamFriends.setPersonaName("dota2bot");
            util.log("Logged on.");
    
            Dota2.launch();
            Dota2.on("ready", function() {
                util.log("Node-dota2 ready.");
    
                // CHAT
    
                var chatChannel = "chatchannel";
                var joiningChannel = 1;
                var leavingChannel = 0;
    
                if(joiningChannel == 1){
                    Dota2.joinChat(chatChannel);
                    setTimeout(function(){
                        Dota2.sendMessage(chatChannel, "Hello, guys! I'm Dota 2 Bot.");
                    }, 1000);
                }
    
                if(leavingChannel == 1){
                    setTimeout(function(){
                        Dota2.leaveChat(chatChannel);
                    }, 10000);
                }
    
            });
    
            Dota2.on("unready", function onUnready() {
                util.log("Node-dota2 unready.");
            });
    
            Dota2.on("chatMessage", function(channel, personaName, message) {
                util.log("[" + channel + "] " + personaName + ": " + message);
            });
    
            Dota2.on("unhandled", function(kMsg) {
                util.log("UNHANDLED MESSAGE #" + kMsg);
            });
        }
    },
    onSteamServers = function onSteamServers(servers) {
        util.log("Received servers.");
        fs.writeFile('servers', JSON.stringify(servers));
    },
    onSteamLogOff = function onSteamLogOff(eresult) {
        util.log("Logged off from Steam.");
    },
    onSteamError = function onSteamError(error) {
        util.log("Connection closed by server.");
    };
    
    steamUser.on('updateMachineAuth', function(sentry, callback) {
        fs.writeFileSync('sentry', sentry.bytes)
        util.log("sentryfile saved");
    
        callback({ sha_file: crypto.createHash('sha1').update(sentry.bytes).digest() });
    });
    
    var logOnDetails = {
        "account_name": global.config.steam_user,
        "password": global.config.steam_pass,
    };
    if (global.config.steam_guard_code) logOnDetails.auth_code = global.config.steam_guard_code;
    
    try {
        var sentry = fs.readFileSync('sentry');
        if (sentry.length) logOnDetails.sha_sentryfile = sentry;
    }
    catch (beef){
        util.log("Cannot load the sentry. " + beef);
    }
    
    steamClient.connect();
    
    steamClient.on('connected', function() {
        steamUser.logOn(logOnDetails);
    });
    
    steamClient.on('logOnResponse', onSteamLogOn);
    steamClient.on('loggedOff', onSteamLogOff);
    steamClient.on('error', onSteamError);
    steamClient.on('servers', onSteamServers);

**Comment by andresrivero** [comment]
I will update this as soon as I verify it but I am pretty sure it has to do with your dota2/steam account level. I checked the console from the Dota2 in game client and saw a message about chat being denied due to steam account level. Once I figure it out, I'll modify this issue.

**Comment by jimmydorry** [comment]
Before reading any further, you may want to give the dev branch a spin. I recall some of the chat stuff being improved.

https://github.com/RJacksonm1/node-dota2/tree/dev

**Comment by jimmydorry** [comment]
Are you trying this on a non-limited account (i.e. one you know is absolutely able to post to channels)?

**Comment by andresrivero** [comment]
It works now after removing the limit from the account. I think my biggest hurdle was that the account was used for node-dota2 bot a couple months ago so I assumed it was grandfathered in after the switch to reborn. To check you just have to open the dota2 game client, join a user chat channel, and send a message while observing the console. It will alert you there if the account is limited. 

I have Steam Guard via the app on my main account, so turning that off to test a non-limited account was  my last resort - since it stalls any trading after switching it off and I am in the middle of some exchanges.

**Comment by Crazy-Duck** [comment]
There have been quite some changes in the GC/Steam's behaviour over the past few months. I'm glad you got things working again. If there'ss no further problems this issue can be closed

**Comment by jimmydorry** [comment]
Yep. Although we may want to mention this in the readme. @Crazy-Duck pls :+1:

**Comment by jimmydorry** [comment]
Tagged and bagged.

https://github.com/RJacksonm1/node-dota2/pull/164
