### ISSUE TITLE
matchmakingStatsData update

### ISSUE THREAD

**Issue by imayhaveborkedit** [RJacksonm1/node-dota2#165]
I noticed that the `matchmakingStatsResponse` data has changed slightly, where `searching_players_by_group` should now be `searching_players_by_group_source2`, and the wait times are still gone.  I'm now looking at the matchmaking regions list plan to update that too.  I'll make a PR when its done, and I'm assuming removing wait time data is ok since it's been gone for ages.  It seems no one figured out `disabledGroups` does, but I think it's probably something to do with the `0` data regions in the `searching_players...` field.  In this protobuff dump, `disabled_groups_source2` is 65552, which would be 65536 + 16,  and fields 4 and 16 are the 0s.  I'm just going to assume that's what that means.

**Comment by Crazy-Duck** [comment]
Might be a 16bit bitmask

**Comment by imayhaveborkedit** [comment]
I originally made this issue because I was I thought something was incorrect but I was just imagining it.  I guess any relevant discussion can go in the pull request.
