### ISSUE TITLE
Common result IDs get resolved as an error message

### ISSUE THREAD

**Issue by jimmydorry** [RJacksonm1/node-dota2#174]
There are a heap of common eresults. We can make a helper function to inject the corresponding message into results when the enum is known, to enable easier debugging.

I'll try to remember to make a list of them on the weekend. Some of the steam irc bots already have a list we can steal.

**Comment by Crazy-Duck** [comment]
I've been wondering about these actually. Thing is, Valve isn't terribly consistent in naming schemes, there's like no consistency as to when they send an `eresult` or a `result`. Furthermore, to add insult to injury, both have a different value for success and failure states, with values going in the negatives as well as in the positives (I've seen values up to 11 while implementing CMsgSetLobbyTeamSlot). It's weird we need to define our own enums for it, one would've assumed Valve'd put them in the protobufs like some of the other enums...

**Comment by jimmydorry** [comment]
Haha, negative eresults are a stupid, but I guess it is Valve after all.

As to them not being in protobufs, it's not terrible surprising. They are generally universal and hard-coded. I suppose they even cover modes where communication and everything else has failed completely, which I don't think protobufs would help with.

I guess the helper will do something like try to match the result to an enum and return message or do nothing.

**Comment by Crazy-Duck** [comment]
Just defining the enum is sufficient I think. That way the user can parse the errors themselves, for example:
```JavaScript
callback = function (err, data) {
    if (err === Dota2.EResult.SUCCESS) {
        // do something
    }
}
```

**Comment by jimmydorry** [comment]
That's a very good idea! If you think the range is greater than 55, there are way more that I can go find.

enum EResult
{
	k_EResultOK	= 1,							// success
	k_EResultFail = 2,							// generic failure 
	k_EResultNoConnection = 3,					// no/failed network connection
	//	k_EResultNoConnectionRetry = 4,				// OBSOLETE - removed
	k_EResultInvalidPassword = 5,				// password/ticket is invalid
	k_EResultLoggedInElsewhere = 6,				// same user logged in elsewhere
	k_EResultInvalidProtocolVer = 7,			// protocol version is incorrect
	k_EResultInvalidParam = 8,					// a parameter is incorrect
	k_EResultFileNotFound = 9,					// file was not found
	k_EResultBusy = 10,							// called method busy - action not taken
	k_EResultInvalidState = 11,					// called object was in an invalid state
	k_EResultInvalidName = 12,					// name is invalid
	k_EResultInvalidEmail = 13,					// email is invalid
	k_EResultDuplicateName = 14,				// name is not unique
	k_EResultAccessDenied = 15,					// access is denied
	k_EResultTimeout = 16,						// operation timed out
	k_EResultBanned = 17,						// VAC2 banned
	k_EResultAccountNotFound = 18,				// account not found
	k_EResultInvalidSteamID = 19,				// steamID is invalid
	k_EResultServiceUnavailable = 20,			// The requested service is currently unavailable
	k_EResultNotLoggedOn = 21,					// The user is not logged on
	k_EResultPending = 22,						// Request is pending (may be in process, or waiting on third party)
	k_EResultEncryptionFailure = 23,			// Encryption or Decryption failed
	k_EResultInsufficientPrivilege = 24,		// Insufficient privilege
	k_EResultLimitExceeded = 25,				// Too much of a good thing
	k_EResultRevoked = 26,						// Access has been revoked (used for revoked guest passes)
	k_EResultExpired = 27,						// License/Guest pass the user is trying to access is expired
	k_EResultAlreadyRedeemed = 28,				// Guest pass has already been redeemed by account, cannot be acked again
	k_EResultDuplicateRequest = 29,				// The request is a duplicate and the action has already occurred in the past, ignored this time
	k_EResultAlreadyOwned = 30,					// All the games in this guest pass redemption request are already owned by the user
	k_EResultIPNotFound = 31,					// IP address not found
	k_EResultPersistFailed = 32,				// failed to write change to the data store
	k_EResultLockingFailed = 33,				// failed to acquire access lock for this operation
	k_EResultLogonSessionReplaced = 34,
	k_EResultConnectFailed = 35,
	k_EResultHandshakeFailed = 36,
	k_EResultIOFailure = 37,
	k_EResultRemoteDisconnect = 38,
	k_EResultShoppingCartNotFound = 39,			// failed to find the shopping cart requested
	k_EResultBlocked = 40,						// a user didn't allow it
	k_EResultIgnored = 41,						// target is ignoring sender
	k_EResultNoMatch = 42,						// nothing matching the request found
	k_EResultAccountDisabled = 43,
	k_EResultServiceReadOnly = 44,				// this service is not accepting content changes right now
	k_EResultAccountNotFeatured = 45,			// account doesn't have value, so this feature isn't available
	k_EResultAdministratorOK = 46,				// allowed to take this action, but only because requester is admin
	k_EResultContentVersion = 47,				// A Version mismatch in content transmitted within the Steam protocol.
	k_EResultTryAnotherCM = 48,					// The current CM can't service the user making a request, user should try another.
	k_EResultPasswordRequiredToKickSession = 49,		// You are already logged in elsewhere, this cached credential login has failed.
	k_EResultAlreadyLoggedInElsewhere = 50,		// You are already logged in elsewhere, you must wait
	k_EResultSuspended = 51,
	k_EResultCancelled = 52,
	k_EResultDataCorruption = 53,
	k_EResultDiskFull = 54,
	k_EResultRemoteCallFailed = 55,

};

**Comment by Crazy-Duck** [comment]
I'll add this to my pull with the refactoring

**Comment by jimmydorry** [comment]
I wonder how long until we see the first 17s. :+1:

**Comment by Crazy-Duck** [comment]
I've been thinking about that actually when running nethook the last time. Normally Valve is pretty strict about stuff hooking into their libraries, you know what their position is on nethook?

**Comment by jimmydorry** [comment]
They are strict on hooks on the game when you are playing. You never want
to be doing nethook on your main account, although it's generally fine if
you are just doing it in the menu and such. As to the usage of nethook in
general, they have been fine with it in the past. There are two or three
valfs that hang out in the irc channel nethook comes from.

**Comment by Crazy-Duck** [comment]
hmm, alright, good thing I've been mainly using it on my bot accounts then :laughing:

**Comment by jimmydorry** [comment]
Should have closed this a while ago. :+1:
