### ISSUE TITLE
How to get info about created lobby

### ISSUE THREAD

**Issue by oleghalin** [RJacksonm1/node-dota2#175]
Hello, i want to know how to get info about created lobby, for example id, i though that this script must echo lobby info Dota2.createPracticeLobby(lobbyPassword, lobbyName, function(err, data){
                   util.log(JSON.stringify(data));
                }); but it isnt.

**Comment by oleghalin** [comment]
Its given just result

**Comment by Crazy-Duck** [comment]
Which is normal. If you look in the readme, you'll see that the createpracticelobby callback data only contains a practicelobbyresponse, which is, as you've seen, just a result. If you want info about the lobby, listen for practicelobbyupdate events.

**Comment by oleghalin** [comment]
If im not mistake, i must write new handler? ye?

**Comment by Crazy-Duck** [comment]
The handler already exists, it's sufficient to register an eventlistener. Check out [this](https://github.com/RJacksonm1/node-dota2#practicelobbyupdate-lobby) link for the documentation on the proper event. This one is fired each time something changes in your lobby. In your case I'm guessing you'll need to do something like 
```JavaScript
Dota2.on('practiceLobbyUpdate', function(err, data) {
    // do something
});
```

**Comment by oleghalin** [comment]
Dota2.createPracticeLobby(options.pass_key, options, function(err, data){});
				Dota2.on('practiceLobbyUpdate', function(err, data) {
					util.log(JSON.stringify(data));	});
				something like that?

**Comment by Crazy-Duck** [comment]
yeah pretty much. As soon as something changes in your lobby you should get an update

**Comment by oleghalin** [comment]
![image](https://cloud.githubusercontent.com/assets/9086983/11667795/830c5954-9dfc-11e5-8594-f5f0884066ad.png)
![image](https://cloud.githubusercontent.com/assets/9086983/11667797/8810bb5c-9dfc-11e5-9c55-a6b299d4739a.png)
So, maybe i did something wrong?

**Comment by Crazy-Duck** [comment]
yes, my mistake actually, I messed up the example. If you look at the readme explanation for the event, it states: practiceLobbyUpdate (lobby). This means the event has 1 argument, i.e. the lobby object. This ought to be fine:
```JavaScript
Dota2.on('practiceLobbyUpdate', function(lobby) {
    util.log(JSON.stringify(lobby);
});
```

**Comment by oleghalin** [comment]
Oh, ty very match but, maybe someone need it too
Dota2.on('practiceLobbyUpdate', function(lobby) {
    util.log(JSON.stringify(lobby));
});

**Comment by oleghalin** [comment]
![image](https://cloud.githubusercontent.com/assets/9086983/11668250/d950b2d6-9dfe-11e5-921b-1d1e5834c047.png)
Where is id of lobby?

**Comment by Crazy-Duck** [comment]
var id = lobby.lobby_id + ""
