### ISSUE TITLE
Adding bot to slot

### ISSUE THREAD

**Issue by oleghalin** [RJacksonm1/node-dota2#176]
![image](https://cloud.githubusercontent.com/assets/9086983/11668488/23312f56-9e00-11e5-9cff-f4c8c0b30713.png)
In previous issue i asked it, but function AddBot isnt exist. 

p.s. i readed readme, all info that i can translate i learned

**Comment by Crazy-Duck** [comment]
It's not yet on the main branch. If you want to use that function, you should check out the dev branch. You can find the implementation [here](https://github.com/RJacksonm1/node-dota2/blob/dev/handlers/lobbies.js#L348)

**Comment by oleghalin** [comment]
Its to use example.  ye?

**Comment by oleghalin** [comment]
I need to set bot to spectetares

**Comment by oleghalin** [comment]
Previous command SetSlot was easy, but there just bots

**Comment by Crazy-Duck** [comment]
Use `joinPracticeLobbyTeam` then. `addBotToPracticeLobby` adds an AI bot to one of the teams. `joinPracticeLobbyTeam` allows you to set the team of your bot.

**Comment by oleghalin** [comment]
![image](https://cloud.githubusercontent.com/assets/9086983/11670457/94a84cdc-9e0a-11e5-97fd-dfc26f349467.png)
Must be like that? (i Used enum from .proto)

**Comment by Crazy-Duck** [comment]
Something like that should work yeah. Be careful though, I'm not sure if the value for the spectator team is actually used by Valve. In my experience you should put the bot in the player pool if you want to have it spectate -> DOTA_GC_TEAM.DOTA_GC_TEAM_PLAYER_POOL

**Comment by oleghalin** [comment]
```
Dota2.joinPracticeLobbyTeam(1, 4, function(err, data){
                    });
```
