### ISSUE TITLE
How to leave lobby after launching it?

### ISSUE THREAD

**Issue by oleghalin** [RJacksonm1/node-dota2#179]
How to leave from game after launching lobby? launchPracticeLobby

**Comment by imayhaveborkedit** [comment]
`leavePracticeLobby()`?

**Comment by oleghalin** [comment]
nope. Its isnt work. I need to disconnect from server, not leave from lobby

**Comment by imayhaveborkedit** [comment]
node-dota2 does not connect to a game like you would in the normal client.  I don't know exactly what issue you're having but it's not that.

**Comment by oleghalin** [comment]
srsly not connect? bro, just check bot. After launching bot connection to the server

**Comment by jimmydorry** [comment]
Run nethook on the real client to figure out what messages are being sent. I last linked a pre-compiled version and a wiki about it here: https://github.com/RJacksonm1/node-dota2/issues/141#issuecomment-153559554

I'm pretty sure though, you just need to leave the lobby.

**Comment by oleghalin** [comment]
![image](https://cloud.githubusercontent.com/assets/9086983/11742364/04cb6072-a008-11e5-86ee-fd77d3b07e46.png)
After finish of game, i disconnect from the server, check status of bot, bot is in lobby, after try invite myself to lobby, it isnt work

**Comment by oleghalin** [comment]
![image](https://cloud.githubusercontent.com/assets/9086983/11742407/5a088c4a-a008-11e5-8143-5e1d1f9b7fb6.png)
And when i tried to create lobby again i have this one message

**Comment by jimmydorry** [comment]
11 is invalid state

**Comment by oleghalin** [comment]
![image](https://cloud.githubusercontent.com/assets/9086983/11742446/a1366dd0-a008-11e5-9a20-59ddbd7bb7c6.png)
When i try to leave lobby, i have this question

**Comment by jimmydorry** [comment]
2 is fail

**Comment by oleghalin** [comment]
I understand that is it fail, but why? And what u mean of "11 is invalid stat"

**Comment by jimmydorry** [comment]
There is a big list of errors. https://github.com/RJacksonm1/node-dota2/issues/174#issuecomment-162831628

**Comment by oleghalin** [comment]
![image](https://cloud.githubusercontent.com/assets/9086983/11742550/8379a7ca-a009-11e5-8b38-071bbfbfe8f9.png)
What does it mean?

**Comment by jimmydorry** [comment]
https://github.com/RJacksonm1/node-dota2/blob/afdc621f2aace87269655cbaa3a29b421805db24/proto/dota_gcmessages_common.proto#L74

**Comment by oleghalin** [comment]
I think that after finishing game arg lobby dont seting to  null, can it be?

**Comment by oleghalin** [comment]
![image](https://cloud.githubusercontent.com/assets/9086983/11742717/bf55fb80-a00a-11e5-946e-30da5b058da6.png)
In dota with account of bot this seems like that. (text on the button 'back to lobby')
after clicking
![image](https://cloud.githubusercontent.com/assets/9086983/11742726/d804189c-a00a-11e5-9644-d3f1c602e4de.png)

**Comment by jimmydorry** [comment]
Nethook and figure out what it wants.

**Comment by oleghalin** [comment]
Via nethook?

**Comment by jimmydorry** [comment]
I've linked it a million times. Re-read this thread.

**Comment by oleghalin** [comment]
Its just ask.

**Comment by jimmydorry** [comment]
It's up ^^^

**Comment by oleghalin** [comment]
![image](https://cloud.githubusercontent.com/assets/9086983/11742907/0d3dd2cc-a00c-11e5-9f04-cab759323c60.png)

**Comment by jimmydorry** [comment]
The instructions say

NetHook2 will now begin dumping every message to file. You can locate the dumps in your Steam install, under the nethook directory. The directories are numbered with the unix time that dumping began.

**Comment by jimmydorry** [comment]
It goes without saying that you need to perform the actions the bot will, so you can see what messages are being sent.

**Comment by idreamshen** [comment]
launchPracticeLobby, then abandonGame

**Comment by oleghalin** [comment]
abandonGame? node-dota havent this function

**Comment by oleghalin** [comment]
http://pastebin.com/RuJLYw6D in this file i get this, but what i must see there?

**Comment by jimmydorry** [comment]
https://github.com/RJacksonm1/node-dota2/blob/master/proto/dota_gcmessages_client.proto#L203

It's there, just no handler for it, most likely.

**Comment by oleghalin** [comment]
Hm. Ill write this handler, and this function need to disconnect or not to connect?

**Comment by oleghalin** [comment]
http://pastebin.com/Bhe3ZfTj can u check my hanlder?

**Comment by idreamshen** [comment]
first abandonCurrentGame(),then leavePracticeLobby().

https://github.com/idreamshen/node-dota2/blob/master/handlers/lobbies.js#L183 
I wrote it for the source engine 1

**Comment by oleghalin** [comment]
Thank you, i think this working
function:
```
Dota2.abandonCurrentGame();
```
hanlder:
```
Dota2.Dota2Client.prototype.abandonCurrentGame = function(callback) {
    callback = callback || null;
    var _self = this;

    if (!this._gcReady) {
        if (this.debug) util.log("GC not ready, please listen for the 'ready' event.");
        return null;
    }

    if (this.debug) util.log("Sending match CMsgAbandonCurrentGame request");
    var payload = new Dota2.schema.CMsgAbandonCurrentGame({});
    this._protoBufHeader.msg = Dota2.schema.EDOTAGCMsg.k_EMsgGCAbandonCurrentGame;
    this._gc.send(
        this._protoBufHeader,
        payload.toBuffer(),
        function(header, body) {
            onPracticeLobbyResponse.call(_self, body, callback);
        }
    );
};
```

**Comment by jimmydorry** [comment]
Feel free to make a pull request.

**Comment by oleghalin** [comment]
Oh no, sry. It isnt work. 
![image](https://cloud.githubusercontent.com/assets/9086983/11743456/43e114d4-a010-11e5-9fc0-4f3470869257.png)

**Comment by Apmats** [comment]
The handler works for me and judging from the conversation here and from issue #56 it could be useful for others as well. Why no PR for this?

**Comment by jimmydorry** [comment]
Make a PR.

**Comment by csplkiller** [comment]
How to leave lobby after launching it?
I need to have the bot launch the lobby, then leave the game, and immediately create a new lobby. How to implement this?

If I do first abandonCurrentGame(),then leavePracticeLobby()., then I get a red screen in the match, and trying to create a new lobby - I get into the old lobby

**Comment by oleghalin** [comment]
Im using function like this
`function leaveLobby()
{
	Dota2.abandonCurrentGame();
	Dota2.leavePracticeLobby();
	Dota2.leaveChat('Lobby_'+id);
}`

**Comment by csplkiller** [comment]
oleghalin Can I contact you?
We swill both speak Russian.

**Comment by csplkiller** [comment]
If I use your function
The situation does not change, so in the queue error
And after the creation of the next lobby - it turns out that the bot
Gets into the old lobby (game) ...

![2017-04-15_12-33-13](https://cloud.githubusercontent.com/assets/7470513/25062614/019708ae-21d8-11e7-8b94-5548be0a67e7.png)

**Comment by oleghalin** [comment]
Yes. Vk.com/pawno_ua
