### ISSUE TITLE
practiceLobbyKick

### ISSUE THREAD

**Issue by oleghalin** [RJacksonm1/node-dota2#183]
My code 
```
Dota2.practiceLobbyKick(123456789);
```
123456789 - my steamid. Im in lobby. 
![image](https://cloud.githubusercontent.com/assets/9086983/11768566/d0fc5cfa-a1d9-11e5-966d-8ad8fc4632c6.png)
Result of kick
![image](https://cloud.githubusercontent.com/assets/9086983/11768567/d7290c04-a1d9-11e5-8045-f72ce1d34ab7.png)
Whats can be wrong?

**Comment by oleghalin** [comment]
Maybe problem in handler?

**Comment by oleghalin** [comment]
hello, guys. 
pls check this hanlder. 
```
Dota2.Dota2Client.prototype.practiceLobbyKick = function(account_id, callback) {
    callback = callback || null;
    var _self = this;
    if (!this._gcReady) {
        if (this.debug) util.log("GC not ready, please listen for the 'ready' event.");
        return null;
    }

    account_id = account_id || "";

    if (this.debug) util.log("Sending match CMsgPracticeLobbyKick request");
    var payload = new Dota2.schema.CMsgPracticeLobbyKick({
        "account_id": account_id
    });
    this._protoBufHeader.msg = Dota2.schema.EDOTAGCMsg.k_EMsgGCPracticeLobbyKickFromTeam;
    this._gc.send(
        this._protoBufHeader,
        payload.toBuffer(),
        function(header, body) {
            onPracticeLobbyResponse.call(_self, body, callback);
        }
    );
};
```

**Comment by oleghalin** [comment]
And pls set bug label. I neednt help with function. I need help with fix handler.

**Comment by Crazy-Duck** [comment]
You're using the wrong k_EMsg, you should be using `k_EMsgGCPracticeLobbyKick` for `CMsgPracticeLobbyKick` and `k_EMsgGCPracticeLobbyKickFromTeam` for `CMsgPracticeLobbyKickFromTeam` I think

**Comment by oleghalin** [comment]
Like that?
```
/ callback to onPracticeLobbyResponse
Dota2.Dota2Client.prototype.practiceLobbyKick = function(account_id, callback) {
    callback = callback || null;
    var _self = this;
    if (!this._gcReady) {
        if (this.debug) util.log("GC not ready, please listen for the 'ready' event.");
        return null;
    }

    account_id = account_id || "";

    if (this.debug) util.log("Sending match CMsgPracticeLobbyKick request");
    var payload = new Dota2.schema.k_EMsgGCPracticeLobbyKickFromTeam ({
        "account_id": account_id
    });
    this._protoBufHeader.msg = Dota2.schema.EDOTAGCMsg.k_EMsgGCPracticeLobbyKickFromTeam;
    this._gc.send(
        this._protoBufHeader,
        payload.toBuffer(),
        function(header, body) {
            onPracticeLobbyResponse.call(_self, body, callback);
        }
    );
};
```

**Comment by oleghalin** [comment]
And in PracticeLobbyKick im using default function from dev branch

**Comment by Crazy-Duck** [comment]
This seems to be ok as far as I can see. Are you using the correct account id? I'll try to do some tests over the weekend, see if I can find anything.

**Comment by oleghalin** [comment]
Yes. Iam using correct acc id

**Comment by Crazy-Duck** [comment]
I've done some tests myself with both functions and I'm getting the same results. Think this can be tagged as bug.

**Comment by jimmydorry** [comment]
RIP

**Comment by Crazy-Duck** [comment]
Premature RIP-ification by me, I messad up the accountID. Passing in Dota2.ToAccountID(steamID) as argument to `practiceLobbyKick` seems to do the trick to kick you from lobby. Gonna see if the same holds for the other function :$

**Comment by jimmydorry** [comment]
What about kicking other accounts. I believe that is where @oleghalin came unstuck.

**Comment by Crazy-Duck** [comment]
Jup, definetly premature RIP-ification. I tested by having the lobby owner kick someone from the lobby and from the team.
My sincerest apologies dear mods. Everything is working as intended. As penitence I'll make a PR for the practiceLobbyKickFromTeam function.

**Comment by oleghalin** [comment]
What?) I didnt understand anything xD

**Comment by jimmydorry** [comment]
@Crazy-Duck noice.

 @oleghalin you made an error somewhere (no shared code to look at). Just wait till the PR before you try again.

**Comment by oleghalin** [comment]
```
  else if(message == 'kick')
  {
	 Dota2.practiceLobbyKick(76561198107070247);
	 steamFriends.sendMessage(source, 'Игрок кикнут', steam.EChatEntryType.ChatMsg); 
  }
```

**Comment by Crazy-Duck** [comment]
I made a new PR @jimmydorry, should be ok.
@oleghalin try this:
```JavaScript
...
    Dota2.practiceLobbyKick(Dota2.ToAccountID(76561198107070247));
...
```
just make sure that the account doing the kicking is the owner of the lobby

**Comment by jimmydorry** [comment]
Re-download the dev branch @oleghalin 

https://github.com/RJacksonm1/node-dota2/pull/188

**Comment by oleghalin** [comment]
![image](https://cloud.githubusercontent.com/assets/9086983/11977020/27a49e8c-a987-11e5-894a-b0c9879d2735.png)

**Comment by Crazy-Duck** [comment]
This seems to me to be more of a problem with how you initialize and use the library...

**Comment by oleghalin** [comment]
Its after update from dev branch. Before it all was ok

**Comment by Crazy-Duck** [comment]
How do you initialize the bot? Do you create a new instance of Dota2Client? Like 
```JavaScript
var Dota2 = require("dota2");
var bot = new dota2.Dota2Client(steamClient, true, false);
```

**Comment by oleghalin** [comment]
```
    Dota2 = new dota2.Dota2Client(steamClient, true);
```

**Comment by Crazy-Duck** [comment]
You'll have to debug your code, I'm afraid there's not much we can do to solve this. There is something wrong in the way you're naming variables and initializing the bot. The fact that your error message shows a path `Dota2Client.Dota2.Dota2Client.createPracticeLobby` points in that direction

**Comment by oleghalin** [comment]
Its after update from dev branch. Before it all was ok

**Comment by oleghalin** [comment]
Im just reload old dev branch. I think jimmy mistook in code of hanlders. Check it

**Comment by Crazy-Duck** [comment]
There is nothing wrong with the current dev branch, it works fine as it should. In the new update of the dev branch we've reworked all functions to use `Dota2Client.prototype.sendToGC` to send the messages to the GC, instead of calling this._gc.send in every function. Because your code doesn't seem to find `this.sendToGC' it seems like you're calling `createPracticeLobby` from an erroneous context, one which is NOT a Dota2Client object.

**Comment by oleghalin** [comment]
I reload my old dev branch and everthing is ok.

**Comment by oleghalin** [comment]
Ill write lobby hanlder and send it to this github

**Comment by jimmydorry** [comment]
If you just pastebinned the entire file you wrote, there would be a chance we could see what you did.

**Comment by oleghalin** [comment]
I understand it. Ill try today paste it.

**Comment by oleghalin** [comment]
http://pastebin.com/Zgb6ASvc
This is my lobbies.js with AbadnonCurrentGame, practiceLobbyKick and practiceLobbyKickFromTeam.
Everthing works good.

**Comment by Crazy-Duck** [comment]
you misunderstood, we need the code which actually uses these functions

**Comment by oleghalin** [comment]
...
    Dota2.practiceLobbyKick(Dota2.ToAccountID('76561198107070247'));
...
this one

**Comment by Crazy-Duck** [comment]
yes, that's a part, we need to see the entire code, including the pieces where you create Dota2 etc.

**Comment by oleghalin** [comment]
Master branch test.js

**Comment by Crazy-Duck** [comment]
hmm, @jimmydorry I might need some help on this one. As far as I can see in test.js the functions are all called from within the ["ready" handler](https://github.com/RJacksonm1/node-dota2/blob/master/test/test.js#L20). Could it be that when `Dota2.createPracticeLobby(...)` is invoked from inside this handler, the event is passed as the context instead of the Dota2Client object on which the function is called?

**Comment by jimmydorry** [comment]
I think you know more than me.

Were you testing using the latest library version (i.e. The callback changes)?

If so, why not just paste it here so we have something to check against?

I don't see any obvious race conditions in the test code, but it's 2:20am here.

**Comment by jimmydorry** [comment]
You may want more debug messages too.

https://github.com/RJacksonm1/node-dota2/blob/dev/index.js#L35

**Comment by Crazy-Duck** [comment]
See #192 . The test.js example now works. I tested creation of a lobby starting from a clean node js installation using the dev branch and the example and the lobby got created as it should.

**Comment by Maevnik** [comment]
IMHO, one possible solvation for it is convert your steam id to string (It is possible, if you're using numbers type as is)
