### ISSUE TITLE
Dota2.schema.CMsgFindSourceTVGames is not a function

### ISSUE THREAD

**Issue by RandomSeeded** [RJacksonm1/node-dota2#185]
I'm attempting to use the requestSourceTVGames function as defined in helpers/sourceTV.js

It contains the following invocation: 

    var payload = new Dota2.schema.CMsgFindSourceTVGames(merge({
        "searchKey": '',
        "start": 0,
        "numGames": 6,
        "leagueid": 0,
        "heroid": 0,
        "teamGame": false,
        "customGameId": 0,
    },filter_options));

However, the relevant CMsg is undefined on the Dota2 schema. I did a quick grep, and found that it does exist inside the steam npm module (steam-resources/protobufs/dota test/dota_gcmessages_client.proto). Tried copying & pasting the relevant proto from the node_modules into proto/dota_gcmesages_client.proto, but that then threw Error: .CMsgFindSourceTVGames#searchKey is not a field: undefined

Without much knowledge of the codebase or the steam GC in general, not really sure where to start trying to debug this, but I figured if nothing else you would probably want to know that the requestSourceTVGames function appears non-functional.

**Comment by Crazy-Duck** [comment]
We've known this problem for a while, the CMsg hasn't been functional for a couple of weeks. I suggest you check out the dev branch, we've implemented the proto handler for the message which replaces this one. This issue can be closed.

**Comment by RandomSeeded** [comment]
Thanks for the info, appreciated
