### ISSUE TITLE
Can i get a match details which i had created?

### ISSUE THREAD

**Issue by tsbilguun7167** [RJacksonm1/node-dota2#190]
Hello i like your project and using it. I have one question i wanted to use lobby creator. Can i get lobby details which i had created. I am developing website like tournament creator. Thanks for support

**Comment by jimmydorry** [comment]
Everything you need should be in the dev branch. If you have a specific question feel free to ask it in a new issue, but people probably won't be back to look here until the new year. :)

https://github.com/RJacksonm1/node-dota2/tree/dev
