### ISSUE TITLE
API key or steam_guard_code

### ISSUE THREAD

**Issue by Altantur** [RJacksonm1/node-dota2#191]
Hi, It is not relevant to api. steam_guard_code was sending to me  in runtime which is I can't fill it right way. 
Do we have to use API key or something? Please helps this issue. Thank you.

**Comment by Altantur** [comment]
If we use steam_guard_code as referred and launched again steam sends another code. Seems never gonna work properly everytime it sends different one.

**Comment by jimmydorry** [comment]
1. Use dev branch. https://github.com/RJacksonm1/node-dota2/tree/dev
2. Run app, get steamguard code, stop app
3. Save steamguard code into config, run app, remove steamguard code from config
4. Save sentry file so steamguard is bypassed

OR

Make a new account without steamguard.

------------

Keep in mind that using the same account for bot, as the one you use in steam will have lots of weird interactions, like logging each other out.

**Comment by jimmydorry** [comment]
And this library is all about steamguard. No API keys. 

Re-open this issue if you are still stuck, or make a new issue with a specific question.
