### ISSUE TITLE
Spectator bot in lobbies

### ISSUE THREAD

**Issue by miovski** [RJacksonm1/node-dota2#193]
Is there a way to move the bot into spectator when creating lobby ?

**Comment by jimmydorry** [comment]
https://github.com/RJacksonm1/node-dota2/issues/176

Use the dev branch, and checkout the last issue that was like that.

https://github.com/RJacksonm1/node-dota2/tree/dev

Re-open or make a new issue if you have further questions.

**Comment by Crazy-Duck** [comment]
To be more precise, check out the lobbies.js handler, you'll find a function which can be called like this: `joinPracticeLobbyTeam(1, Dota2.schema.DOTA_GC_TEAM.DOTA_GC_TEAM_PLAYER_POOL);`. All players in the pool become spectators upon starting the match

**Comment by oleghalin** [comment]
```
Dota2.joinPracticeLobbyTeam(1, 4, function(err, data){
		if(JSON.stringify(data['result']) == 1)
		{
			util.log("Бот занял место наблюдателя.");
		}
	});
```
This how my code is looks
