### ISSUE TITLE
Multiple user config

### ISSUE THREAD

**Issue by Altantur** [RJacksonm1/node-dota2#197]
Happy new year everyone, Hope you have great year so far!
is it possible to logon with multiple users? if so how we write config for bots? Thank you.

**Comment by howardchung** [comment]
Yes, you can.  However node-dota2 doesn't handle this--you are responsible for implementing the logic to choose accounts yourself.  You'll need to create a new instance of node-steam/node-dota2 for each account.

**Comment by Altantur** [comment]
Thank you quick answer. I got it :smile:
