### ISSUE TITLE
requestProfileCard sometimes doesnt return

### ISSUE THREAD

**Issue by Hack3l** [RJacksonm1/node-dota2#198]
I have writen a little programm that goes through many dota profiles and requests their ProfileCard it works fine most of the time but sometimes it just doesnt return a callback (probably hanging somewhere) i tried it with both debug modes on still no result after "sending profile card request" any ideas where this might come from?

**Comment by Crazy-Duck** [comment]
How many requests are you sending? Valve doesn't like people spamming their servers, so after a certain amount of requests (I think 100(0)/day) they block your account. You need to make sure to rate limit your bot and use multiple accounts

**Comment by howardchung** [comment]
I can confirm the limit is over 1000/day/account for requestProfileCard.  I
didn't really try beyond that.

**Comment by Hack3l** [comment]
it still works after i restart the script it just stops the script and as soon as i try again everything is normal

**Comment by howardchung** [comment]
In that case you're probably not getting back a response for one of the
requests and waiting for a callback that never comes.  Add a timeout.

**Comment by jimmydorry** [comment]
When did the requestProfileCard rate limit change? In the pre-reborn client, it was 100/day/IP

That's nice of Valve to relax that limit.

**Comment by howardchung** [comment]
Old profiles were 100/day.  I assume it's because profilecards are much
higher traffic (since you can view one just by mousing over someone's name).

**Comment by jimmydorry** [comment]
I would hit the rate limit in the old client, just through playing games normally. I didn't expect Valve to make a more rational limit. :)

**Comment by jimmydorry** [comment]
Stale issue. Re-open or make a new issue.

- Please rate the service provided on a scale of 1 to 7
- Please rate your satisfaction as a result of interaction with @howardchung on a scale of 1 to 6.5

Have a nice day, and remember that Dota2 is serious business. Your happiness matters to someone.
