### ISSUE TITLE
Parties bug

### ISSUE THREAD

**Issue by Maevnik** [RJacksonm1/node-dota2#199]
Please, replace 
# Dota2.EGCBaseMsg.k_EMsgGCInviteToParty #  
to 
# Dota2.schema.EGCBaseMsg.k_EMsgGCInviteToParty. #
Great job, guys.
With great wishes, Random Developer

**Comment by Maevnik** [comment]
Dota2.launch()
		Dota2.on('ready',function(){
			console.log(Dota2.Lobby)	
			var options = {
				"game_name": "Name of your lobby",
				"server_region": 3,
				"game_mode": 2,
				"game_version": 1,
				"allow_cheats": false,
				"fill_with_bots": false,
				"allow_spectating": true,
				"pass_key": "password",
				"radiant_series_wins": 0,
				"dire_series_wins": 0,
				"allchat": true
			}
			Dota2.createPracticeLobby(options.pass_key, options, function(msg){
				console.log(msg)
			})
		})

**Comment by jimmydorry** [comment]
Make a PR, you can even do it all via the site (it will fork to your repo, where you make changes, and then PR back into developer branch). 

Otherwise @Crazy-Duck

**Comment by Crazy-Duck** [comment]
There you go, should be fixed now

**Comment by jimmydorry** [comment]
@Maevnik pull the dev branch to ACK or NACK
