### ISSUE TITLE
Dev dependencies out of date

### ISSUE THREAD

**Issue by Crazy-Duck** [RJacksonm1/node-dota2#203]
There is a more recent major version of `should` available, we should test if everything still works with the new version and if not update the dependency

https://david-dm.org/RJacksonm1/node-dota2#info=devDependencies&view=table

**Comment by RJacksonm1** [comment]
> ![image](https://cloud.githubusercontent.com/assets/602850/12119049/3850abba-b3c1-11e5-8f8b-47f16905bd24.png)

Who caaaaaaaaaaaaaares

**Comment by Crazy-Duck** [comment]
But... Muh shiny green badges D:

**Comment by jimmydorry** [comment]
Stuff isn't exploding and people aren't complaining, so I assume we are gucci?

**Comment by Crazy-Duck** [comment]
Yeah, should be ok.
