### ISSUE TITLE
Can the bot listen in-game chat?

### ISSUE THREAD

**Issue by XenBG** [RJacksonm1/node-dota2#204]
Hello, I want my bot to interact with the players in the game server, so I've tried to put him in channel.

```Dota2.joinChat("Game_" + LobbyID, 11);```

At the moment the bot can listen the lobby states, but he can't listen the in-game chat.

**Comment by jimmydorry** [comment]
Pretty sure that is not a thing. Bots don't join the game, and even if they did... they would only see all-chat.

**Comment by Crazy-Duck** [comment]
That's because you are joining the wrong channel, check the readme, it contains several important channels. You are looking for `'Lobby_' +lobby_id`

On 6 Jan 2016 1:37 pm, Tom <notifications@github.com> wrote:

Hello, I want my bot to interact with the players in the game server, so I've tried to put him in channel

Dota2joinChat("Game_" + LobbyID, 11);

At the moment the bot can listen the lobby states, but he can't listen the in-game chat

**Comment by XenBG** [comment]
@Crazy-Duck I put him in the Lobby chat channel, but I can't put him to the in-game chat channel. There is no way to do this with NodeJS?

**Comment by Crazy-Duck** [comment]
There probably is, just need to find the right format. I haven't tried joining in game chat myself, I thought lobby chat was the same as in game allchat. Just nethook yourself starting a lobby, you should see a joinchatchannel message being sent to the GC. If you find out, add the format to the Readme ☺

On 6 Jan 2016 1:41 pm, Tom <notifications@github.com> wrote:

@Crazy-Duck I put him in the Lobby chat channel, but I can't put him to the in-game chat channel. There is no way to do this with NodeJS?

**Comment by jimmydorry** [comment]
Here is when I last mentioned nethook. Use a dummy account that is not limited.

https://github.com/RJacksonm1/node-dota2/issues/141#issuecomment-153559554

**Comment by XenBG** [comment]
```6 Jan 08:26:26 - Joining chat channel: Game_24361177125537785
6 Jan 08:26:26 - Chat channel Game_24361177125537785 has 1 person(s) online```

After starting the lobby, but still the bot can't listen the in-game chat. Maybe the prefix or the number are wrong. I can't nethook, because I don't know how :D.

**Comment by jimmydorry** [comment]
Read the link.

**Comment by jimmydorry** [comment]
Stale issue. Probably technically possible, but requires a code sponsor or for the proposer to do the leg-work and Nethook to see if it's possible.

Make a new issue or open a new one if you Nethook it.
