### ISSUE TITLE
Need help with simply connecting to Dota 2 GC and fetching match data.

### ISSUE THREAD

**Issue by ESipalis** [RJacksonm1/node-dota2#206]
Hi guys,
I am totally new to node.js,git,so I need only really simple example how to login to steam and Dota 2 and then fetch match detail data.
After some time I managed to get the command "npm test" working,but I don't want to run it in that way,I want "node filename" to work.
Apparently copying a few functions from test.js to a new file doesn't work,because node.js isn't working synchronizating way(One function doesn't wait for other to finish).After some time,I came up with this code: http://pastebin.com/i6uVdyaq , which should have worked by my logic,but it didn't :-1: 
Could someone give me a simple example file,which would connect to steam and dota and then fetch match details.
Thanks in advance!
P.S. I only now discovered that there are branches in github and that there is a dev branch -_O.

**Comment by jimmydorry** [comment]
I'm guessing you weren't on the dev branch.

Have another look at the updated and working version of the library.

https://github.com/RJacksonm1/node-dota2/blob/dev/test/test.js

Make sure to look at the new readme if you get stuck.

https://github.com/RJacksonm1/node-dota2/blob/dev/README.md

**Comment by ESipalis** [comment]
Yeah,downloaded files from there,looked at examples,fixed everything now!
Thank you for your comment.
God,I wish I haven't wasted like 5hours on it :dash:
