### ISSUE TITLE
Problem about the test.js handling sentry file

### ISSUE THREAD

**Issue by ZiRoger** [RJacksonm1/node-dota2#207]
When I try to run the test/test.js, I found a little flaw about the sentry file storing. As the code below:
```javascript
steamUser.on('updateMachineAuth', function(sentry, callback) {
    fs.writeFileSync('sentry', sentry.bytes)
    util.log("sentryfile saved");
    callback({
        sha_file: crypto.createHash('sha1').update(sentry.bytes).digest()
    });
});
```
The code save the sentry bytes directly which is ok for me. But when using the sentry to login, the code read the sentry file without hashing it.
...
```javascript
try {
    var sentry = fs.readFileSync('sentry');
    if (sentry.length) logOnDetails.sha_sentryfile = sentry;
} catch (beef) {
    util.log("Cannae load the sentry. " + beef);
}
```
This may leading the situation that you will receive the 63 error continually when you login with the sentry.
My solution is store the hashed bytes or hash the sentry after read it.
```javascript
 fs.writeFileSync('sentry', crypto.createHash('sha1').update(sentry.bytes).digest())
```
or hash the sentry after read it
```javascript
if (sentry.length) logOnDetails.sha_sentryfile = crypto.createHash('sha1').update(sentry).digest();
```
Cheers!

**Comment by Crazy-Duck** [comment]
Feel free to checkout the dev branch and make a pull request ☺

On 11 Jan 2016 12:07 pm, Roger <notifications@github.com> wrote:

When I try to run the test/testjs, I found a little flaw about the sentry file storing As the code below:

steamUseron('updateMachineAuth', function(sentry, callback) { fswriteFileSync('sentry', sentrybytes) utillog("sentryfile saved"); callback({ sha_file: cryptocreateHash('sha1')update(sentrybytes)digest() }); });

The code save the sentry bytes directly witch is ok for me But when using the sentry to login, the code read the sentry file without hashing it

try { var sentry = fsreadFileSync('sentry'); if (sentrylength) logOnDetailssha_sentryfile = sentry; } catch (beef) { utillog("Cannae load the sentry " + beef); }

This may leading the situation that you will receive the 63 error continually when you login with the sentry
To solve it is simple as you can see Store the hashed bytes or hash the sentry after read it

fswriteFileSync('sentry', cryptocreateHash('sha1')update(sentrybytes)digest())

or

if (sentrylength) logOnDetailssha_sentryfile = cryptocreateHash('sha1')update(sentry)digest();

Cheers!
