### ISSUE TITLE
Unhandled message IDs

### ISSUE THREAD

**Issue by XenBG** [RJacksonm1/node-dota2#209]
When the lobby is created and started:

```12 Jan 09:25:33 - UNHANDLED MESSAGE #3001```
```12 Jan 09:25:34 - UNHANDLED MESSAGE #7581```
```12 Jan 09:33:47 - UNHANDLED MESSAGE #8081```

If somebody have description for these IDs, let us know :).

**Comment by jimmydorry** [comment]
https://github.com/RJacksonm1/node-dota2/blob/dev/proto/gcsystemmsgs.proto#L105
https://github.com/RJacksonm1/node-dota2/blob/dev/proto/dota_gcmessages_common.proto#L503
https://github.com/RJacksonm1/node-dota2/blob/dev/proto/dota_gcmessages_common.proto#L608
