### ISSUE TITLE
Where is config.js.example?

### ISSUE THREAD

**Issue by tomasmck** [RJacksonm1/node-dota2#217]
In the README, part of the setup includes copying a config file:

> Copy config.js.example to config.js and edit appropriately

I don't see this anywhere in the repo. I'm unable to run example.js without a reference to the config file.

**Comment by Crazy-Duck** [comment]
derp, must have gotten lost in one merge or another '-_-
anyways, it should look something like this:

```
// Configure and mv to config.js
var config = {};

config.steam_name = "mySteamName";
config.steam_user = "mySteamUserName";
config.steam_pass = "mySteamPassword";
config.steam_guard_code = "steamGuardCodeIfApplicable";

module.exports = config;
```

**Comment by jimmydorry** [comment]
oops

**Comment by kiddick** [comment]
Sorry, duplicated https://github.com/RJacksonm1/node-dota2/issues/219
