### ISSUE TITLE
Cannae load the sentry.

### ISSUE THREAD

**Issue by kiddick** [RJacksonm1/node-dota2#220]
I am getting this annoying error every time then I am trying to run tests,

```
29 Jan 14:04:35 - Cannae load the sentry. Error: ENOENT: no such file or directory, open '...\node\node-dota2\test\sentry'
29 Jan 14:04:37 - Connection closed by server.
```

Can't figure what is the reason for that.
Is it steamkit related?
Any ideas?

**Comment by jimmydorry** [comment]
Is there a sentry file in that location? If not, try making one.

**Comment by kiddick** [comment]
@jimmydorry just an empty file?

**Comment by jimmydorry** [comment]
Yes, try it. That's literally what the error says.

**Comment by kiddick** [comment]
@jimmydorry thanks.
There is not this error anymore.
But now every time `Connection closed by server.` I getting this.
Trying to go deeper.

**Comment by jimmydorry** [comment]
No problem. Make sure to read the errors, and look through the readme.

**Comment by tomasmck** [comment]
I was able to connect yesterday but today I'm seeing the same 'connection closed by server'. This is reported when onSteamError is called.

There's nothing in the readme to indicate what could be causing this. Does anyone have any ideas for troubleshooting?

**Comment by jimmydorry** [comment]
The most obvious cause would be Steam maintenance Tuesday. So check https://steamstat.us/ first.

Then make sure the sentry file exists in the correct location. Also, make sure there is no sentry code in your config.

Also, it never hurts to grab an up to date copy of this lib from here, and drop it over your current version. It's always possible that the NPM is out of date, or not pushed out yet.

https://github.com/RJacksonm1/node-dota2/archive/master.zip

**Comment by tomasmck** [comment]
Thanks @jimmydorry
