### ISSUE TITLE
Use bot as a spectator to get match detail from practice lobby

### ISSUE THREAD

**Issue by taloto07** [RJacksonm1/node-dota2#223]
Is there a way to use bot as spectator to get match detail from practice lobby? Note: bot is not one of the players in the lobby, and bot can not get players' practice lobby match detail either since bot is not playing this match.

**Comment by jimmydorry** [comment]
Answered here: https://github.com/RJacksonm1/node-dota2/issues/194#issuecomment-175599066

**Comment by jimmydorry** [comment]
Summary:

1. Start game with bot in broadcast slot
2. Listen for "practiceLobbyUpdate" event
3. Parse the data returned, that should be in a form like: http://hastebin.com/enopuliric.json

**Comment by taloto07** [comment]
Thank you for your responding. "practiceLobbyUpdate" only gives information about lobby. But, I'm looking for information about Death, Kill, Assistance, Gold.... after the match is finished.

In Dota application, as a spectator, I can see match detail just like a player, but when I try to use NetHook to sniff packages, I don't see anything related to match detail that being send back and forth between client and server. Just wonder if anyone can use bot to get other player's practice match detail without their steam's account and password.

**Comment by jimmydorry** [comment]
Did you nethook as a broadcaster?

**Comment by jimmydorry** [comment]
@paralin Does your super sekret projekt grab live match details like Deaths, Kills, Assists, Gold, etc. ? If so, what is the general process or which event are you listening for?

**Comment by taloto07** [comment]
Yes, I nethooked as both broadcaster and player.

**Comment by paralin** [comment]
You can get those stats with either a GetMatchDetails (but this won't work in a private lobby unless you're  a player) or a API call if you have a ticket. 

My "super sekret projekt" - https://github.com/paralin/Dota2/tree/master/src/Dota2.GameClient - worked in Source 1 but is broken in source 2. It could connect completely into the game and get you whatever you wanted.

**Comment by jimmydorry** [comment]
RIPeroni. That sucks. Atleast you can still get some match details, like heroes and who won.

**Comment by Crazy-Duck** [comment]
It should be possible though, if you look at the protos there's all kinds of interesting stuff. The following protos contain a buttload of data concerning an ongoing match. I'd hazard a guess that there should be a way to grab this data when you're in a spectator/broadcasting slot. 
```
message CMsgDOTARealtimeGameStats {
	message TeamDetails {
		optional uint32 team_number = 1;
		optional uint32 team_id = 2;
		optional string team_name = 3;
		optional fixed64 team_logo = 4;
		optional uint32 score = 5;
		repeated .CMsgDOTARealtimeGameStats.PlayerDetails players = 6;
		optional bool only_team = 7;
		optional uint32 cheers = 8;
	}

	message ItemDetails {
		optional uint32 id = 1;
		optional string name = 2;
		optional int32 time = 3;
		optional bool sold = 4;
		optional uint32 stackcount = 5;
	}

	message AbilityDetails {
		optional uint32 id = 1;
		optional string name = 2;
		optional uint32 level = 3;
		optional float cooldown = 4;
		optional float cooldown_max = 5;
	}

	message HeroToHeroStats {
		optional uint32 victimid = 1;
		optional uint32 kills = 2;
		optional uint32 assists = 3;
	}

	message AbilityList {
		repeated uint32 id = 1;
	}

	message PlayerDetails {
		optional uint32 accountid = 1;
		optional uint32 playerid = 2;
		optional string name = 3;
		optional uint32 team = 4;
		optional uint32 heroid = 5;
		optional uint32 healthpoints = 6;
		optional uint32 maxhealthpoints = 7;
		optional float healthregenrate = 8;
		optional uint32 manapoints = 9;
		optional uint32 maxmanapoints = 10;
		optional float manaregenrate = 11;
		optional uint32 base_strength = 12;
		optional uint32 base_agility = 13;
		optional uint32 base_intelligence = 14;
		optional int32 base_armor = 15;
		optional uint32 base_movespeed = 16;
		optional uint32 base_damage = 17;
		optional uint32 strength = 18;
		optional uint32 agility = 19;
		optional uint32 intelligence = 20;
		optional int32 armor = 21;
		optional uint32 movespeed = 22;
		optional uint32 damage = 23;
		optional uint32 hero_damage = 24;
		optional uint32 tower_damage = 25;
		repeated .CMsgDOTARealtimeGameStats.AbilityDetails abilities = 26;
		optional uint32 level = 27;
		optional uint32 kill_count = 28;
		optional uint32 death_count = 29;
		optional uint32 assists_count = 30;
		optional uint32 denies_count = 31;
		optional uint32 lh_count = 32;
		optional uint32 hero_healing = 33;
		optional uint32 gold_per_min = 34;
		optional uint32 xp_per_min = 35;
		optional uint32 net_gold = 36;
		optional uint32 gold = 37;
		optional float x = 38;
		optional float y = 39;
		optional int32 respawn_time = 40;
		optional uint32 ultimate_cooldown = 41;
		optional bool has_buyback = 42;
		repeated .CMsgDOTARealtimeGameStats.ItemDetails items = 43;
		repeated .CMsgDOTARealtimeGameStats.ItemDetails stashitems = 44;
		repeated .CMsgDOTARealtimeGameStats.ItemDetails itemshoppinglist = 45;
		repeated .CMsgDOTARealtimeGameStats.AbilityList levelpoints = 46;
		repeated .CMsgDOTARealtimeGameStats.HeroToHeroStats hero_to_hero_stats = 47;
		optional bool has_ultimate = 48;
		optional bool has_ultimate_mana = 49;
	}

	message BuildingDetails {
		optional uint32 team = 2;
		optional float heading = 3;
		optional uint32 lane = 4;
		optional uint32 tier = 5;
		optional uint32 type = 6;
		optional float x = 7;
		optional float y = 8;
		optional bool destroyed = 9;
	}

	message KillDetails {
		optional uint32 player_id = 1;
		optional int32 death_time = 2;
		optional uint32 killer_player_id = 3;
	}

	message BroadcasterDetails {
		optional uint32 player_id = 1;
		optional uint32 selected_hero = 2;
		optional uint32 selected_graph = 3;
	}

	message PickBanDetails {
		optional uint32 hero = 1;
		optional uint32 team = 2;
	}

	message MatchDetails {
		optional fixed64 server_steam_id = 1;
		optional uint64 matchid = 2;
		optional uint32 timestamp = 3;
		optional float time_of_day = 4;
		optional bool is_nightstalker_night = 5;
		optional int32 game_time = 6;
		optional uint32 teamid_radiant = 8;
		optional uint32 teamid_dire = 9;
		repeated .CMsgDOTARealtimeGameStats.PickBanDetails picks = 10;
		repeated .CMsgDOTARealtimeGameStats.PickBanDetails bans = 11;
		repeated .CMsgDOTARealtimeGameStats.KillDetails kills = 12;
		repeated .CMsgDOTARealtimeGameStats.BroadcasterDetails broadcasters = 13;
		optional uint32 game_mode = 14;
		optional uint32 league_id = 15;
		optional bool single_team = 16;
		optional uint32 cheers_peak = 17;
	}

	message GraphData {
		message LocationStats {
			repeated int32 stats = 1;
		}

		message TeamLocationStats {
			repeated .CMsgDOTARealtimeGameStats.GraphData.LocationStats loc_stats = 1;
		}

		enum eStat {
			CreepGoldEarned = 0;
			KillGoldEarned = 1;
			DeathAndBuybackGoldLost = 2;
			XPEarned = 3;
		}

		enum eLocation {
			BotLane = 0;
			MidLane = 1;
			TopLane = 2;
			Jungle = 3;
			Ancients = 4;
			Other = 5;
		}

		repeated int32 graph_gold = 1;
		repeated int32 graph_xp = 2;
		repeated int32 graph_kill = 3;
		repeated int32 graph_tower = 4;
		repeated int32 graph_rax = 5;
		repeated .CMsgDOTARealtimeGameStats.GraphData.TeamLocationStats team_loc_stats = 6;
	}

	optional .CMsgDOTARealtimeGameStats.MatchDetails match = 1;
	repeated .CMsgDOTARealtimeGameStats.TeamDetails teams = 2;
	repeated .CMsgDOTARealtimeGameStats.BuildingDetails buildings = 3;
	optional .CMsgDOTARealtimeGameStats.GraphData graph_data = 4;
	optional bool delta_frame = 5;
}

message CMsgDOTARealtimeGameStatsTerse {
	message TeamDetails {
		optional uint32 team_number = 1;
		optional uint32 team_id = 2;
		optional string team_name = 3;
		optional fixed64 team_logo = 4;
		optional uint32 score = 5;
		repeated .CMsgDOTARealtimeGameStatsTerse.PlayerDetails players = 6;
	}

	message PlayerDetails {
		optional uint32 accountid = 1;
		optional uint32 playerid = 2;
		optional string name = 3;
		optional uint32 team = 4;
		optional uint32 heroid = 5;
		optional uint32 level = 6;
		optional uint32 kill_count = 7;
		optional uint32 death_count = 8;
		optional uint32 assists_count = 9;
		optional uint32 denies_count = 10;
		optional uint32 lh_count = 11;
		optional uint32 gold = 12;
		optional float x = 13;
		optional float y = 14;
	}

	message BuildingDetails {
		optional uint32 team = 1;
		optional float heading = 2;
		optional uint32 type = 3;
		optional uint32 lane = 4;
		optional uint32 tier = 5;
		optional float x = 6;
		optional float y = 7;
		optional bool destroyed = 8;
	}

	message MatchDetails {
		optional fixed64 server_steam_id = 1;
		optional uint64 matchid = 2;
		optional uint32 timestamp = 3;
		optional int32 game_time = 4;
		repeated uint32 steam_broadcaster_account_ids = 6;
		optional uint32 game_mode = 7;
		optional uint32 league_id = 8;
	}

	message GraphData {
		repeated int32 graph_gold = 1;
	}

	optional .CMsgDOTARealtimeGameStatsTerse.MatchDetails match = 1;
	repeated .CMsgDOTARealtimeGameStatsTerse.TeamDetails teams = 2;
	repeated .CMsgDOTARealtimeGameStatsTerse.BuildingDetails buildings = 3;
	optional .CMsgDOTARealtimeGameStatsTerse.GraphData graph_data = 4;
	optional bool delta_frame = 5;
}
```

**Comment by howardchung** [comment]
My understanding is that node-dota2 only handles connection to the GC.  Getting all the other data requires a connection to the actual game server.

**Comment by jimmydorry** [comment]
In game, definitely (as that's how all of the spectator/broadacaster overlays work)! 

However, I don't think node-dota2 can go that last mile and join the actual game. It can just sit in the lobby.

**Comment by jimmydorry** [comment]
Damn, ninja'ed

**Comment by Crazy-Duck** [comment]
Why would communicating with the actual game server be any more difficult than communicating with the GC? Going by the protobufs, it would seem that the protocol has to be quite similar. The guys behind TrackDota seem to be able to obtain ingame matchdata and I doubt they have a full fledged game client running for each match they need to spectate (at least I hope they don't). If node-dota doesn't handle it yet, doesn't mean we can't add it at some point :D

**Comment by paralin** [comment]
@Crazy-Duck Because it's a completely different protocol. The ingame communication is Source 2 networking. This is ENTIRELY different from the comparatively simple GC and Steam communication.

Just look at all the work that was put into the Source 1 code: https://github.com/paralin/Dota2/blob/master/src/Dota2.GameClient/Engine/Session/DotaGameConnection.cs

TrackDota does it by checking the HTTP api for live league games. Very simple.

It's not something that node would be able to do, I think. In the long run the best bet would be to re-implement it again in C# using the existing code structure we have. The protocol has been significantly altered though, so it's not going to be as easy as you think.

**Comment by paralin** [comment]
I think the best way forward for this in node-dota2 is to see if we can check the data from these two things:

 - Check to see how http://www.dota2.com/watch/ works. What triggers a game showing up there? Can we trigger this via a bot? How complex will it be to reverse the protocol? (should be easy, all the javascript code is there)
 - Check to see if we can somehow hook into the data coming from the GC for the "watch games" tab which includes the delayed view of the map and the player stats. i think this data will be approximately the same as from the HTTP api with the same delay but it could be used to get this data for non-league matchmaking games.

**Comment by Crazy-Duck** [comment]
hmm, I see your point, it looks a hell of a lot more complicated than I thought it would be.. However I don't necessarily agree that this wouldn't be feasible in node. In the end they're still just messages sent over the wire. Especially with ES6 I think it might be possible to pull it off. If we could pull this off, it would open up the doors to a whole new set of functionalities (think for example AI API's etc.). I think it might be worth looking into.
I like the idea of reverse engineering dota2 watch, but this wouldn't solve the problem for private lobbies unfortunately.

**Comment by paralin** [comment]
@Crazy-Duck It's a *lot* of data going over the wire with an emphasis on proper threading and constant tick speed. This is **not** something that node is at ALL good at. Especially since Node is single threaded.

Most promising thing here is the watch page or other GC based ways of getting stats.

**Comment by Crazy-Duck** [comment]
I'm just throwing around ideas, hadn't considered the threading issues yet. I'm still wondering though, wouldn't the inherent simplicity of a bot (seeing as there's no need to occupy ourselves with rendering and stuff) leave us with enough leeway to work around this? Especially in the case where we'd want to just plop a bot into the spectator slot and only concern us with game data and not so much actual interaction with the game (again, just spitballing here)

**Comment by paralin** [comment]
@Crazy-Duck Even if you're a spectator the client is expected to behave like a player. So this means you need to send ticks in lockstep with the server.

It might be more feasable to reverse engineer the SourceTV protocol. But I think this format is exactly the same, just with a proxy in between the client and the server.

**Comment by Crazy-Duck** [comment]
I'll try and take a look at the /watch code in the coming days/weeks, see if I can whip something up

**Comment by paralin** [comment]
Holy shit, this was *way* easier than expected.

https://gist.github.com/paralin/100ef20e1562ade0d725

The data is in JSON. Wow.

Request url: http://valve600.cs.steampowered.com/broadcast/2705567649847572738/segment/game/1/825/?broadcast_origin=br02.broadcast.fra.steamstatic.com:80

I'm guessing the segment just increments?

The next url after that one was: http://valve600.cs.steampowered.com/broadcast/2705567649847572738/segment/video/1/825/?broadcast_origin=br02.broadcast.fra.steamstatic.com:80

The code is embedded in the page for a giant object with hero definitions and other constants as well as the information needed to contact the server.

**Comment by Crazy-Duck** [comment]
That's.. surprisingly easy. Am I correct that this contains literally the entire gamestate? Seems like you get everything from current stats to item builds, positioning, ... Anything you could want really

**Comment by paralin** [comment]
Yes. Only drawback is you need to be broadcasting.

**Comment by jimmydorry** [comment]
I recall the steam monster game working in a similar way. That would be pretty funny if it was really a test for how the broadcasting would scale.

**Comment by tomasmck** [comment]
I'm trying to do something similar (monitor the state of the game, in particular to find out who won).

I'm not able to add the bot as a Broadcaster or Spectator, however.

`Dota2.joinPracticeLobbyTeam(10, dota2.schema.DOTA_GC_TEAM.DOTA_GC_TEAM_SPECTATOR, broadcasterResponse())`

The response that I receive:

`{"result":9}`

I have tried a few different slots [1-10]. Is there a reference to what these errors may mean somewhere?

**Comment by jimmydorry** [comment]
Absolutely, but getting eResult 9 is weird. Maybe it's something else. https://github.com/RJacksonm1/node-dota2/blob/master/handlers/helper.js#L5

**Comment by paralin** [comment]
It's something else... I can do this fine in C#

**Comment by jimmydorry** [comment]
What has faceIT been doing since reborn? Out of curiosity.

**Comment by paralin** [comment]
Not sure what you mean. What's being developed or how have we solved a particular problem introduced by reborn?

**Comment by jimmydorry** [comment]
I assume you track more than just which team won, and in Source1, you could actually join the game. Just wondering how FaceIT has worked around this functionality loss.

**Comment by paralin** [comment]
I never actually implemented the game joining into the prod code, it wasn't quite stable enough when reborn hit. 

We have tickets on every match and use valve apis to get stats. For private lobbies we just have access to the lobby data (match id, hero data, ...). You can't fetch replay as a spectator yet. Once that's possible we can do replay parsing too.

**Comment by taloto07** [comment]
@paralin How did you get match's tickets?

**Comment by paralin** [comment]
Valve gives us a ticket called FACEIT League (id 4122)

**Comment by jimmydorry** [comment]
RIP. I guess you can still do enough with that data though, in combination with webAPI. Thanks for sharing.

**Comment by Crazy-Duck** [comment]
I wonder, can you download replays for games you've coached? If so, i guess you could inject a bot as a team coach and have access to the replay file afterwards. 
Another possibility (which is a lot more resource intensive) is to set up source TV for your private lobbies and get the match data that way

**Comment by paralin** [comment]
Coaching? You mean in MM? Or lobbies?

Assuming you mean lobbies, I've checked and no slot other than player gives you replay access.

**Comment by paralin** [comment]
We did sourceTV before, that was what the GameClient code did, but if you remember that code doesn't work in source 2 :)

**Comment by Crazy-Duck** [comment]
I meant scraping the data from dota2.com/watch :)
