### ISSUE TITLE
Is there any way to get count of matches by player id?

### ISSUE THREAD

**Issue by kiddick** [RJacksonm1/node-dota2#224]
Since `requestPlayerMatchHistory(account_id, [options], [callback])` requires `matches_requested` option, is there any way how we could get count of matches for certain player id?

**Comment by jimmydorry** [comment]
That kind of thing is generally better done via webAPI. Have a look on the dota2 dev forum in the webAPI section.

**Comment by kiddick** [comment]
@jimmydorry okay, thanks.
That's bad that we haven't unified place for getting such common data.

**Comment by jimmydorry** [comment]
You can't even get all of a players matches via webapi (and probably not for ingame too). 

The major difference between in-game and webapi, is overhead. Even if you figure out how to do it in node, the webapi will be far cheaper, faster, and scalable.

**Comment by kiddick** [comment]
> You can't even get all of a players matches via webapi (and probably not for ingame too). 

There is definitely should be a way, since such services as dotabuff and yasp has such data.

**Comment by jimmydorry** [comment]
They actually don't. The webapi only serves a specific window of matches, and those that happened too long ago are lost. There used to be a trick where you could set a max/min date to shift the window, but I believe they broke it.

The new trick is to filter by hero to get that 500 game window for each hero. This covers most people for their full history... unless they play a lot, or focus on a few heroes.

https://yasp.co/faq they mention this.

**Comment by kiddick** [comment]
Ah, remember something like that.
A couple years ago I've written java application to retrieve math data.
But since Volvo broken pagination by date max/mix it goes down. :(

**Comment by howardchung** [comment]
The only way to get them all is to use GetMatchHistoryBySequenceNum to import every match ever played.  However, there are 600 million+ and it will take months and use a lot of storage.

I haven't done it for YASP yet but I'm thinking about trying it in the next few months :)

**Comment by jimmydorry** [comment]
I remember the rate limit being such a stumbling block in the past. In comparison to the s1 dota profile limit of 100 a day... it was actually child's play. :baby: 

There doesn't seem to be much more we can do here, so closing.
