### ISSUE TITLE
How to reference "team" from the JSON structure passed by practiceLobbyUpdate

### ISSUE THREAD

**Issue by BlinkingRiki182** [RJacksonm1/node-dota2#225]
Really sorry if this is a dumb question but I need to reference "members" from the JSON structure passed by practiceLobbyUpdate. The structure looks like this:

{"lobby_id":{"low":-4303139,"high":5681462,"unsigned":true},"me
mbers":[{"id":{"low":163589911,"high":17825793,"unsigned":true},"hero_id":null,"
team":4,"name":"BG-Bot","slot":0,"party_id":null,"meta_level":null,"meta_xp":nul ...

For lobby_id, I have already found a solution in the closed issues which works fine:

var parsed_lobby_id = lobby.lobby_id + "";

However, when I try to reference "members" with:

var parsed_members_id = lobby.members[0].id + "";

I get a: TypeError: Cannot read property '0' of undefined

What am I doing wrong?

**Comment by jimmydorry** [comment]
Try doing a JSON.stringify() to see exactly what is happening. It's possible you are looking at the array when that value is not populated.

I'm going to hazard a guess that it would be lobby.members[0]['id'] or lobby['members'][0][''id] but I always screw up objects... leaving it to a game of trial and error.

**Comment by Crazy-Duck** [comment]
```"" + lobby.members[0].id``` should work normally. Try to put some prints in your code or step through it to see what happens

**Comment by BlinkingRiki182** [comment]
Here's my code:

> 				Dota2.on('practiceLobbyUpdate', function (lobby) {
> 					
> 					util.log(JSON.stringify(lobby));
> 
> 					var parsed_lobby_id = lobby.lobby_id + "";
> 					util.log(parsed_lobby_id);
> 
> 					var parsed_members_nicks = "" + lobby.members[0].id;
> 					util.log(parsed_members_nicks);
> 
> 				});

And here's the error.

> E:\Node-Dota2\Node-Dota2\node-dota2-master\test\test.js:238
>                                         var parsed_members_nicks = "" + lobby.me
> mbers[0].id;
> 
>         ^
> 
> TypeError: Cannot read property 'id' of undefined
>     at Dota2Client.<anonymous> (E:\Node-Dota2\Node-Dota2\node-dota2-master\test\
> test.js:238:54)
>     at emitOne (events.js:77:13)
>     at Dota2Client.emit (events.js:169:7)
>     at Dota2Client.handleSubscribedType (E:\Node-Dota2\Node-Dota2\node_modules\d
> ota2\handlers\cache.js:18:18)

I suspect that the reason for this is that the 1st lobbyUpdate object directly after creating a lobby comes with "members" being empty:

e.g.:

> {"lobby_id":{"low":513459630,"high":5681463,"unsigned":true},"m
> embers":[],"left_members":[],"leader_id":{"low":163589911,"high":17825793,"unsig...

But I may be wrong, I'm really bad at coding :)
What do you guys think?

**Comment by jimmydorry** [comment]
Well, yea... If it's not set it will crash unless you check for the value before using it.

**Comment by BlinkingRiki182** [comment]
if (lobby.members[0] != null) {
						var parsed_members_nicks = "" + lobby.members[0].id;
						util.log(parsed_members_nicks);
					}

Now it works. I'm so dumb...
Thanks guys.
