### ISSUE TITLE
How do I change the type/scope of JoinChannel from custom to the new regional channels?

### ISSUE THREAD

**Issue by dzg6** [RJacksonm1/node-dota2#226]
Question here: 
(sorry if it's in the wrong place  or tagged poorly)

In the README.md,

joinChat(channel, [type]) defines
[type] - The type of the channel being joined. 
Defaults to Dota2.schema.DOTAChatChannelType_t.DOTAChannelType_Custom.

Is there a way to change the default channel type from custom(user created)  to regional? The chat bots I make can only gain access to user created channels.

**Comment by jimmydorry** [comment]
https://github.com/RJacksonm1/node-dota2/blob/bd4eedf57075ab9d65091b77cc2b12da2cd7125d/proto/dota_gcmessages_common.proto#L943

**Comment by jimmydorry** [comment]
Feel free to re-open or make a new issue if you need further assistance.
