### ISSUE TITLE
Is there a way to join regional chat channels?

### ISSUE THREAD

**Issue by BlinkingRiki182** [RJacksonm1/node-dota2#227]
Is there a way to join regional chat channels? Requesting the channel list results in displaying only the custom channels. (Sorry for creating a new issue, a similar issue was created 8 hours ago, which I failed to see). Is there a way to request all regional channels?

**Comment by BlinkingRiki182** [comment]
I tried the following: 
Dota2.joinChat('Sofia, Bulgaria', 0);

However, instead of joining the regional channel, the bot creates a custom channel in which there are 0 people.

**Comment by jimmydorry** [comment]
Have a look at the other thread. I'm pretty sure localised chatrooms were
not type 0.

**Comment by BlinkingRiki182** [comment]
According to the dota_gcmessages_common.proto:

enum DOTAChatChannelType_t { 
 	_DOTAChannelType_Regional = 0; _
 	DOTAChannelType_Custom = 1; 
 	DOTAChannelType_Party = 2; 
 	DOTAChannelType_Lobby = 3; 
 	DOTAChannelType_Team = 4; 
 	DOTAChannelType_Guild = 5; 
 	DOTAChannelType_Fantasy = 6; 
 	DOTAChannelType_Whisper = 7; 
 	DOTAChannelType_Console = 8; 
 	DOTAChannelType_Tab = 9; 
 	DOTAChannelType_Invalid = 10; 
 	DOTAChannelType_GameAll = 11; 
 	DOTAChannelType_GameAllies = 12; 
 	DOTAChannelType_GameSpectator = 13; 
 	DOTAChannelType_GameCoaching = 14; 
 	DOTAChannelType_Cafe = 15; 
 	DOTAChannelType_CustomGame = 16; 
 	DOTAChannelType_Private = 17; 
 }

**Comment by BlinkingRiki182** [comment]
I suspect that the name should be something funky and not just "Sofia, Bulgaria". That's why I was wondering how would one obtain the list with regional channels.

**Comment by jimmydorry** [comment]
Ah, yep.

I dunno why you aren't seeing regionals.

https://github.com/RJacksonm1/node-dota2/blob/bd4eedf57075ab9d65091b77cc2b12da2cd7125d/proto/dota_gcmessages_client.proto#L1207

**Comment by BlinkingRiki182** [comment]
Executing:

> Dota2.requestChatChannels();
> 				Dota2.on('chatChannelsData', function (channels) {
> 					console.log(JSON.stringify(channels));
> 				});
> 

Returns only channels from "channel_type":1 and "channel_type":16

**Comment by Crazy-Duck** [comment]
Did you try to nethook the joinChat proto's your client sends when you join a regional chat?

**Comment by Crazy-Duck** [comment]
Also, you might want to look into this message: 
```
message CMsgDOTAChatRegionsEnabled {
	message Region {
		optional float min_latitude = 1;
		optional float max_latitude = 2;
		optional float min_longitude = 3;
		optional float max_longitude = 4;
	}

	optional bool enable_all_regions = 1;
	repeated .CMsgDOTAChatRegionsEnabled.Region enabled_regions = 2;
}
```
Seems to be implying you need to enable the regions before they'll show up?

**Comment by BlinkingRiki182** [comment]
I nethooked and analyzed the data. Everything suggests that it should work as expected:

http://s11.postimg.org/rqydss5dv/Screen1.png

**Comment by BlinkingRiki182** [comment]
It works ... God knows what I did wrong the first time. Closing issue.

**Comment by dzg6** [comment]
@BlinkingRiki182  Would you mind sharing the working code that changed the channel type to regional?

I'm also stuck on 
 Dota2.joinChat('Seattle, WA', 0); // The bot still creates a custom channel instead of joining the regional.

**Comment by BlinkingRiki182** [comment]
@dzg6 I'm totally confused myself dude. But here's how it worked for me. The second parameter of the Dota2.joinChat function has to be passed as part of an array (wtf?). I have tried with:

Dota2.joinChat('Seattle, WA', 0); // No joy
var vari = 0;
Dota2.joinChat('Seattle, WA', vari); // No joy

var arr = ["0", "0", "0"]
Dota2.joinChat('Seattle, WA', arr[1]); // It works?

Can you confirm if this works for you?

**Comment by Crazy-Duck** [comment]
Have you tried using the actual Enum itself?
I.e. Dota2.schema...

**Comment by BlinkingRiki182** [comment]
A.k.a the second parameter of the Dota2.joinChat function has to be not an integer but a string ...

**Comment by Crazy-Duck** [comment]
To avoid this type of problem I warmly recommend using the Dota2.schema.DOTAChatChannelType_t object to fetch the Enum value, especially since this makes your code independent of the actual underlying value.

**Comment by dzg6** [comment]
@BlinkingRiki182 The string tip totally works. Thank you.

@Crazy-Duck I'll look into this, thank you. I just found this git hub yesterday, everything is still very new.

**Comment by Silur** [comment]
not working nor with the '0' hack, neither with the schema lookup method, the bot still creates a new channel for itself

**Comment by Crazy-Duck** [comment]
See #445 there's a bug in chat.js for handling regional chat. It's slated for fixing somewhere this week

**Comment by ClockRide** [comment]
@BlinkingRiki182 @Crazy-Duck , again... How can i join regional chat. `Dota2.joinChat("Yoshkar Ola, Mariy-El", 0);` and `Dota2.joinChat("Yoshkar Ola, Mariy-El", 0);` don't working
