### ISSUE TITLE
Automated tests have disappeared?

### ISSUE THREAD

**Issue by Crazy-Duck** [RJacksonm1/node-dota2#228]
Where did the automated tests go? I can't seem to find them anywhere anymore...

**Comment by jimmydorry** [comment]
Good question. I hope I didn't lose them in the merge. Master was compatible with the automated test branch, so I PRed. Do you remember when they were added? I'll look through the logs if we have a rough starting point.

**Comment by jimmydorry** [comment]
Also, I've been seeing travis do build tests on PRs, if that is what I think you mean.

**Comment by Crazy-Duck** [comment]
Yeah, I saw travis doing build tests as well, but the test.js file is supposed to contain the tests that Travis should be running afaik, however it's contents seem to have been reverted to the old test file, which should've been moved to example.js, which for the moment doesn't even seem to compile anymore O_O. Did something got messed up when you restored the config.js.example file?

**Comment by jimmydorry** [comment]
I didn't restore. I'll go back and look at the merge tomorrow (yay for weekends), as that is likely where we came undone.

**Comment by Crazy-Duck** [comment]
https://github.com/RJacksonm1/node-dota2/commit/219e5729255da80c1ed73ce4f2a72f613662f6a7 this is the last commit on the correct file I could find

**Comment by Crazy-Duck** [comment]
Probably something wonky while rebasing for a merge, when I look at the history for test.js there is no trace of Rob's commits. I think easiest way to fix things will be to just copy current contents of test.js in example.js and to replace test.js with the above commit.

**Comment by jimmydorry** [comment]
I see where I did it, but like you said no history. Weird, cause this is a vanilla PR. Look in files changed.

https://github.com/RJacksonm1/node-dota2/pull/216/files

**Comment by Crazy-Duck** [comment]
Files changed list test.js and indeed the entire file is replaced with its old value

**Comment by jimmydorry** [comment]
I'll fix it tomorrow, but we haven't lost anything. Can I apply this to all branches (i.e. Dev, master and AT)?

We can have a test and example script in that folder. 

I have a feeling that somewhere in the past few months, we deleted test and renamed example... but never synced AT, which meant it was always compatible.

**Comment by jimmydorry** [comment]
Also, isn't the test useless with credentials. I recall us coming to consensus on whacking a throw away account in there. I'll do it.

**Comment by Crazy-Duck** [comment]
yeah, no problem applying to all branches (think they're pretty much in sync), it's not like it's urgent :) 
Probably an oversight somewhere, the way we've been merging these past few months it's no big surprise something gets borked occasionally. As long as it's only the tests and nothing critical I think we gucci :p

**Comment by jimmydorry** [comment]
:fire: :+1:

**Comment by howardchung** [comment]
The test uses an account that RJackson made in Travis.  It will not run
external PRs, but works for "trusted" ones.

**Comment by jimmydorry** [comment]
Fixed. This time, automated testing branch should not be compatible with Master... so we shouldn't be able to inadvertently wipe our tests.

https://github.com/RJacksonm1/node-dota2/commit/44264e9fd56903153a134cb034c13729a8f6da72
