### ISSUE TITLE
Looks like `game_mode` doesn't work

### ISSUE THREAD

**Issue by teckays** [RJacksonm1/node-dota2#230]
I'm testing with different `requestMatches()` criteria and the result is always the same no matter what `game_mode` I'm passing in

**Comment by jimmydorry** [comment]
I'll look a bit later, but it may be expecting a string, like Dota2.enum....

**Comment by jimmydorry** [comment]
https://github.com/RJacksonm1/node-dota2/blob/master/proto/dota_gcmessages_common.proto#L627

Something like Dota2.schema.DOTA_gamemode.dota_gamemode_ar

**Comment by teckays** [comment]
@jimmydorry ok, I didn't try it using built in constants, I just passed the number directly. Will test this out and'll let you know.

**Comment by teckays** [comment]
@jimmydorry I have tried the way you suggested and no luck, the results are still the same no matter what `gam_mode` I'm choosing.

**Comment by jimmydorry** [comment]
You can figure out what's happening in the client, if you run nethook to capture the communications made. It's like a wireshark, except it dumps the protobuf messages with the data, that the dota client sends via the steam client to the steam network.

Make sure to use a throw away account. The chances of a false-positive VAC detection are small, but always present. New accounts get limited in strange ways (especially around chat channels), so keep that in mind too.

https://github.com/RJacksonm1/node-dota2/issues/141#issuecomment-153578302

When you figure out what you client is sending, you will know what messages you should be sending, and the order they are required in.

**Comment by jimmydorry** [comment]
Here is our first stab at describing its usage. https://github.com/RJacksonm1/node-dota2/wiki

**Comment by jimmydorry** [comment]
You tried nethook yet? It's actually not as scary as it looks.

**Comment by jimmydorry** [comment]
Issue is very old.
