### ISSUE TITLE
Is it possible to create a 'normal' match, i.e not practice match lobby?

### ISSUE THREAD

**Issue by tomasmck** [RJacksonm1/node-dota2#236]
The createTournamentLobby request still generates a practice lobby, as it is using the CMsgPracticeLobbyCreate request.

Looking through the proto's, I'm not seeing anything relating to creating a normal or ranked match lobby.

Maybe it is possible to specify using the LobbyType enum?

**Comment by jimmydorry** [comment]
Tournament lobbies require a ticket, I believe.

You can figure out what's happening in the client, if you run nethook to capture the communications made. It's like a wireshark, except it dumps the protobuf messages with the data, that the dota client sends via the steam client to the steam network.

Make sure to use a throw away account. The chances of a false-positive VAC detection are small, but always present. New accounts get limited in strange ways (especially around chat channels), so keep that in mind too.

https://github.com/RJacksonm1/node-dota2/issues/141#issuecomment-153578302

**Comment by jimmydorry** [comment]
As a side note, I don't recall ranked lobbies ever being a thing... and normal lobbies don't ring a bell either. As far as I recall, it's Normal Games (via match making), Ranked Games (via match making), Practice Lobbies, Tournament Lobbies (attached to tickets).

**Comment by Crazy-Duck** [comment]
There exist proto messages pertaining to matchmaking (at least I recall seeing some), however none have been implemented as of yet. Seeing as we have no way to actually join/play a match, I don't really see the value in it either. You'd only be fucking over legitimate players if you were to queue...

**Comment by jimmydorry** [comment]
![GreyFace](http://dota2.photography/public/s/GreyFace.png) or no ![GreyFace](http://dota2.photography/public/s/GreyFace.png) ?

:fire:

**Comment by Crazy-Duck** [comment]
Being a nice guy and all I obviously mean to say that it wouldn't be very nice towards your team if they were to be matched with a bot who can't even join the game. I am definitely not commenting on @tomasmck 's 1337DotaSkillz, that's just a convenient implication xD

**Comment by jimmydorry** [comment]
![GreyFace](http://dota2.photography/public/s/GreyFace.png) it is. Sorry @tomasmck 

On a slightly more serious note, please re-phrase your question. What is it that you want to do?

**Comment by tomasmck** [comment]
I was intending to setup a 'normal' match for _other_ users and then leave the bot in the broadcaster slot to receive updates on the match.

**Comment by jimmydorry** [comment]
If by normal, you mean the kind that Match Making does with random people... then I don't think you can or should be able to do that.

If you mean the practice lobbies, then you should have all the functionality you need.

1. Make lobby
2. Move into broadcaster slot
3. Invite users
4. Start game
5. Listen for practiceLobbyUpdate responses. These will return in a form like http://hastebin.com/enopuliric.json where you can grab basic details. 
6. When the game ends, use the webAPI to grab the full match details.

**Comment by tomasmck** [comment]
Thanks @jimmydorry that has cleared it up for the most part. I am in the process of creating a tournament/league with Dota (it takes 15 days to process for an amateur league).

When I have this confirmed, I should be able to create a tournament lobby and follow your steps above. Does this sound right?

**Comment by jimmydorry** [comment]
Yep. Feel free to open a new issue if you have a question.

**Comment by shu1396** [comment]
Can you please recommend me the process of for getting the stats using practice match. Give me the resource or any link for the implementation in Python. 
Otherwise Please tell me the flow for implementation.
I am able to get the stats through my Python code for previous played match id of Practice match. But i'm unable to get the match id at the end of the game so that i can fetch the stats.
Please help me
