### ISSUE TITLE
Make a wiki page for using Nethook

### ISSUE THREAD

**Issue by jimmydorry** [RJacksonm1/node-dota2#238]
We should outline basic troubleshooting steps, how to get nethook, how to use it, and the expected result.

It would be way better linking to this, than other older issues.

**Comment by jimmydorry** [comment]
@imayhaveborkedit Feel free to contribute. You are one of the last people I recall using it.

**Comment by imayhaveborkedit** [comment]
I just have a .bat with this in it:
```cmd
rundll32 NetHook2.dll,Inject
pause
rundll32 NetHook2.dll,Eject
```
You had the mediafire dl link for it, but I don't remember if that came with the analyzer.  At that point its just, start dota, run the thing, do whatever you want to check out, close the thing, close dota, open the analyzer, and look through the protobuff data.

**Comment by jimmydorry** [comment]
Cheers. I certainly do. Do you think you could take a few screenshots? 

Note to self, links to include in wiki:

* https://github.com/SteamRE/SteamKit/tree/master/Resources/NetHook2
* https://www.mediafire.com/folder/0bkbp0sb0d3lf/nethook2

**Comment by imayhaveborkedit** [comment]
I'm not quite sure of exactly what I would need to visually demonstrate to people but here's this for starters I suppose: http://i.imgur.com/3MKRzef.png

**Comment by jimmydorry** [comment]
Thanks, that's good enough.

**Comment by jimmydorry** [comment]
We have a v1 up. I'll come back and improve it later.

https://github.com/RJacksonm1/node-dota2/wiki

**Comment by imayhaveborkedit** [comment]
Here's a large version with more interesting data http://i.imgur.com/SmQ666M.png
