### ISSUE TITLE
undefined returned from requestJoinableCustomGameModes();

### ISSUE THREAD

**Issue by jimmydorry** [RJacksonm1/node-dota2#242]
Reminder to check this out later. 

Had a few minutes to see if this function worked, but not enough time to spend on debugging it. 

The requestJoinableCustomGameModes() doesn't appear to return anything, regardless of the region set.

![image](http://i.imgur.com/c91N4YO.png)

The specific code I was testing: http://hastebin.com/yubacurexa.js

**Comment by Crazy-Duck** [comment]
DO YOU EVEN README :p You've got an error in your code, check the event thrown by the handler:
```
this.emit("joinableCustomGameModes", modes.game_modes);
```
There is no error handling when we emit events, it's always either a correct response or null. So your data is in your error object. If you were to use the callback, there you could actually use the callback funtion you've written, as those do always return (error, data).

**Comment by jimmydorry** [comment]
Well that was stupid of me.

I was looking at the function, and it just never clicked that the emit returns the data differently to the straight function.

https://github.com/RJacksonm1/node-dota2/blob/master/handlers/custom.js#L21

Do we have any examples of how to do the callback for methods that only have a callback parameter on the return function? Most other methods have a way of setting the callback in the request function, but requestJoinableCustomGameModes() does not.

**Comment by jimmydorry** [comment]
I was putting together a method for the top custom games message, but it's annoying as it can't be tested as there is no request message. You have to wait for the message to be sent out to all clients.

https://github.com/RJacksonm1/node-dota2/blob/master/proto/dota_gcmessages_common.proto#L555

**Comment by Crazy-Duck** [comment]
Seems like I actually borked the implementation, apparently this thing supports callbacks o_O' I'm fixing it right now, I'll make a pull for it together with a proto update

**Comment by Crazy-Duck** [comment]
#244

**Comment by Crazy-Duck** [comment]
As for the top custom game list, I've looked into that one as well when the proto was added, don't know why there isn't a request function for that one, seems messy you basically have to sit there and hope for Valve to send it out -_-'

**Comment by jimmydorry** [comment]
Yep, and thanks for the change.
