### ISSUE TITLE
requestLeaguesInMonth return no leagues

### ISSUE THREAD

**Issue by JonesN7** [RJacksonm1/node-dota2#247]
```
29 Feb 16:35:27 - Received leagues in month response 1
null
{ eresult: 1, month: 1, year: 2016, leagues: [] }
```

Should at least return the shanghai major?

**Comment by jimmydorry** [comment]
Shanghai major is february. Unless this is wanky javascript offsets at play again, I would assume that you have the wrong month.

**Comment by jimmydorry** [comment]
The function may also be out of date. Use the dev branch, and update the function to include the new tier parameter.

https://github.com/RJacksonm1/node-dota2/blob/dev/handlers/leagues.js#L6

https://github.com/RJacksonm1/node-dota2/blob/dev/proto/dota_gcmessages_client.proto#L1926

**Comment by JonesN7** [comment]
The documentation (in the readme.md) specifically noted that the month is zero-aligned, which is why I used 1 for February, month: 2 still comes up empty. I will try to use the dev branch instead.

**Comment by JonesN7** [comment]
I tried changing to the dev branch and updating the payload of 
> Dota2.Dota2Client.prototype.requestLeaguesInMonth
To include a tier attribute in the payload. I do know that according to the API the shanghai major is a tier 3, but I did try with multiple values. The callback still yield nothing in leagues, for month = 0, 1 , 2 or 3.

I'm not experienced in javascript at all, so for orientation this is the code I used. Tried to different ways to be sure.

```
Dota2.requestLeaguesInMonth(2, 2016, function(code, data) {
      console.log(data)
    } );

Dota2.requestLeaguesInMonth();
Dota2.on("leaguesInMonthData", function(a, b) {
      console.log(JSON.stringify(b))
      console.log(b)
   });

```

**Comment by jimmydorry** [comment]
Are you sure the tier is not 0, 1, 2, or 4? Also, I need to see the handler. When updating the payload, I would have added another function parameter for tier. You should also dump your code variable in the callback to the console too.

@Crazy-Duck any other ideas?

**Comment by JonesN7** [comment]
I just hard coded the tier (with different values) instead of taking in a parameter. I did try to go further in dates, and I get result for all months from before november 2015, but nothing after that. Might be something changed in tournament creation, Dota 2 reborn was fully released in september so might be connected to that?

**Comment by jimmydorry** [comment]
Weird. This is beyond my level of expertise. @Crazy-Duck may know how to proceed.

In the meantime, I would highly recommend setting up nethook and having a look at exactly what your client does and what data it send for this method.

https://github.com/RJacksonm1/node-dota2/wiki#using-nethook

If you compile it, please share an updated version. Otherwise, feel free to use the very old pre-compiled one linked in the wiki.

**Comment by JonesN7** [comment]
I'm sorry, but I am not using or have easy access to a windows machine. I can look into setting up a virtual machine if I find the time this weekend.

**Comment by Crazy-Duck** [comment]
This function has always confused me. It seems that 2015 gives okayish results, but 2016 gives nothing, no matter what parameters you enter. If I find the time, I'll try and nethook the client to see what it does. In the mean time, depending on what info you need exactly, `requestLeagueInfo()` might be of help as well.

**Comment by Crazy-Duck** [comment]
I made a PR to add support for the tier, but merging into the master might have to wait until we release 3.0.0 since it breaks retro-compatibility

**Comment by jimmydorry** [comment]
I'll push v3 into master after I add my custom games stuff. It may take a while though.

In the meantime, the above PR will be in the dev branch (very soon).

**Comment by jimmydorry** [comment]
This was probs done ages ago.
