### ISSUE TITLE
Automated tests missing from dev & master again

### ISSUE THREAD

**Issue by Crazy-Duck** [RJacksonm1/node-dota2#252]
Title pretty much. @jimmydorry could you replace the current test.js in master and dev branch with the one in the automated-testing branch so we have parity again?

**Comment by jimmydorry** [comment]
I think I did it that way as a merge safeguard to make sure that branch can't be automatically merged and broken.

**Comment by Crazy-Duck** [comment]
Oh ok, nothing to see here, move along

**Comment by jimmydorry** [comment]
I bet this creates more work than it solves, as per commit message.

https://github.com/RJacksonm1/node-dota2/commit/d2adfbee9cc744910c5ff2a168567e01cea8b039
