### ISSUE TITLE
Server IP converting

### ISSUE THREAD

**Issue by Altantur** [RJacksonm1/node-dota2#253]
Hello, I have a question about LobbyUpdate object. 
There is line about game hosted server and port like below:
**"connect": "=[A:1:665554951:6478]" ,**

It might be too noob to ask about how convert this to ipv4 address or something readable. Do I need specific table?   Thanks.

**Comment by jimmydorry** [comment]
Valve moved to a fancy routing system to make it harder to find the server IP, to prevent this. Let me google their news, as I'm pretty sure they mentioned it after all of the community outrage over DoS of tournaments.

**Comment by jimmydorry** [comment]
Look at networking section. http://www.dota2.com/reborn/part3

**Comment by jimmydorry** [comment]
And look here: http://dev.dota2.com/showthread.php?t=172553&page=2&p=1251337&viewfull=1#post1251337

Hope that helps
