### ISSUE TITLE
How do large websites like dotabuff/yasp know that a game is ended?

### ISSUE THREAD

**Issue by gerlaic** [RJacksonm1/node-dota2#254]
How do dotabuff/yasp know that a game is ended? It looks like they can grab the information as soon as the game ends. I know we can get the match detail information from the steam API but how do I know that the game is ended?

**Comment by howardchung** [comment]
Basically it doesn't show up until the game is over.

**Comment by gerlaic** [comment]
I know it doesn't show up until the game is over. But how do you know the matchID of a recent ended game?

**Comment by howardchung** [comment]
Use the sequence number API.  The match rate can be up to 20 matches a
second so make sure your application can handle it.
