### ISSUE TITLE
No replay_salt in API response

### ISSUE THREAD

**Issue by Jefftopia** [RJacksonm1/node-dota2#258]
I'm hitting the MatchDetails url from within the dota client and not receiving `replay_salt` in the response. What am I missing? 

```
        client.Dota2.once("ready", function()
        {
            console.log("Dota 2 is ready");
            steamObj[client.steamID] = client;
            
            var test = getConfig('api_details', { match_id: matchId });
            /*
            creates the following URL:
            base + "/IDOTA2Match_570/GetMatchDetails/V001/?key=" + api_key + "&match_id=" + match_id
            */
            request({   
                url: test.url,
                json: true,
                timeout: 30000
            }, function(err, res, body) { 
                fs.writeFile('data.json', JSON.stringify(body));
            });
        });
        client.Dota2.launch();
```

**Comment by jimmydorry** [comment]
That looks to be using the webAPI. The webAPI stripped that field away many years ago, after Dotabuff was using it to harvest replays. You need to be using the in-game API, that this library is built around.

**Comment by Jefftopia** [comment]
@jimmydorry Ah, that explains it - I found the appropriate requestMatchDetails method, thanks.

**Comment by jimmydorry** [comment]
No probs.

**Comment by mehdi-kaytoue** [comment]
Hey guys,
what is the in game  api you are speaking about?
Even with a limit, I'd like to download replays for which I have an id.
Thanks a lot!
Cheers,
Mehdi

**Comment by Crazy-Duck** [comment]
The ingame API is the API your Reborn client uses. Your client communicates by means of protobuf messages with Valve's game coordinator and matchmaking servers. The node JS library to which this GitHub project is dedicated is a reverse engineering of the protobuf protocol the reborn client uses. This library allows you to act as if you're a legitimate client (to a limited extent). One of the functionalities we offer is the requestMatchDetails method, which contains the replay salt. You need this salt to be able to download match replays via the official web API

**Comment by Crazy-Duck** [comment]
BTW, I'd appreciate it if you'd open a new issue when you have questions, it's considered bad form to comment on issues which have been closed months ago..

**Comment by mehdi-kaytoue** [comment]
Oh, thanks a lot! I get it now. 
Sorry for reopening!
