### ISSUE TITLE
Do I have to use node-dota2 to download replays?

### ISSUE THREAD

**Issue by gerlaic** [RJacksonm1/node-dota2#259]
Hi!

I used to use the api link to download replays. But it looks like we can't do that anymore since the match ID I received is a negative number and the absolute value of it doesn't work as well. Do I have to use node-dota2 to download replays?

**Comment by Crazy-Duck** [comment]
Are you sure it's not a parsing issue at your end? What datatype are you using to store a match ID? Match ID's are 64 bits now, so if you're using a signed 32bit integer to store them, the ID will roll over into the negatives...

**Comment by jimmydorry** [comment]
Need further information and a code example to make further comment. It's most likely that you are treating or storing the matchID as a 32bit, like @Crazy-Duck said.

**Comment by gerlaic** [comment]
Basically what I do is this:

`Dota2.requestMatchDetails(match_ID, function (err, body) {
                if (err) throw err;

                path = '../VP-root/json-data/';

                file_name = match_ID + '.json'
                fs.writeFile(path + file_name, JSON.stringify(body), function (err) {
                    if (err) throw err;
                    steamClient.disconnect();
                })`

Not sure how should I use a 64 bit integer to store them tho... since I just saved the response to a json file.

**Comment by jimmydorry** [comment]
You should treat it as a string.

http://www.javascripter.net/faq/converti.htm

http://stackoverflow.com/questions/24037751/how-to-do-64bit-integer-arithmetic-in-node-js

**Comment by gerlaic** [comment]
Ah Ok. Thanks!

**Comment by jimmydorry** [comment]
Did it work?
