### ISSUE TITLE
Is include_practice_matches invalid?

### ISSUE THREAD

**Issue by soloqi** [RJacksonm1/node-dota2#265]
message CMsgDOTAGetPlayerMatchHistory {
	optional uint32 account_id = 1;
	optional uint64 start_at_match_id = 2;
	optional uint32 matches_requested = 3;
	optional uint32 hero_id = 4;
	optional uint32 request_id = 5;
	optional bool include_practice_matches = 7;
	optional bool include_custom_games = 8;
}
I use 'include_practice_matches' want to get player's practice_matche,but is invalid.
I'd love to get answers from you guys, thanks!

**Comment by jimmydorry** [comment]
Does it work in-client? I don't recall being able to see Practice Matches... and they are definitely excluded from the WebAPI.

Go confirm you can find those kind of matches in the client first.

**Comment by Crazy-Duck** [comment]
You can retrieve them in client, but only for your own account

On 5 May 2016 1:21 p.m., jimmydorry <notifications@github.com> wrote:

Does it work in-client? I don't recall being able to see Practice Matches... and they are definitely excluded from the WebAPI.

Go confirm you can find those kind of matches in the client first.
