### ISSUE TITLE
Installation issue.

### ISSUE THREAD

**Issue by leovarmak** [RJacksonm1/node-dota2#267]
Hey
I have first cloned the the repo. Then I went in the local directory 'node-dota2' in the terminal and ran `npm install steam` and `npm install`.  Then changed the contents on the .example file and saved it as config.js and deleted the .example file.  I then went into test directory in terminal and ran `npm test.js` and I get a issue.

![node error](https://cloud.githubusercontent.com/assets/14135553/15091103/645837aa-145b-11e6-8e64-f463492368dc.jpg)

Please help me out. I am not really good at coding but I want to work on this project

**Comment by jimmydorry** [comment]
Ignore or delete test.js you want to be running example.js

**Comment by leovarmak** [comment]
![node issuetiff](https://cloud.githubusercontent.com/assets/14135553/15092492/39baa8d8-1489-11e6-90b9-12726b281bcf.jpg)
This is the error I get now. What should I do sir ?

**Comment by jimmydorry** [comment]
https://github.com/RJacksonm1/node-dota2/issues/220

**Comment by leovarmak** [comment]
Well what should be the extension of the file ? Well I am complete noob.

**Comment by jimmydorry** [comment]
No extension. Read through the script you are trying to run.

https://github.com/RJacksonm1/node-dota2/blob/master/test/example.js#L179

**Comment by leovarmak** [comment]
@jimmydorry I am getting this error `Connection closed by server` just like in the issue #220 . I check is anything is down but evrything is fine. What should I do ?

**Comment by Crazy-Duck** [comment]
@leovarmak check out the error message. It says: cannot load sentry file. This means it searches for a file with filename sentry (no extension). This file is not included when you clone the repo. It is a file which is used when you want to use an account which is protected with more than just a username + password. As issue #220 points out, all you need to do to get it running, is creating an empty file with filename "sentry" (no extension) in that directory.

**Comment by leovarmak** [comment]
@Crazy-Duck I have created that. I am talking about the issue that I am facing now after creating the file.

**Comment by Crazy-Duck** [comment]
Can you post a screen cap from what ur getting now? And your directory structure, node js version and the file you're trying to run

On 7 May 2016 8:52 p.m., Karthik Varma <notifications@github.com> wrote:

@Crazy-Duck I have created that. I am talking about the issue that I am facing now after creating the file.

**Comment by leovarmak** [comment]
This is the screenshot
![node-error](https://cloud.githubusercontent.com/assets/14135553/15095639/79c569fc-14ef-11e6-8280-57eb1f148322.jpg)

This is the path - `/Karthik/Websites/github/node-dota2/test/example.js`

Node.js version- 4.4.4

I am try to run the example.js file which is present inside the folder test

**Comment by jimmydorry** [comment]
Is the sentry file empty? Do you have the correct user credentials? Double check them by logging into the steam site. Did you sign in with no auth code, and after getting the email, then fill in the auth code?

**Comment by leovarmak** [comment]
@jimmydorry The sentry file is empty. My user credentials are correct. I have double checked them. When I run the `config.js` with no auth code I get a code on my Mobile. Then I fill in the code and saved the file. Then when I ran the `example.js` file I again I get a new auth code. This repeats. What should I do now ?

**Comment by jimmydorry** [comment]
You should just create a new account, and make sure it does not have steamguard. It's far easier if you can't figure out how to make the normal account work.

**Comment by leovarmak** [comment]
@jimmydorry I have created a new account and updated the `config.js` file. I didn't receive any steam auth code on my email but in terminal its shows logged in. Here is the screenshot.
![node-error](https://cloud.githubusercontent.com/assets/14135553/15096091/80fe9f14-1507-11e6-99a4-106aa2bb548a.jpg)
Now I guess its stuck there. Nothing is happening. What should I do now ?

**Comment by jimmydorry** [comment]
It's working. Everything else is up to you.

Look at what is in the example, and read the readme about the different functions you can use.

**Comment by jimmydorry** [comment]
Heard nothing more about this. Open another issue when you have a specific question.
