### ISSUE TITLE
Update travis node js version from 5.0 to 6.1 and 4.2 to 4.4.4

### ISSUE THREAD

**Issue by Crazy-Duck** [RJacksonm1/node-dota2#268]
Pretty much what the title says

**Comment by Crazy-Duck** [comment]
I think we can also ditch 0.12 since node-steam only supports >=4.1.1

**Comment by jimmydorry** [comment]
@RJacksonm1 All yours buddy. I have no idea how any of that magic works.

I will also take the opportunity to point out that as I said would happen (when we debated on merging the test script into the main branch), someone tried to run test script locally and didn't understand why the library did not work.

**Comment by Crazy-Duck** [comment]
about that, I think I'm gonna look into creating a simple node-module which offers a basic bot implementation class. Something like the following
```
class DotaBot {
    constructor (logonDetails, debug) {
         // handle all set-up 
    }

    init () {
        // extend this method in subclass, it is automatically called when the bot is connected to the GC
    }
```

**Comment by jimmydorry** [comment]
That would be pretty helpful.

**Comment by Crazy-Duck** [comment]
Made a start [here](https://github.com/Crazy-Duck/node-dota2-bot). I'll probably make some small tweaks like returning a promise when you don't pass a callback in the near future. I also might look into putting this on npm

**Comment by jimmydorry** [comment]
The biggest thing I see people fail to account for time and time again, is graceful handling of diconnections, GC restarts, and random timeouts. It would be a massive improvement to set an example of how to robustly handle such.

**Comment by Crazy-Duck** [comment]
I created [this](https://github.com/Crazy-Duck/node-dota2-bot/issues/1) issue to not further clutter this one since we're straying a bit away from the original subject

**Comment by howardchung** [comment]
I just checked and it doesn't appear the automated test is even running.  `package.json` doesn't have a test script.

**Comment by jimmydorry** [comment]
I blame @Crazy-Duck for that whole need to keep all branches in-sync. :fire: It was definitely not due to my ham-fisted merge.

@howardchung I'm pretty ignorant of what needs doing when it comes to travis. What should the package.json look like, and can I have it in the main branches without causing problems?

I see how to change the travis node versions, so I can change that at the same time as the package.json is fixed and hopefully resolve this issue..

**Comment by howardchung** [comment]
`package.json` should contain under `scripts` a key called `test`.

```
"test":"node test/test.js"
```

`example.js` should be moved outside since it is not test code.

All Travis does is execute whatever you define as a test.  By default, this is just `npm test`, which runs the script in package.json called `test`, which we set above.

**Comment by howardchung** [comment]
It also looks like the test for requestMatchDetails that I added got lost:

https://github.com/RJacksonm1/node-dota2/commit/7ac07173b3808a15354cfa89053e010c3f06af90

**Comment by Crazy-Duck** [comment]
This is why I didn't like the whole different unsynchronized branches shenanigans :p 
We might wanna create a separate folder for the examples honestly, so we don't clutter the root too much.

**Comment by jimmydorry** [comment]
Yea, already working on it. https://github.com/RJacksonm1/node-dota2/pull/275

Will ping you in there in a few secs, when it's ready.

**Comment by jimmydorry** [comment]
Thanks for pointing this out @howardchung

**Comment by Crazy-Duck** [comment]
Seems like you messed up somewhere, Travis is haemorrhaging
https://travis-ci.org/RJacksonm1/node-dota2

**Comment by jimmydorry** [comment]
Probably from versioning syntax. Didn't know it had to be x.x.x and not x.x

**Comment by howardchung** [comment]
This can go in master.

**Comment by howardchung** [comment]
It looks like there's a problem with test.js though:

https://travis-ci.org/RJacksonm1/node-dota2/jobs/133879728

**Comment by Crazy-Duck** [comment]
Seems like we're missing another proto file, the enum doesn't seem to exist anymore.. What's worse is the entire EDOTAGCMsg subschema is gone from the protos we host. Gonna see if I can find where they've put it.

**Comment by jimmydorry** [comment]
Might be easier to just dump them all in there, and pare it back.

**Comment by Crazy-Duck** [comment]
gottem dota_gcmessages_msgid.proto

**Comment by Crazy-Duck** [comment]
I'll make a pull

**Comment by jimmydorry** [comment]
![image](http://i.imgur.com/deMoVu6.png)

**Comment by Crazy-Duck** [comment]
Rofl, I'm testing everything in example.js to see if we've missed some other stuff. Valve seems to have been sick of their ginormous proto files and started to repartition everything in separate files by subject :p

**Comment by Crazy-Duck** [comment]
Seems like we'll have to redo most of team.js. All protomessages except  for CMsgDOTAProTeamListRequest have disappeared

**Comment by Crazy-Duck** [comment]
LOL, why didn't we notice this sooner :p k_EMsgClientToGCAddTI6TreeProgress

**Comment by jimmydorry** [comment]
>_<

**Comment by Crazy-Duck** [comment]
ROFL, no serverside validation whatsoever
```
message CMsgClientToGCAddTI6TreeProgress {
	optional uint32 trees = 1;
}
```
Challenge could've been over in 10m :p

**Comment by jimmydorry** [comment]
It's a button just waiting to be pressed.

**Comment by jimmydorry** [comment]
Fire = fought :fire: :fire_engine: :fireworks:
