### ISSUE TITLE
CMsgPassportDataRequest no longer seems to exist

### ISSUE THREAD

**Issue by Crazy-Duck** [RJacksonm1/node-dota2#272]
requestPassportData will no longer work since the corresponding protobuf seems to have disappeared.  We might want to look into adding a deprecated tag in the README/source doc, or removing it all together

**Comment by Crazy-Duck** [comment]
Added some notes in #273, think most of our stuff should work now

**Comment by jimmydorry** [comment]
Marking it as no-longer working is probably the better option than removing it. People would be able to see why things they were using, no longer work. :+1:
