### ISSUE TITLE
requestProTeamList down

### ISSUE THREAD

**Issue by Crazy-Duck** [RJacksonm1/node-dota2#279]
Issue for posterity

Writing tests, `CMsgDOTAProTeamListRequest` no longer gets a response from GC.
Adding comment to README

**Comment by jimmydorry** [comment]
That was a quick turn around! :smile:

**Comment by Crazy-Duck** [comment]
Yeah I immediately closed it since it's no use leaving it open. I just created it so there'd be a trace in the issues in case someone shows up asking questions :) I'm preparing a pull with some README modifications indicating the stuff that no longer works and the stuff for which the proto's have disappeared. I'm commenting all functions for which the protos are gone and adding comments to all those that still have protos but don't receive responses anymore. I'll also be adding some more tests and elaborating the existing ones so we'll be able to detect this stuff more easily in the future

**Comment by jimmydorry** [comment]
I'm just joshing you. :P
