### ISSUE TITLE
Human player stuck in invisible bot's lobby

### ISSUE THREAD

**Issue by ZiRoger** [RJacksonm1/node-dota2#286]
Bot can create the lobby and invite human player. But once the player accepted the invitation, he could see no lobby detail  window but a "back to lobby" button in the lower right corner. And clicking it wounldn't pop the lobby window either. The player would stuck in this state, only a force_leave_game_button in console could help. Is this a bug or only my config error? Need help, thanks.

**Comment by Crazy-Duck** [comment]
It would be helpful if you'd provide us with the code you're using to set up and configure the lobby... 

On 13 Jun 2016 4:24 p.m., Roger <notifications@github.com> wrote:

Bot can create the lobby and invite human player. But once the player accepted the invitation, he could see no lobby detail window but a "back to lobby" button in the lower right corner. And clicking it wounldn't pop the lobby window either. And the player would stuck in this state, only a force_leave_game_button in console could help. Is this a bug or only my config error? Need help, thanks.

**Comment by ZiRoger** [comment]
Basically, I just ran the example2.js in dev branch, and added an inviting function call.
```
           var creatingLobby = 1;
           var leavingLobby = 0;

            if(creatingLobby == 1){ // sets only password, nothing more
                var lobbyPassword = "ap";
                var lobbyName = "Lobby Name";

                Dota2.createPracticeLobby(lobbyPassword, lobbyName, function(err, data){
                    util.log(JSON.stringify(data));
                    Dota2.inviteToLobby("7656119********");
                });
            }
```

**Comment by Crazy-Duck** [comment]
Hmm, can you try and pass some additional options? So instead of lobbyName, pass an object like this one
```
{
        "game_name": "MyLobby",
        "server_region": 3,
        "game_mode": 2,
        "series_type": 2,
        "game_version": 1,
        "allow_cheats": false,
        "fill_with_bots": false,
        "allow_spectating": true,
        "pass_key": lobbyPassword,
        "radiant_series_wins": 0,
        "dire_series_wins": 0,
        "allchat": true
    }
```
It might be that there's a minimum amount of options that need to be set in order for a player to be able to actually join...

**Comment by ZiRoger** [comment]
@Crazy-Duck It works! Thanks a lot. By the way, the example2.js should be updated a bit.

**Comment by Crazy-Duck** [comment]
Did you check which options are required and which ones are optional? If not I'll look into making a pull with an update that contains the entire object.

**Comment by ZiRoger** [comment]
So sorry that I didn't check which options are necessary. I am now busy on making my bot just working.

**Comment by Crazy-Duck** [comment]
eh, don't sweat, I'm sure we'll know some day :p
