### ISSUE TITLE
Request to add to npm

### ISSUE THREAD

**Issue by ammuench** [RJacksonm1/node-dota2#287]
Hey, love the work you guys have done.  Just wondering if you'll be adding your repo to NPM any time soon?  We've been working on some projects with it and it'd be helpful for us going forward (we've just been using the direct git link format in the meantime)!

Thanks!

**Comment by pendo324** [comment]
@ammuench I might not be who you want to hear from, but here it is on npm: https://www.npmjs.com/package/dota2

**Comment by ammuench** [comment]
Yep, I completely whiffed that.  Need some more coffee this afternoon, haha.  Sorry guys, thanks for the help

**Comment by pendo324** [comment]
@ammuench haha, not a problem man. I was a bit surprised the first time, when I learned it was just "dota2" on npm.

**Comment by Crazy-Duck** [comment]
Be careful, npm is not yet up to speed with git. If I recall correctly it's on 3.x.x while git is at 4.x.x we'll do a new push in the coming days/weeks as soon as we got some last things ironed out

On 15 Jun 2016 10:49 p.m., Alex Muench <notifications@github.com> wrote:

Closed #287.

**Comment by pendo324** [comment]
@Crazy-Duck It looks like rjackson published 4.0.0 to npm 2 weeks ago

**Comment by Crazy-Duck** [comment]
Huh, TIL. Hadn't noticed it yet. In any case, there's some stuff that's been added in the mean time. It's mostly tests, but we've had to deprecate a few functions since Volvo stopped supporting them
