### ISSUE TITLE
Bot-hosted lobby results in all members being in same voice channel

### ISSUE THREAD

**Issue by JayFialkowski** [RJacksonm1/node-dota2#292]
Any lobby hosted via the bot results in all players and broadcasters being on the same voice channel in-game, and hearing each other. Obviously, this is bad. What could possibly be causing this?

Below is an example Lobby snapshot

> [ { id: Long { low: 350788683, high: 17825793, unsigned: true },
    hero_id: null,
    team: 4,
    name: 'Bot',
    slot: 0,
    party_id: null,
    meta_level: null,
    meta_xp: null,
    meta_xp_awarded: null,
    leaver_status: 1,
    leaver_actions: null,
    channel: 6,
    prize_def_index: null,
    disabled_hero_id: [],
    partner_account_type: 0,
    enabled_hero_id: [],
    coach_team: 5,
    nexon_pc_bang_no: null,
    nexon_pc_bang_name: null,
    xp_bonuses: [],
    rank_change: null,
    cameraman: false,
    custom_game_product_ids: [],
    lobby_mvp_vote_account_id: null,
    search_match_type: 0 },
  { id: Long { low: 165903706, high: 17825793, unsigned: true },
    hero_id: null,
    team: 0,
    name: 'jasus',
    slot: 1,
    party_id: null,
    meta_level: null,
    meta_xp: null,
    meta_xp_awarded: null,
    leaver_status: 1,
    leaver_actions: null,
    channel: 6,
    prize_def_index: null,
    disabled_hero_id: [],
    partner_account_type: 0,
    enabled_hero_id: [],
    coach_team: 5,
    nexon_pc_bang_no: null,
    nexon_pc_bang_name: null,
    xp_bonuses: [],
    rank_change: null,
    cameraman: false,
    custom_game_product_ids: [],
    lobby_mvp_vote_account_id: null,
    search_match_type: 0 } ]

**Comment by Crazy-Duck** [comment]
That seems weird (and weirdly interesting)... Can you post the steps you take to create the lobby, how the players join (are they bots too or real client), if possible with code samples?

**Comment by JayFialkowski** [comment]
I'll do my best to share the relevant bits. The bot is controlled remotely via Discord.

User creates a lobby via command in discord. That executes:

`
Dota2.createPracticeLobby(password,options,
			function(err, body){
				if (body && body['result'] == 1) {
					Dota2.joinPracticeLobbyTeam();
					Dota2.joinChat("Lobby_"+Dota2.Lobby.lobby_id,3);
					success();
				}
				else {
					console.log(err);
					failure();
				}
			});
`

options looks like:
>{ game_name: 'title',
  server_region: 0,
  game_mode: 2,
  league_id: 4570,
  series_type: 1,
  allow_cheats: false,
  fill_with_bots: false,
  allow_spectating: true,
  pass_key: 'pass',
  cm_pick: 0,
  radiant_series_wins: 0,
  dire_series_wins: 0,
  allchat: true }

Some settings are modified remotely as well. I don't think that would impact anything, all it does is change some of the above. Users were all real users, in client. I tried a few test lobbies with just the bot, myself and someone in the broadcaster slot. As a player, the broadcaster and I can hear each other. This happens every time. If I host a lobby myself in-client, it does not happen.

Not sure what else I can share with you that might be relevant.

**Comment by JayFialkowski** [comment]
Here are two logs of the lobby object, before and after launching the game. There's one person as a broadcaster, one on radiant and one on dire. The bot is in spectators. All users can hear each other in game.

https://gist.github.com/JayFialkowski/abffa74fccbbf8f6d1670c6d963ec5dd

**Comment by jimmydorry** [comment]
Have you tried allchat: false?

**Comment by Crazy-Duck** [comment]
Alright, let's look at the lobby log:
* SatanBot
 * team: 4
 * channel: 6
* Jasus
 * team: 2
 * channel: 0
* Soranos
 * team: 1
 * channel: 6
* Moxxi
 * team: 0
 * channel: 6

So there's a few things we can see here: 
* Your bot is in the player pool, not in a spectator slot (is confirmed by `num_spectators: null`)
* Everyone except for the broadcaster seems to be in channel 6

The fact that everyone seems to be in channel 6 might have something to do with it.. Thing is I've no idea why they are all in the same channel or if this is normal or not.. Have you tried creating the lobby yourself, loading in the same people and comparing the lobby updates?

```
enum DOTA_GC_TEAM {
	DOTA_GC_TEAM_GOOD_GUYS = 0;
	DOTA_GC_TEAM_BAD_GUYS = 1;
	DOTA_GC_TEAM_BROADCASTER = 2;
	DOTA_GC_TEAM_SPECTATOR = 3;
	DOTA_GC_TEAM_PLAYER_POOL = 4;
	DOTA_GC_TEAM_NOTEAM = 5;
}
```

**Comment by Crazy-Duck** [comment]
@paralin you've got some experience creating lobbies if I recall correctly, have you ever seen this problem?

**Comment by jimmydorry** [comment]
Channel is to do with allchat, I believe. Something you have set to true.

**Comment by JayFialkowski** [comment]
Yeah guys, apparently the allchat doesn't do what I assumed it did. This was a developer error, thanks for your time!

**Comment by jimmydorry** [comment]
@Crazy-Duck lol, every duck must have it's day. I totally called it.

**Comment by Crazy-Duck** [comment]
Congrats :p I'm gonna add a comment in the README at one point though, this seems like something useful to add. It's a nice touch, gives a whole new dimension to the world of bm xD

**Comment by jimmydorry** [comment]
I only recall it due to the way d2ware custom game lobbies worked, where by default, everyone was voicing each other.
