### ISSUE TITLE
Chat command

### ISSUE THREAD

**Issue by salacryl** [RJacksonm1/node-dota2#302]
Hi,

besides sendMessage I can't find any function to use things like "/privatechatkick". If I use sendMessage it only appears in the chat without invoking the command itself.

Any Ideas?

Greetings,
Björn

**Comment by Crazy-Duck** [comment]
I think you've got the wrong idea of how chat works in Dota 2. Check out handlers/chat.js, that's where all the magic is happening. Basically, when you invoke sendMessage, you're basically doing just that: sending a text message. At this time the only chat functions we've implemented are:
* `CMsgDOTAJoinChatChannel`
* `CMsgDOTALeaveChatChannel`
* `CMsgDOTAChatMessage`
  * sending text
  * sharing a lobby
  * flipping a coin
  * rolling dice
The protobufs interacting with private chat channels have yet to be implemented in this library. I've listed the relevant parts at the end of this comment. If you really need this functionality, feel free to make a pull request to the staging branch. Implementing new proto messages is pretty straightforward (just take a look at some of the others), you just need to write a wrapper function for outgoing messages and a handler to treat the responses
```
message CMsgClientToGCPrivateChatInvite {
	optional string private_chat_channel_name = 1;
	optional uint32 invited_account_id = 2;
}

message CMsgClientToGCPrivateChatKick {
	optional string private_chat_channel_name = 1;
	optional uint32 kick_account_id = 2;
}

message CMsgClientToGCPrivateChatPromote {
	optional string private_chat_channel_name = 1;
	optional uint32 promote_account_id = 2;
}

message CMsgClientToGCPrivateChatDemote {
	optional string private_chat_channel_name = 1;
	optional uint32 demote_account_id = 2;
}

message CMsgGCToClientPrivateChatResponse {
	enum Result {
		SUCCESS = 0;
		FAILURE_CREATION_LOCK = 1;
		FAILURE_SQL_TRANSACTION = 2;
		FAILURE_SDO_LOAD = 3;
		FAILURE_NO_PERMISSION = 4;
		FAILURE_ALREADY_MEMBER = 5;
		FAILURE_NOT_A_MEMBER = 7;
		FAILURE_NO_REMAINING_ADMINS = 8;
		FAILURE_NO_ROOM = 9;
		FAILURE_CREATION_RATE_LIMITED = 10;
		FAILURE_UNKNOWN_CHANNEL_NAME = 11;
		FAILURE_UNKNOWN_USER = 12;
		FAILURE_UNKNOWN_ERROR = 13;
		FAILURE_CANNOT_KICK_ADMIN = 14;
		FAILURE_ALREADY_ADMIN = 15;
	}

	optional string private_chat_channel_name = 1;
	optional .CMsgGCToClientPrivateChatResponse.Result result = 2 [default = SUCCESS];
	optional string username = 3;
}

message CMsgClientToGCPrivateChatInfoRequest {
	optional string private_chat_channel_name = 1;
}

message CMsgGCToClientPrivateChatInfoResponse {
	message Member {
		optional uint32 account_id = 1;
		optional string name = 2;
		optional uint32 status = 3;
	}

	optional string private_chat_channel_name = 1;
	repeated .CMsgGCToClientPrivateChatInfoResponse.Member members = 2;
	optional uint32 creator = 3;
	optional uint32 creation_date = 4;
}
```

**Comment by salacryl** [comment]
Yes I'm even further now. I compiled Nethook2 to translate the eMsg and  to extend your code. 
Thanks for the Input.

**Comment by Crazy-Duck** [comment]
These are the corresponding eMsg types:
```
	k_EMsgClientToGCPrivateChatInvite = 8084;
	k_EMsgClientToGCPrivateChatKick = 8088;
	k_EMsgClientToGCPrivateChatPromote = 8089;
	k_EMsgClientToGCPrivateChatDemote = 8090;
	k_EMsgGCToClientPrivateChatResponse = 8091;
	k_EMsgClientToGCPrivateChatInfoRequest = 8092;
	k_EMsgGCToClientPrivateChatInfoResponse = 8093;
```

**Comment by salacryl** [comment]
@Crazy-Duck Ty, THIS was really helpful.
Good work with the prototypes. Easy Implementation for me. Worked - as you mentioned - pretty sraight forward.

Greetings,
Björn

**Comment by Crazy-Duck** [comment]
Don't forget to make a PR :D

**Comment by salacryl** [comment]
PR is out :)
