### ISSUE TITLE
Requestmatches only obtains very short matches

### ISSUE THREAD

**Issue by niliur** [RJacksonm1/node-dota2#313]
I'm building a bot that will download the replays of the most recent games in the GC. So far I'm able to get the match ID using requestmatches and download them by getting the match details using the http://replay<cluster>.valve.net/570/<match_id>_<replay_salt>.dem.bz2 link. However all the replays I've downloaded using this method end in less than a few minutes due to someone disconnecting in game (I've tried with ~90 replays). Is this just a coincidence or something wrong with my parameters? 

I'm currently using this method to get my matchIDs:
`Dota2.requestMatches( { "matches_requested": 25,"min_players": 10},matchescallback);`

If someone could give me some tips on why this is happening or parameters I can use to get longer game replays that would be greatly appreciated.

**Comment by jimmydorry** [comment]
You probably want to be using the webAPI to find matches to download. 

Match IDs are created at the start of the game, and as you can imagine, this means that longer running games get buried when they finally report they are done.

 There is a webAPI method for getting matches in sequence, rather than by finishing time. `GetMatchHistoryBySequenceNum`

http://dev.dota2.com/showthread.php?t=58317

**Comment by niliur** [comment]
Thanks, that explains why the replays always end very quickly. 

I'm not sure if this is the right place to ask about the webapi, but after making the call I receive matchids that are only 3 digits long, seems like either they are not allowing people to find the matchid this way or I've done something wrong. 

```
				"radiant_win": false,
				"duration": 2408,
				"pre_game_duration": 0,
				"start_time": 1299121489,
				"match_id": 496,   <---
				"match_seq_num": 240,
```

**Comment by niliur** [comment]
Update: I was able to get actual match_ids by using the dota 2 beta test api instead of the beta api. 

Wonder why that made a difference.

```
				 "radiant_win": false,
				"duration": 2144,
				"pre_game_duration": 90,
				"start_time": 1468274403,
				"match_id": 6219227, <----
				"match_seq_num": 50,
```

**Comment by niliur** [comment]
Thanks for your help Jimmydorry, I was able to figure it out and get my replays! Disregard the posts that I deleted, after figuring it out I felt quite silly.. Your guide was very helpful, thanks for helping out a newbie.
