### ISSUE TITLE
Search function is really bad

### ISSUE THREAD

**Issue by leovarmak** [RJacksonm1/node-dota2#316]
Hey !

The search function is really bad. I don't mean to be rude tho. I respect you people. I tried to search my account in many ways and I always end up with  **NOT FOUND** . Haha .
Well my game profile is "Amanda Rosset" . I did a series of queries to test it. Here are pics

![screen shot 2016-07-20 at 6 23 11 pm](https://cloud.githubusercontent.com/assets/14135553/16987344/512ac20a-4ea9-11e6-836d-a46d1eca8d01.png)
![screen shot 2016-07-20 at 6 23 21 pm](https://cloud.githubusercontent.com/assets/14135553/16987349/54d0ab72-4ea9-11e6-88db-6abd2de803e4.png)
![screen shot 2016-07-20 at 6 23 32 pm](https://cloud.githubusercontent.com/assets/14135553/16987351/57c4b30a-4ea9-11e6-8831-035900c72e7e.png)
![screen shot 2016-07-20 at 6 23 46 pm](https://cloud.githubusercontent.com/assets/14135553/16987355/59eaf2b6-4ea9-11e6-945c-5523d1a81706.png)
![screen shot 2016-07-20 at 6 23 53 pm](https://cloud.githubusercontent.com/assets/14135553/16987358/5c63efac-4ea9-11e6-9603-f040281ec2e9.png)
![screen shot 2016-07-20 at 6 24 09 pm](https://cloud.githubusercontent.com/assets/14135553/16987361/5e807b8e-4ea9-11e6-99ea-62002d5ed674.png)

But when I type in **rosset** my profile shows up

So whats wrong ?

**Comment by Crazy-Duck** [comment]
Well, the main thing that's wrong is that you're posting your issue in the wrong repository :D The people over at Yasp are well-esteemed colleagues who hang out here from time to time, however, this is just the repo for one of the many libraries they use within the Yasp ecosystem. I'm afraid there's very little we here at node-dota2 can do for you. You're asking the farmer to change the way the baker bakes his bread. If you have a problem with Yasp, I propose that you head over to the [yasp repository](https://github.com/yasp-dota/yasp) :)

**Comment by leovarmak** [comment]
@Crazy-Duck I actually wanted to comment on the recent value decision in the open issue. So somewhere I mixed up the tabs and ended up here. Sorry ! 
such and awkward situation xD

**Comment by Crazy-Duck** [comment]
no problem, everyone messes up from time to time :p you're always welcome to contribute to the library if you'd be so inclined, we're always looking for contributors :D
