### ISSUE TITLE
32 bit ID inaccuracies

### ISSUE THREAD

**Issue by paralin** [RJacksonm1/node-dota2#32]
The method I wrote into the latest version of the package for converting SteamID to 32 bit for Dota 2 might be incorrect. Here's what I'm currently using (kind of hacky)

```
@toSteamID32 = (id)->
     sids = (steamidconvert.convertToText id).split ":"
     id = parseInt sids[2]
     id*(2+parseInt(sids[1]))+1
```

This works with SteamTracks' backend. I think this solution might need to be integrated into this package.

**Comment by RJacksonm1** [comment]
Fixed by #66.
