### ISSUE TITLE
2FA Support

### ISSUE THREAD

**Issue by Noxville** [RJacksonm1/node-dota2#320]
Hey, currently getting SteamError #85 AccountLoginDeniedNeedTwoFactor.

I was wondering if there was an easy way to configure this for one-off connections (so, you type the code into your config.js file and execute it). Unsure really at what level to try solve this.

**Comment by Crazy-Duck** [comment]
As far as I know you need to run the log-on process twice, while making sure you have an empty sentry file present before you start running. The first time you log in to trigger the steamguard code generation, the second time you can login with the steamguard code as an entry in your config.js. At that point a sentry-hash will be written to the sentry file for future usage and you can remove the steamguard code again. So the first time your config.js would look like this:
```
var config = {};

config.steam_name = "mySteamName";
config.steam_user = "mySteamUserName";
config.steam_pass = "mySteamPassword";
config.steam_guard_code = "";

module.exports = config;
```
And for the second login you'd fill out the steamguard code between the quotes.

**Comment by Noxville** [comment]
Yeah I've followed that process before, it's not applicable since the introduction of 2FA via mobile app.

https://github.com/seishun/node-steam/wiki/Protobufs#cmsgclientlogon documents the log on details definition and as a result how you can add an additional field (which you could add to the config, but would need to also add to pass to steamUser.logOn(details).

var logOnDetails = {
    "account_name": global.config.steam_user,
    "password": global.config.steam_pass,
    "two_factor_code": "blah"
};

This is a bit tedious since you need to adjust it each execution - but works fine.

**Comment by Crazy-Duck** [comment]
There is unfortunately no way around the tediousness of having to specify this each execution, since this is the core purpose of that second factor; it pretty much NEEDS to be different on each login. We usually recommend using dummy throwaway accounts without 2FA/steamguard when you're in development/test and only to switch to 2FA for the actual always-online production runs.

**Comment by Noxville** [comment]
Yeah I understand, no problem. 

Unfortunately I'm writing something that needs my current account (Fantasy Cards) so no other way around.

**Comment by Crazy-Duck** [comment]
In that case there is indeed no way around it :) 

*Disclaimer*
I'm gonna assume that you're experienced enough to understand the risks of using your own account in conjunction with this library, however for the potentially less experienced users who might one day stumble upon this issue: _we do not in any way encourage people to use their own accounts when using this library_. This library tries to mimic the behavior of the Dota 2 client to allow people to programmatically interact with the Dota 2 GC, however we make no efforts to hide this fact and it's pretty easy for Valve to detect clients using this library based on the generated traffic. While Valve has not yet expressed a dislike regarding reverse engineering projects like this one, it's not unimaginable that this might one day change and result in VAC bans.

**Comment by Noxville** [comment]
Slightly off-topic, but would you mind giving me a hand with some code I'm writing? Unsure the best way to contact you and there's no #node-dota2 IRC group or something.

**Comment by howardchung** [comment]
@Crazy-Duck  that disclaimer is worth a section in the README :)

**Comment by Crazy-Duck** [comment]
@noxville send me a mail : jobuyse [at] gmail

@howard I'll add it when I make the pull for the contribution.md 😊
