### ISSUE TITLE
How to fetch the MMR for solo and party?

### ISSUE THREAD

**Issue by maximski** [RJacksonm1/node-dota2#52]
How exactly would i fetch the Dota 2 MMR for solo and party games with this wrapper?

**Comment by CoericK** [comment]
You can't at the moment.

**Comment by maximski** [comment]
I am not talking about the Dota 2 Web API, it's about this node-dota2 plugin. Also, SteamKit does seem to be able to fetch it: https://github.com/SteamRE/SteamKit/search?utf8=%E2%9C%93&q=mmr

Besides that, SteamTracks (https://steamtracks.com/about) seems to use this plugin and node-steam, so I guess it must be possible somehow.

**Comment by imayhaveborkedit** [comment]
MMR is returned with `profileRequest()` under `gameAccountClient` as `soloCompetitiveRank` and `competitiveRank`, but only if the requested account is on the bot's friends list.

**Comment by maximski** [comment]
Perfect, thank you!
