### ISSUE TITLE
Handling party invites

### ISSUE THREAD

**Issue by kallisti-dev** [RJacksonm1/node-dota2#54]
So I was looking through the steamkit protobufs for a command to automate party invites (either through a guild or through friends), but I couldn't find anything related to that. Any idea if this is possible? If you could point me in the direction of the relevant protobufs, I could probably add the functionality to this package.

**Comment by paralin** [comment]
I figured out everything regarding parties. If you'd like to implement it in node-dota2 and submit a PR I'd appreciate it. I have it implemented in my fork of SteamKit c#, 

Here's the blog post on how to interact with parties: http://blog.paral.in/dota-2-party-system/

**Comment by RJacksonm1** [comment]
Fixed by #66.
