### ISSUE TITLE
Event for ended matches of friends?

### ISSUE THREAD

**Issue by maximski** [RJacksonm1/node-dota2#55]
Is there any way to know when a friend of the bot finished a match?

**Comment by paralin** [comment]
This is possible by looking at the RichPresence data of a friend. The api has not been implemented into this package yet. I'll build it into http://github.com/paralin/dota2 and then port it over here.

**Comment by maximski** [comment]
Alright, can't wait for it :+1:

**Comment by paralin** [comment]
Can you put an issue on http://github.com/paralin/Dota2 about this?

**Comment by maximski** [comment]
Sure!

**Comment by howardchung** [comment]
@paralin any progress here?

I think but am not sure that Valve removed the RichPresence stuff a while ago.  Considering that Reborn gives you even more data about what your friend is doing (the party they're in), it's probably possible to get it, though.

I don't think this needs to go 1.0.0 though.

**Comment by jimmydorry** [comment]
No one apparently cares about this. Closed until it finds a new sponsor.
