### ISSUE TITLE
SourceTV address

### ISSUE THREAD

**Issue by uSide** [RJacksonm1/node-dota2#57]
I receive "connect" field when launch practice lobby. I think it contains game address. Anyone knows how I can get source tv address to view this game as spectator?

**Comment by uSide** [comment]
However, i think that's impossible. Can I join to game as spectator? I really need record a demo files for games which i create

**Comment by SimpleCold** [comment]
Yes of course you can.
If DotaTV is enabled, tv_status console command will give you the info you need.

**Comment by l419351633** [comment]
You can get the game id when launch the lobby, and get the replay by it.

**Comment by uSide** [comment]
But this is private game and I doubt that Valve will save replay for it

**Comment by paralin** [comment]
Run watch_server "server id" where the server ID is the steam3 ID of the server. 

Joining and parsing in realtime as a spectator hasn't been done successfully in a few months afaik

**Comment by uSide** [comment]
In original idea I want save a replay, but spectator receives not all of events
