### ISSUE TITLE
Interprets all cache subscriptions as lobby IDs

### ISSUE THREAD

**Issue by paralin** [RJacksonm1/node-dota2#61]
I didn't know as much as I do now about the internal lobby system when I wrote the node-dota2 lobby handlers. I need to go back in and refactor everything with new knowledge I have from building a c# implementation of a full dota2 lobby and party client.

http://blog.paral.in/dota-2-party-system/

There is some info on the party system.

The cache subscriptions come for several things, including parties, party invites, lobbies, and matchmaking. Each has a different ID. I believe lobbies are id 4.

**Comment by RJacksonm1** [comment]
Fixed with #66.
