### ISSUE TITLE
profileRequest() entering callback only on few users

### ISSUE THREAD

**Issue by maximski** [RJacksonm1/node-dota2#62]
I have around 50 users in my database and somehow I was able to collect the MMR of ~15 of them. "Somehow", because my profileRequest() will enter the callback only on 4 or 5 of them at a time. I can't figure out when and why the callback is called on someone and when and why not. Am I missing something?

**Update:** I feel like there is a limitation for profileRequests by the Steam servers. If I request the profile for X Steam IDs at once I will only get answered the first 5 ones. Also, after a time, I won't get an answer for any request at all. Did anyone else face this issue?

**Comment by jimmydorry** [comment]
Yes, they have a rate limit. There is a hard limit of about 100 profiles per day per account per IP, and a softer one.

Welcome to node-dota2. There is nothing you can do but work around it.

**Comment by maximski** [comment]
Can you tell me about the softer one? Or show me a resource about it?

Which other approaches could there be? I wonder how Dotabuff can perform so many MMR request with their new Rating Buddy.

**Comment by jimmydorry** [comment]
There are no resources for it, for the exact reason why you want the resource (to circumvent it).

Dotabuff works around it, in the exact way you will have to if you wish to use this library in that way.

**Comment by maximski** [comment]
So you found out the hard way? :D Anyway, I will try to see how I can approach this issue best otherwise. Can you still tell me about the soft limit? :)

**Comment by jimmydorry** [comment]
I don't want to be the one that sees this project terminated by Valve, for actively aiding people in circumventing restrictions that have been clearly set. You will just need to figure it out the hard way.

I have already given the approximate hard limit.

:fist:

**Comment by lockebr** [comment]
Hi jimmydorry, I know you don´t want to go into details but...
Is there a way to check if the limit was reached? Or do we have to simply use this approximate hard limit?

**Comment by RJacksonm1** [comment]
The only way to know is if the GC stops responding to your requests.  I'm
not aware of there being sent facility in the GC to check whether you have
or haven't surpassed their limits.

For my own projects I just kept a track of requests in my application, and
didn't allow any single node-dota2 instance (I had a cluster to work around
this limit) to send more than 100 requests in a rolling 24hr period. This
was with match detail requests though, I'm not sure what the limit is on
profile requests.

**Comment by lockebr** [comment]
Thank you, sometimes i can get 120 or 130 requests... But I will limit to 100. Thank you so much.
