### ISSUE TITLE
DOTA GC Never sending welcome message

### ISSUE THREAD

**Issue by paralin** [RJacksonm1/node-dota2#63]
I just ran into this issue... The GC never responds with welcome, it's just stuck on sending "ClientHello" over and over.

**Comment by paralin** [comment]
This probably isn't a node-dota2 bug but just Valve saying "no" to the bot.

**Comment by jimmydorry** [comment]
It sounds like an unintended behaviour that can be handled in the library. I assumed by posting this here, you were making note of this behaviour in the expectation that the library would be updated to better handle it. 

Let me know if I miss-interpreted this.

**Comment by paralin** [comment]
That was my intention, yes. We need to more elegantly handle this than spamming ClientHello I think

**Comment by paralin** [comment]
In my fork I just fire a hello timeout whenever this happens.

Can we do some testing to see what causes this and if it's possible to get around it?

**Comment by RJacksonm1** [comment]
Done with #66.
