### ISSUE TITLE
Hello, I have a question!

### ISSUE THREAD

**Issue by SimpleCold** [RJacksonm1/node-dota2#64]
Is it possible to use node-d2 to force a "Create Lobby" non-local(!) lobby to join my dedicated server with a custom gamemode?
Because sv_search_key does not work for me, maybe because the game is searching for AP , and on the server it is 15, Custom game.

**Comment by paralin** [comment]
This is possible through some incredibly complex trickery with some things we haven't yet finished reverse engineering let alone implementing a library for. It'll require a significant amount of work.
