### ISSUE TITLE
Adding support to get the match history for a player

### ISSUE THREAD

**Issue by zettelmj** [RJacksonm1/node-dota2#69]
Hi, 

i'm currently adding support to get the Match History for a player. Since it is working for my usecase i wanted to contribute the changes back. That is where it starts to get more interesting:
What is your approach on having multiple parameters? CMsgDOTAGetPlayerMatchHistory has a lot of parameters:

message CMsgDOTAGetPlayerMatchHistory {
	optional uint32 account_id = 1;
	optional uint32 start_at_match_id = 2;
	optional uint32 matches_requested = 3;
	optional uint32 hero_id = 4;
	optional uint32 request_id = 5;
}

Granted not all of them need to be used a the same time. But all of them do make sense (with the exception of the hero_id). So would you prefere them to be exposed individually as in function a(param1, param2,...) or would you prefere function a({param1, param2, ...})?

Thanks
Jens

**Comment by jimmydorry** [comment]
The array would make the most sense, as long as it is properly documented.

**Comment by RJacksonm1** [comment]
I think this has been completed in #90. Can anybody confirm?

**Comment by howardchung** [comment]
@pyarmak added it, I think.  I've never tried to use it myself.

**Comment by Crazy-Duck** [comment]
The method was added, but it has fixed arguments. Might want to refactor it to take 1 filter argument instead, kinda like lobbies.

**Comment by Crazy-Duck** [comment]
I've put a rework on my dev branch. I externalized the option parser from the configureLobby method in a separate file -> handlers/helper.js. createPracticeLobby, configureLobby and getPlayerMatchHistory all use this method to parse their input arguments. I made sure that all obligatory arguments are required on their respective interfaces.

**Comment by Crazy-Duck** [comment]
This issue can be closed I think, modification has been merged some weeks ago
