### ISSUE TITLE
Lobby invite implementation

### ISSUE THREAD

**Issue by paralin** [RJacksonm1/node-dota2#71]
There are new protos in place now for lobby invites. Need to implement these.

**Comment by paralin** [comment]
Implemented in http://github.com/paralin/Dota2 as a reference :)

**Comment by RJacksonm1** [comment]
Has this been done with #90 or is it still on the TODO list?

**Comment by Crazy-Duck** [comment]
Still TODO as far as I know

**Comment by paralin** [comment]
It's really simple.

**Comment by howardchung** [comment]
@Crazy-Duck I think you implemented this?  If you can confirm we can probably close this

**Comment by jimmydorry** [comment]
Probably this one. https://github.com/RJacksonm1/node-dota2/pull/132

**Comment by Crazy-Duck** [comment]
yup, that's the one
