### ISSUE TITLE
Lobby is always null, I am not getting any practiceLobbyUpdate

### ISSUE THREAD

**Issue by JonnanMedel** [RJacksonm1/node-dota2#75]
Hi, I'm trying to get the `Lobby` object to get its id. I'm looking to create some sort of autochecker of who's currently in the lobby and which team they are in.

But after creating it using `createPracticeLobby()`, `Lobby` is still  *null*. I've tried listening to `practiceLobbyUpdate` but i don't receive any event from it. 

Aside from that whenever I launch Dota2 client I get the following cache subscriptions

`5 Jun 23:40:23 - Sending ClientHello`
`5 Jun 23:40:25 - Received client welcome.5 Jun 23:40:2`
`5 - Cache subscribed, type undefined`
`5 Jun 23:40:25 - Unknown cache ID: undefined`
`5 Jun 23:40:25 - Unknown cache ID: undefined`
`5 Jun 23:40:25 - Unknown cache ID: undefined`
`5 Jun 23:40:25 - Unknown cache ID: undefined`
`5 Jun 23:40:25 - Unknown cache ID: undefined`
`5 Jun 23:40:25 - Unknown cache ID: undefined`

Am not sure if this is the expected output since. Could you enlighten me on this?

Thanks!

**Comment by JonnanMedel** [comment]
I've resolved this by updating cache.js with the following:

`function handleSubscribedType(obj)
{
  switch(obj.typeId)
  {...
  }
}
`

i changed `type_id` to `typeId`

**Comment by trainingday01** [comment]
7 Jul 11:11:50 - Cache subscribed, type undefined
7 Jul 11:11:50 - Unknown cache ID: undefined
7 Jul 11:11:50 - Unknown cache ID: undefined
7 Jul 11:11:50 - Unknown cache ID: undefined

I still have the same issue, even after changing the line in cache.js

**Comment by idreamshen** [comment]
try this.
https://github.com/idreamshen/node-dota2/commit/311008ed01cd7ab2418522c5301bf081654de52b

**Comment by trainingday01** [comment]
Was just doing the same, but you need to add this:

dota_gcmessages_common= new Schema(fs.readFileSync(__dirname + "/../generated/dota_gcmessages_common.desc")),

and change the cacheTypeIDs to:
var cacheTypeIDs = {
  LOBBY: 1,
  PARTY: 7,
  PARTY_INVITE: 39
};

After this I manage to get the snapshots BUT it still results in DOTA_JOIN_RESULT_INVALID_LOBBY, the lobby id seems the same all the time and it doesn't clear it.

**Comment by trainingday01** [comment]
Sorry, the cacheTypeIDS were right, my bad. Now it seems that cache works but I still get
Received create/leave response {"result":"DOTA_JOIN_RESULT_INVALID_LOBBY"}
:/
