### ISSUE TITLE
How to set your library, and you need to work it?

### ISSUE THREAD

**Issue by anar4you** [RJacksonm1/node-dota2#76]
Hello! I hasten to apologize for my English, I'm from Russia))
I want to organize a league through a web interface. I realized that your library I can help. But I can not understand what is needed for its operation and how to install it. I ask you to help. Thanks in advance!

**Comment by jimmydorry** [comment]
There is too much to explain. Read up on using nodejs, and then about how this library works https://blog.rjackson.me/extending-node-dota2/
