### ISSUE TITLE
Reborn support?

### ISSUE THREAD

**Issue by twisterghost** [RJacksonm1/node-dota2#77]
Will this package be broken when Reborn goes live? Does Reborn use the same GC as current Dota2? Any knowledge in this scope or is this a big if right now?

**Comment by idreamshen** [comment]
same question

**Comment by XenBG** [comment]
The same question. I see that when I create lobby in Dota 2 (Source 1), I can't see it from Dota 2 Reborn (Source 2).

**Comment by jimmydorry** [comment]
They are two different backends, so not surprising.

**Comment by paralin** [comment]
It's the same backend @jimmydorry.

That said I'm trying to get it to work in the C# version at paralin/Dota2 but no matter how much I implement it still doesn't seem to recognize it as Source2.

**Comment by TJRoger** [comment]
They are totally different. Refer to the resources files, you will see the `dota_s2` protobufs backend languages. Don't bother to worry about [node-dota2], worry about [node-steam] first

**Comment by paralin** [comment]
@TJRoger They aren't different, trust me on this one. The difference between dota and dota_s2 is where they were dumped from. The dota ones stopped being updated a while back. The nature of protobuf is that they are backwards compatible and since reborn is on the same gc as source 1, its just some newer calls added to the existing system. 

My proof for this is that the C# version now works with both reborn and regular...

**Comment by paralin** [comment]
The only difference is when you specify the source engine version in the hello message.

**Comment by TJRoger** [comment]
@paralin OK, you say it, I didn't look into it. Ah ha

**Comment by Crazy-Duck** [comment]
@paralin is it sufficient to just change the engine version in the CMsgClientHello or does the appId in the protobuf header also have be changed to [373300](https://steamdb.info/app/373300/) ?

**Comment by paralin** [comment]
App ID is the same. Just read the code in this file: https://github.com/paralin/Dota2/blob/master/Dota2/GC/DotaGCHandler.cs

**Comment by paralin** [comment]
Should work with PR #95

**Comment by jimmydorry** [comment]
Which was merged into master https://github.com/RJacksonm1/node-dota2/commit/2aaa38b455c26e05d00f2c162c6c02a56c618f13
