### ISSUE TITLE
onJoinChatChannelResponse not firing

### ISSUE THREAD

**Issue by Maxpain177** [RJacksonm1/node-dota2#78]
A few days ago valve updated dota2 and my lobby-bot broke.
When i send joinChat (```CMsgDOTAJoinChatChannel```) message, GC do not send me ```CMsgDOTAJoinChatChannelResponse```.

**Comment by RJacksonm1** [comment]
Need somebody to confirm this bug against the node-steam1.1.0 branch. If it's still an issue we should resolve it for the 1.0.0 release.

**Comment by devilesk** [comment]
It's working on the node-steam1.1.0 branch.

![](http://i.imgur.com/73lzgdj.png)

**Comment by RJacksonm1** [comment]
Thanks @devilesk 

In that case I'll close the issue, the fix will ship with 1.0.0.
