### ISSUE TITLE
node-dota2 cannot start 

### ISSUE THREAD

**Issue by TJRoger** [RJacksonm1/node-dota2#80]
node version: 0.12.7
error message: 
```
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/Roger/Developer/Node/bot/node-dota2/index.js:5:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```
anyone can help?
any suggestion will be apprecidated

**Comment by XenBG** [comment]
Use "npm use 0.10" and it will run.

**Comment by TJRoger** [comment]
@XenBG thx for help. But the node steam is using nodejs >v0.12. It's really frustrating.

**Comment by XenBG** [comment]
Okay, try to use my installation - http://esports.bg/node-dota2.zip - hope that help you :).

**Comment by trainingday01** [comment]
Try to use nvm (https://github.com/creationix/nvm)
nvm install 0.12.0

**Comment by TJRoger** [comment]
@XenBG I have completely uninstalled node, and then reinstalled. It works, but new error occurred.

**Comment by TJRoger** [comment]
New error:
```
Roger-MBA:dota2 observer Roger$ node index.js 
27 Jul 23:01:34 - sentry loaded
connecting to 146.66.152.13:27018
27 Jul 23:01:34 - Bot connecting ...
connected
encrypt request
27 Jul 23:01:35 - Bot trying to log in to steam network...
27 Jul 23:01:36 - Bot logged in!
As: (76561198047268298) 
tjroger's accountID: 87002570
tjroger's accountID: 87002570
steamID:76561198063164570
27 Jul 23:01:36 - Launching Dota 2
/Users/Roger/Developer/Node/node_modules/dota2/index.js:95
  this._client.gamesPlayed([this._appid]);
               ^
TypeError: undefined is not a function
    at Dota2Client.launch (/Users/Roger/Developer/Node/node_modules/dota2/index.js:95:16)
```

**Comment by graceda** [comment]
Hi @TJRoger i had same problem here, would you let me know how did you fix that error. Thx

**Comment by TJRoger** [comment]
@graceda you can refer to https://github.com/tjroger/node-dota2-spectator

**Comment by Vladislav719** [comment]
How you solve this problem, I have the same error.
If I use node v 0.10 I got this:
`  var cryptedSessionKey = crypto.publicEncrypt(publicKey, sessionKey);
                                 ^
TypeError: Object #<Object> has no method 'publicEncrypt'
`

If i use node v 0.12: 
` this._client.gamesPlayed([this._appid]);
               ^
TypeError: undefined is not a function
`

What I should do?

**Comment by TJRoger** [comment]
@Vladislav719 You can give it a try with my repo [node dota2 spectator](https://github.com/tjroger/node-dota2-spectator)

**Comment by Vladislav719** [comment]
@TJRoger I'm so sorry but I can't understand how I can use ur repo instead that. For example can I create a lobby using your repo? But exactly thanks for helps!

**Comment by TJRoger** [comment]
@Vladislav719 You can use my repo as a dota2 client. And extend it with your hanlders

**Comment by Vladislav719** [comment]
@TJRoger can you give some example of this? Perhaps do it in your repo, It would be very good.

**Comment by TJRoger** [comment]
@Vladislav719 OK, I will add handler sample today. A moment please
