### ISSUE TITLE
i have a problem

### ISSUE THREAD

**Issue by graceda** [RJacksonm1/node-dota2#81]
i'm sorry because i ask this, but i need to.
i'm new with nodejs.

i have followed your guide, setting up test folder,  used it but i got a problem. 
the problem is always same everytime i tried to run it at CentOS  7, CentOS 6, and also ubuntu.

i have tried to switch my node version, at last i switched it to 0.12 and it gave me error.

/home/lemkova/steam/node_modules/dota2/test/index.js:178
bot.logOn(logOnDetails);
    ^
TypeError: undefined is not a function
    at Object.<anonymous> (/home/lemkova/steam/node_modules/dota2/test/index.js:178:5)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

so, any idea what i have to do?

sorry for my english if it was bad.

**Comment by TJRoger** [comment]
I think it maybe a node version problem. I am trying to roll back my node to v0.10.x. I will update information about it when completed.

**Comment by TJRoger** [comment]
You should read this[]( https://github.com/seishun/node-steam)

**Comment by graceda** [comment]
'Note: only Node.js v0.12 and io.js v2.x are supported.'
so, should i use Node v0.12 and io.js v2.x ?

**Comment by graceda** [comment]
okay, i have tried to use node version 0.10.x but gave me error
`node_module_register undefined`

and i also have searched on google and found out that 
`The node_module_register internal API was added to Node.js in v0.11.11 `

but when i tried to use v0.11.11 or above gave me same error

bot.logOn(logOnDetails);
^
TypeError: undefined is not a function

**Comment by trainingday01** [comment]
Had the same problem, it is because node-steam has released a new version 1.0.0 which changes the logOn method, you have to change the package.json so the node-steam is below 1.0.0.

**Comment by TJRoger** [comment]
@graceda @trainingday01 the example file in node-dota2 is out-dated. You can refer to the node-steam login sample file to login to steam network

**Comment by graceda** [comment]
thanks for your help guys. it worked
