### ISSUE TITLE
How can i fetch the Dota 2 winrate/loses with this wrapper?

### ISSUE THREAD

**Issue by krelly** [RJacksonm1/node-dota2#84]
Is there any way to get player winrate/loses/total games without have to parsing all matches
profileRequest() returns only wins and abadonPercent
also it's imposible to do with  WebAPI GetMatchHistory request cause it limited to maximum of 500 games per user

**Comment by jimmydorry** [comment]
This library can only get what you can see in the client when looking at another user's profile. If it isn't in the profile then you don't get it.

Have another look at the webAPI. There are parameters you can use, like starting date, to shift the 500game window. Just remember that the webAPI rate limit is 100k calls a day, while this wrapper hits a much lower rate limit (if i recall correctly).

**Comment by krelly** [comment]
unfortunately valve removed filtering by time option

**Comment by jimmydorry** [comment]
Yea, I forgot about that. You can only move it by matchID now, and it won't move it past the 500 game window.

You are shit out of luck, unless you want to use the sequence API to parse through all the games, but even Dotabuff won't do that for a player looking to get their old history... as it would take a long time.
