### ISSUE TITLE
Dota GC always Already_in_game state

### ISSUE THREAD

**Issue by Vladislav719** [RJacksonm1/node-dota2#86]
I just try to create a lobby, but I have the following result message: 
`DOTA_JOIN_RESULT_ALREADY_IN_GAME`

code: 

`
Dota2.createPracticeLobby('Game_Name', '12345', Dota2.ServerRegion.EUROPE, Dota2.GameMode.DOTA_GAMEMODE_MO,
 function (err, body) {
                log.info(JSON.stringify(body));
                if (err)
                    log.info(JSON.stringify(err))
            });`

what could be the problem in?

**Comment by Vladislav719** [comment]
It seems I was wrong...

**Comment by jimmydorry** [comment]
Stale question with major library updates.
