### ISSUE TITLE
Lobby methods do not work

### ISSUE THREAD

**Issue by Vladislav719** [RJacksonm1/node-dota2#87]
in cache.js : 
`  switch(obj.type_id) ` 
"obj" hasn't field type_id, but typeId has, anyway 

`var lobby = dota_gcmessages_common.CSODOTALobby.parse(obj.object_data[0]); `
common does't declared in cache.js
Perhaps I'm doing something wrong? Is there some way to create a lobby, because I couldn't :(
Thanks a lot for answer

**Comment by jimmydorry** [comment]
PR 90 should fix it, when it is deployed.

**Comment by RJacksonm1** [comment]
Fixed in branch node-dota2/node-steam1.1.0, which will be deployed with 1.0.0 release in a couple of weeks, if not sooner.
