### ISSUE TITLE
node-dota2 is no longer compatible with the latest stable release of node-steam

### ISSUE THREAD

**Issue by Crazy-Duck** [RJacksonm1/node-dota2#88]
Since node-steam released their v1.0.0 node-dota2 is no longer compatible. Node-steam was made entirely modular, which changed the entire log on process. The dependencies should be updated to require node-steam version <= 0.6.8 or the example and the index.js should be migrated to support node-steam 1.0.0/1.1.0.

**Comment by jimmydorry** [comment]
Should be fixed with https://github.com/RJacksonm1/node-dota2/pull/89
