### ISSUE TITLE
how to join slot

### ISSUE THREAD

**Issue by yunruow** [RJacksonm1/node-dota2#91]
I'm able to create lobby and join the lobby. In order to launch the game automatically, I need to have player join the slot. We tried sending CMsgPracticeLobbySetTeamSlot to gc. We tried that without error, but no response from gc either. Here's my code. Any suggestions?

Dota2.Dota2Client.prototype.setPracticeLobbySlot = function(slotNumber, team, callback)
{
     callback = callback || null;
     /* Sends a message to the Game Coordinator setting slot. */
     if (!this._gcReady) {
         if (this.debug) util.log("GC not ready, please listen for the 'ready' event.");
         return null;
     }
     if (this.debug) util.log("Sending slot CMsgPracticeLobbySetTeamSlot request");  
     var payload = dota_gcmessages_client.CMsgPracticeLobbySetTeamSlot.serialize({
     "slot": 1
     });

this._client.toGC(this._appid, (Dota2.k_EMsgGCPracticeLobbySetTeamSlot | protoMask), payload, callback);
}

**Comment by jimmydorry** [comment]
You will probably want to nethook2 and see what's happening in the actual client. Seeing the messages will probably help in figuring out the logic.

I believe this is the most up to date nethook repo: https://github.com/SteamRE/SteamKit/tree/master/Resources/NetHook2

Installation instructions: https://github.com/SteamRE/SteamKit/wiki/Installation

**Comment by taloto07** [comment]
this._client.toGC(this._appid, (Dota2.k_EMsgGCPracticeLobbySetTeamSlot | protoMask), payload, callback);

You forgot: "EDOTAGCMsg"

this._client.toGC(this._appid, (Dota2.EDOTAGCMsg.k_EMsgGCPracticeLobbySetTeamSlot | protoMask), payload, callback);

**Comment by paralin** [comment]
vote to close this

**Comment by jimmydorry** [comment]
I suppose it is solved
