### ISSUE TITLE
is there a working version of the library?

### ISSUE THREAD

**Issue by Vladislav719** [RJacksonm1/node-dota2#93]
Perhaps one of forks has a working library? Because I have some errors running several repositories. Thanks for the help guys.

**Comment by jimmydorry** [comment]
PR 90 essentially will fix outstanding issues. The steam dependency was updated and not compatible with current version. You will need to downgrade to a version below 1, or wait until the PR is ready.

**Comment by Vladislav719** [comment]
Ok, thanks
