### ISSUE TITLE
Automated testing

### ISSUE THREAD

**Issue by RJacksonm1** [RJacksonm1/node-dota2#99]
I'll find some time to look into setting this up.

**Comment by howardchung** [comment]
in your own time, @RJacksonm1 .

Basically register this repo with Travis CI, create a new steam account without steam guard and put username/password in the Travis environment vars section.  We can then write mocha tests that read process.env and will run automatically on each commit.

**Comment by howardchung** [comment]
@jimmydorry if you have admin access can you set up travis?

**Comment by jimmydorry** [comment]
I don't have admin access. I don't see a settings tab on the side of the repo. :(

@RJacksonm1 pls deliver

**Comment by RJacksonm1** [comment]
https://travis-ci.org/RJacksonm1/node-dota2/builds/89829390

Eh.  Some of them failed. :\

**Comment by RJacksonm1** [comment]
Alright seems to be working now I configured it to run one build at a time, though it's pretty slow.  Do we need to be testing 5 versions of node?  Docs say we support 0.12 upwards, think we can get away testing 0.12, 4.2, and 5?

**Comment by RJacksonm1** [comment]
Let's continue discussion in #147.
